# -*- coding: utf-8 -*-
# Level 13 · B2 · Week 55 Body, Health & Medicine (Day 375–380) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level13/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=13, cefr='B2', title=title, emoji=emoji, theme='Body & Medicine',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(375,374,'Inside the Body','🫀','Day376_TheBodyatWork_B2.html','⚙️','tiles',
  'Structure and function: is responsible for / connects X to Y.',
  [('anatomy','กายวิภาค','/əˈnætəmi/','🦴'),('physiology','สรีรวิทยา','/ˌfɪziˈɒlədʒi/','⚙️'),
   ('ligament','เอ็นยึดข้อ','/ˈlɪɡəmənt/','🪢'),('cartilage','กระดูกอ่อน','/ˈkɑːtɪlɪdʒ/','🦵'),
   ('marrow','ไขกระดูก','/ˈmærəʊ/','🩸'),('artery','หลอดเลือดแดง','/ˈɑːtəri/','🔴'),
   ('capillary','หลอดเลือดฝอย','/kəˈpɪləri/','🕸️'),('kidney','ไต','/ˈkɪdni/','🫘'),
   ('gland','ต่อม','/ɡlænd/','💧')],
  "Anatomy describes the parts; physiology explains what they do. A ligament joins bone to bone and heals slowly. Cartilage cushions a joint and has almost no blood supply of its own. Bone marrow makes new blood cells every single day. An artery carries blood away from the heart under pressure. A capillary is so narrow that red cells pass through in single file. Each kidney filters your entire blood volume many times a day. A gland releases what the rest of the body has ordered.",
  ["Anatomy describes the parts; physiology explains what they do.",
   "A ligament joins bone to bone and heals slowly.",
   "Bone marrow makes new blood cells every single day.",
   "An artery carries blood away from the heart under pressure.",
   "A gland releases what the rest of the body has ordered."],
  ["Anatomy describes the parts; physiology explains what they do.",
   "Bone marrow makes new blood cells every single day.",
   "An artery carries blood away from the heart under pressure."],
  "What does an artery do?","It carries blood away from the heart."),

D(376,375,'The Body at Work','⚙️','Day377_WhenSomethingGoesWrong_B2.html','🦠','scramble',
  'Process description: is broken down / is absorbed / is carried to.',
  [('digestion','การย่อยอาหาร','/daɪˈdʒestʃən/','🍽️'),('intestine','ลำไส้','/ɪnˈtestɪn/','🌀'),
   ('liver','ตับ','/ˈlɪvə(r)/','🟤'),('pancreas','ตับอ่อน','/ˈpæŋkriəs/','🔺'),
   ('bloodflow','การไหลเวียนของเลือด','/ˈblʌdfləʊ/','🔄'),('immunology','วิทยาภูมิคุ้มกัน','/ˌɪmjuˈnɒlədʒi/','🛡️'),
   ('sterile','ปลอดเชื้อ','/ˈsteraɪl/','🧼'),('hydrated','ได้รับน้ำเพียงพอ','/haɪˈdreɪtɪd/','💦'),
   ('regimen','แผนการดูแลสุขภาพ','/ˈredʒɪmən/','📋')],
  "Digestion begins in the mouth, long before food reaches the stomach. The small intestine is about six metres long and folded carefully. The liver performs several hundred jobs and complains about none of them. The pancreas controls how much sugar stays in your blood. Good bloodflow matters more to your brain than to your legs. Immunology explains why children who meet more germs collect more colds. A sterile instrument carries no living organism at all. Staying hydrated affects concentration within hours, not days. A sensible regimen you actually follow beats a perfect one you abandon.",
  ["Digestion begins in the mouth, long before food reaches the stomach.",
   "The small intestine is about six metres long.",
   "The pancreas controls how much sugar stays in your blood.",
   "Immunology explains why children collect colds.",
   "A sensible regimen you actually follow beats a perfect one you abandon."],
  ["Digestion begins in the mouth.",
   "The pancreas controls how much sugar stays in your blood.",
   "A sensible regimen you follow beats a perfect one you abandon."],
  "Where does digestion begin?","It begins in the mouth."),

D(377,376,'When Something Goes Wrong','🦠','Day378_TheMedicineCabinet_B2.html','💊','memory',
  'Describing illness: presents with / is characterised by / resolves within.',
  [('pathogen','เชื้อก่อโรค','/ˈpæθədʒən/','🦠'),('infection','การติดเชื้อ','/ɪnˈfekʃn/','🌡️'),
   ('inflammation','การอักเสบ','/ˌɪnfləˈmeɪʃn/','🔥'),('contagious','ติดต่อได้','/kənˈteɪdʒəs/','🚷'),
   ('asymptomatic','ไม่แสดงอาการ','/ˌeɪsɪmptəˈmætɪk/','🤫'),('chronic','เรื้อรัง','/ˈkrɒnɪk/','🕰️'),
   ('acute','เฉียบพลัน','/əˈkjuːt/','⚡'),('fracture','กระดูกหัก','/ˈfræktʃə(r)/','🩼'),
   ('concussion','การกระทบกระเทือนสมอง','/kənˈkʌʃn/','💫')],
  "A pathogen is any organism that can cause disease. An infection is the body being colonised; illness is the body responding. Inflammation is a repair process that becomes a problem when it will not stop. A contagious illness spreads from person to person, which not all illnesses do. An asymptomatic carrier feels well and can still pass something on. A chronic condition is managed rather than cured. An acute problem arrives quickly and usually resolves. A small fracture may not show on the first image. Concussion is a brain injury even when nobody is knocked out.",
  ["A pathogen is any organism that can cause disease.",
   "Inflammation is a repair process that becomes a problem when it will not stop.",
   "An asymptomatic carrier feels well and can still pass something on.",
   "A chronic condition is managed rather than cured.",
   "Concussion is a brain injury even when nobody is knocked out."],
  ["A pathogen is any organism that can cause disease.",
   "A chronic condition is managed rather than cured.",
   "Concussion is a brain injury even when nobody is knocked out."],
  "How is a chronic condition treated?","It is managed rather than cured."),

D(378,377,'The Medicine Cabinet','💊','Day379_IntheHospital_B2.html','🏥','wordsearch',
  'Instruction and caution: take as directed / discontinue if / consult before.',
  [('antibiotic','ยาปฏิชีวนะ','/ˌæntibaɪˈɒtɪk/','💊'),('antiviral','ยาต้านไวรัส','/ˌæntiˈvaɪrəl/','🧪'),
   ('antiseptic','ยาฆ่าเชื้อภายนอก','/ˌæntiˈseptɪk/','🧴'),('immunise','สร้างภูมิคุ้มกัน','/ˈɪmjunaɪz/','💉'),
   ('placebo','ยาหลอก','/pləˈsiːbəʊ/','🍬'),('clinical','ทางคลินิก','/ˈklɪnɪkl/','🔬'),
   ('sideeffect','ผลข้างเคียง','/ˈsaɪdɪfekt/','⚠️'),('prescribe','สั่งจ่ายยา','/prɪˈskraɪb/','✍️'),
   ('remission','ภาวะโรคสงบ','/rɪˈmɪʃn/','🌤️')],
  "An antibiotic works on bacteria and does nothing at all to a virus. An antiviral must usually be started early to help. An antiseptic is for skin, not for swallowing. To immunise a population you need most of it, not all of it. A placebo can genuinely reduce pain, which is one of the strangest facts in medicine. A clinical trial compares the new treatment against the best current one. Every real medicine has a sideeffect; the question is whether it is worth it. Doctors prescribe fewer antibiotics now than twenty years ago, deliberately. Remission means the disease is quiet, not necessarily gone.",
  ["An antibiotic works on bacteria and does nothing at all to a virus.",
   "An antiseptic is for skin, not for swallowing.",
   "A clinical trial compares the new treatment against the best current one.",
   "Every real medicine has a sideeffect.",
   "Remission means the disease is quiet, not necessarily gone."],
  ["An antibiotic does nothing at all to a virus.",
   "Every real medicine has a sideeffect.",
   "Remission means the disease is quiet, not necessarily gone."],
  "Does an antibiotic work on a virus?","No, it does nothing at all to a virus."),

D(379,378,'In the Hospital','🏥','Day380_HealthforaWholeCountry_B2.html','🌏','vowels',
  'Hospital procedure: is admitted / is referred to / is discharged.',
  [('paramedic','เจ้าหน้าที่กู้ชีพ','/ˌpærəˈmedɪk/','🚑'),('triage','การคัดแยกผู้ป่วย','/ˈtriːɑːʒ/','🚦'),
   ('resuscitate','ช่วยฟื้นคืนชีพ','/rɪˈsʌsɪteɪt/','❤️'),('anaesthetic','ยาสลบ','/ˌænəsˈθetɪk/','😴'),
   ('surgeon','ศัลยแพทย์','/ˈsɜːdʒən/','🔪'),('transplant','การปลูกถ่ายอวัยวะ','/ˈtrænsplɑːnt/','🫀'),
   ('outpatient','ผู้ป่วยนอก','/ˈaʊtpeɪʃnt/','🚪'),('referral','การส่งต่อผู้ป่วย','/rɪˈfɜːrəl/','📨'),
   ('palliative','การดูแลประคับประคอง','/ˈpæliətɪv/','🤲')],
  "A paramedic makes decisions on a pavement that a hospital makes in a room. Triage treats the most urgent first, not the first to arrive. To resuscitate someone is exhausting and succeeds less often than television suggests. A general anaesthetic is closer to a controlled coma than to sleep. A surgeon spends more time deciding whether to operate than operating. A transplant depends entirely on somebody else's generosity. An outpatient goes home the same day. A referral is how one doctor asks a better qualified colleague. Palliative care treats the person when the illness can no longer be treated.",
  ["Triage treats the most urgent first, not the first to arrive.",
   "A general anaesthetic is closer to a controlled coma than to sleep.",
   "A surgeon spends more time deciding whether to operate than operating.",
   "A transplant depends entirely on somebody else's generosity.",
   "An outpatient goes home the same day."],
  ["Triage treats the most urgent first, not the first to arrive.",
   "A surgeon spends more time deciding whether to operate than operating.",
   "An outpatient goes home the same day."],
  "Who does triage treat first?","The most urgent, not the first to arrive."),

D(380,379,'Health for a Whole Country','🌏','Day381_Week55Review_B2.html','⭐','tiles',
  'Population-level claims: per hundred thousand / across the population.',
  [('epidemiology','ระบาดวิทยา','/ˌepɪdiːmiˈɒlədʒi/','📊'),('screening','การตรวจคัดกรอง','/ˈskriːnɪŋ/','🔎'),
   ('prognosis','การพยากรณ์โรค','/prɒɡˈnəʊsɪs/','🔮'),('midwife','ผดุงครรภ์','/ˈmɪdwaɪf/','👶'),
   ('paediatric','เกี่ยวกับเด็ก','/ˌpiːdiˈætrɪk/','🧸'),('geriatric','เกี่ยวกับผู้สูงอายุ','/ˌdʒeriˈætrɪk/','🧓'),
   ('primarycare','บริการปฐมภูมิ','/ˈpraɪmərikeə(r)/','🏘️'),('equitable','เป็นธรรมทั่วถึง','/ˈekwɪtəbl/','⚖️'),
   ('preventive','เชิงป้องกัน','/prɪˈventɪv/','☂️')],
  "Epidemiology studies illness in populations rather than in patients. A screening programme finds disease in people who feel perfectly well. A prognosis is a range of likelihoods, never a date. A trained midwife is one of the cheapest ways to save two lives at once. Paediatric medicine is not adult medicine at a smaller dose. Geriatric care asks what will keep this person independent. Strong primarycare reduces hospital admissions across a whole district. An equitable system is judged by how it treats the person with the least. Preventive spending is unpopular because success looks like nothing happening.",
  ["Epidemiology studies illness in populations rather than in patients.",
   "A screening programme finds disease in people who feel perfectly well.",
   "A prognosis is a range of likelihoods, never a date.",
   "Paediatric medicine is not adult medicine at a smaller dose.",
   "Preventive spending is unpopular because success looks like nothing happening."],
  ["A prognosis is a range of likelihoods, never a date.",
   "Paediatric medicine is not adult medicine at a smaller dose.",
   "Preventive spending is unpopular because success looks like nothing happening."],
  "Why is preventive spending unpopular?","Because success looks like nothing happening."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
