# -*- coding: utf-8 -*-
# Level 14 · B2 · Week 58 Literature & Storytelling (Day 398–403) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level14/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=14, cefr='B2', title=title, emoji=emoji, theme='Literature',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(398,397,'What Makes a Story','📖','Day399_WhoIsTelling_B2.html','👁️','tiles',
  'Narrative analysis: the turning point occurs when / the tension arises from.',
  [('protagonist','ตัวเอก','/prəˈtæɡənɪst/','🧍'),('antagonist','ตัวร้ายผู้ขัดขวาง','/ænˈtæɡənɪst/','😈'),
   ('exposition','การปูเรื่อง','/ˌekspəˈzɪʃn/','🗺️'),('climax','จุดสูงสุดของเรื่อง','/ˈklaɪmæks/','⛰️'),
   ('denouement','บทคลี่คลาย','/deɪˈnuːmɒ̃/','🎀'),('subplot','เรื่องรอง','/ˈsʌbplɒt/','🧵'),
   ('foreshadow','ปูเงื่อนล่วงหน้า','/fɔːˈʃædəʊ/','🌑'),('suspense','ความลุ้นระทึก','/səˈspens/','😬'),
   ('cliffhanger','ตอนจบค้างคา','/ˈklɪfhæŋə(r)/','🪝')],
  "A protagonist is not always likeable and must always want something. The best antagonist believes they are the hero of their own story. Exposition is necessary and should be almost invisible. The climax is the moment the main question is finally answered. The denouement lets the reader breathe out. A good subplot echoes the main story instead of interrupting it. To foreshadow well is to make the ending feel both surprising and inevitable. Suspense is created by what the reader knows and the character does not. A cliffhanger works once per book and annoys everyone after that.",
  ["A protagonist is not always likeable and must always want something.",
   "The best antagonist believes they are the hero of their own story.",
   "The climax is the moment the main question is finally answered.",
   "A good subplot echoes the main story instead of interrupting it.",
   "Suspense is created by what the reader knows and the character does not."],
  ["The best antagonist believes they are the hero of their own story.",
   "The climax is the moment the main question is finally answered.",
   "Exposition is necessary and should be almost invisible."],
  "What is the climax?","The moment the main question is finally answered."),

D(399,398,'Who Is Telling','👁️','Day400_TheMusicofWords_B2.html','🎵','scramble',
  'Point of view: from the perspective of / as filtered through.',
  [('omniscient','ผู้เล่ารู้ทุกอย่าง','/ɒmˈnɪsiənt/','👁️'),('firstperson','เล่าจากมุมฉัน','/ˈfɜːstpɜːsn/','🙋'),
   ('unreliable','ผู้เล่าที่เชื่อไม่ได้','/ʌnrɪˈlaɪəbl/','🌀'),('monologue','บทพูดคนเดียว','/ˈmɒnəlɒɡ/','🎙️'),
   ('soliloquy','บทรำพึงกับตัวเอง','/səˈlɪləkwi/','💭'),('dialogue','บทสนทนา','/ˈdaɪəlɒɡ/','💬'),
   ('characterisation','การสร้างตัวละคร','/ˌkærəktəraɪˈzeɪʃn/','🎨'),('archetype','ต้นแบบตัวละคร','/ˈɑːkitaɪp/','🗿'),
   ('foil','ตัวละครที่ขับให้อีกตัวเด่น','/fɔɪl/','🪞')],
  "An omniscient narrator can enter any head and often enters too many. A firstperson story is limited on purpose, which is its strength. An unreliable narrator makes the reader do detective work. A monologue is one character speaking to others at length. A soliloquy is a character speaking honestly because nobody is listening. Dialogue should sound like speech without actually being a transcript. Characterisation happens through choices under pressure, not through descriptions of eyes. An archetype is a shape a character can start from, not a shape to stay in. A foil exists to make the main character visible by contrast.",
  ["An omniscient narrator can enter any head and often enters too many.",
   "A firstperson story is limited on purpose, which is its strength.",
   "An unreliable narrator makes the reader do detective work.",
   "Dialogue should sound like speech without actually being a transcript.",
   "A foil exists to make the main character visible by contrast."],
  ["A firstperson story is limited on purpose, which is its strength.",
   "Dialogue should sound like speech without being a transcript.",
   "A foil makes the main character visible by contrast."],
  "Why does a foil exist?","To make the main character visible by contrast."),

D(400,399,'The Music of Words','🎵','Day401_KindsofStory_B2.html','📚','memory',
  'Figurative language: as if / is likened to / stands in for.',
  [('simile','อุปมาที่ใช้คำเปรียบ','/ˈsɪməli/','🪁'),('personification','การให้สิ่งไร้ชีวิตมีชีวิต','/pəˌsɒnɪfɪˈkeɪʃn/','🌻'),
   ('hyperbole','อติพจน์เกินจริง','/haɪˈpɜːbəli/','🎈'),('imagery','ภาพพจน์','/ˈɪmɪdʒəri/','🖼️'),
   ('alliteration','การเล่นเสียงพยัญชนะซ้ำ','/əˌlɪtəˈreɪʃn/','🔁'),('symbolism','สัญลักษณ์นิยม','/ˈsɪmbəlɪzəm/','🕊️'),
   ('allegory','นิทานเปรียบเทียบ','/ˈæləɡəri/','🗝️'),('stanza','บทกลอน','/ˈstænzə/','📜'),
   ('prose','ร้อยแก้ว','/prəʊz/','📄')],
  "A simile says one thing is like another and keeps a polite distance. Personification gives the wind a temper and the sea a mood. Hyperbole is not lying; everyone present knows the scale is wrong. Strong imagery reaches the senses before it reaches the argument. Alliteration is why so many shops have names that repeat one sound. Symbolism only works if the object also makes sense literally. An allegory tells one story on the surface and a second underneath. A stanza is to a poem what a paragraph is to prose. Good prose has rhythm even when nobody notices it.",
  ["A simile says one thing is like another.",
   "Personification gives the wind a temper and the sea a mood.",
   "Hyperbole is not lying; everyone present knows the scale is wrong.",
   "An allegory tells one story on the surface and a second underneath.",
   "Good prose has rhythm even when nobody notices it."],
  ["Personification gives the wind a temper and the sea a mood.",
   "An allegory tells one story on the surface and a second underneath.",
   "Good prose has rhythm even when nobody notices it."],
  "Is hyperbole a lie?","No, everyone present knows the scale is wrong."),

D(401,400,'Kinds of Story','📚','Day402_FromManuscripttoShelf_B2.html','📦','wordsearch',
  'Classification: falls into / can be grouped as / belongs to the tradition of.',
  [('category','ประเภทหมวดหมู่','/ˈkætəɡəri/','🗂️'),('fable','นิทานสอนใจ','/ˈfeɪbl/','🐢'),
   ('parable','อุปมานิทานสอนธรรม','/ˈpærəbl/','🌾'),('epic','มหากาพย์','/ˈepɪk/','⚔️'),
   ('tragedy','โศกนาฏกรรม','/ˈtrædʒədi/','🎭'),('satire','งานเสียดสี','/ˈsætaɪə(r)/','🃏'),
   ('parody','งานล้อเลียน','/ˈpærədi/','🙃'),('anthology','หนังสือรวมเรื่อง','/ænˈθɒlədʒi/','📚'),
   ('worldbuilding','การสร้างโลกในเรื่อง','/ˈwɜːldbɪldɪŋ/','🌍')],
  "A category is a promise to the reader about the kind of pleasure ahead. A fable uses animals to say something about people. A parable makes you supply the meaning yourself. An epic follows a hero across a whole world and usually a whole war. In tragedy the flaw belongs to the hero, not to bad luck. Satire attacks by pretending to agree. Parody imitates a style closely enough to expose it. A good anthology introduces you to five writers you would never have found. Worldbuilding is invisible when it is done well and everywhere when it is not.",
  ["A category is a promise to the reader about the kind of pleasure ahead.",
   "A fable uses animals to say something about people.",
   "A parable makes you supply the meaning yourself.",
   "Satire attacks by pretending to agree.",
   "In tragedy the flaw belongs to the hero, not to bad luck."],
  ["A fable uses animals to say something about people.",
   "Satire attacks by pretending to agree.",
   "A parable makes you supply the meaning yourself."],
  "How does satire attack?","It attacks by pretending to agree."),

D(402,401,'From Manuscript to Shelf','📦','Day403_ReadingClosely_B2.html','🔍','vowels',
  'Publishing process: is submitted to / is accepted for / goes into print.',
  [('typescript','ต้นฉบับพิมพ์ส่งสำนักพิมพ์','/ˈtaɪpskrɪpt/','📝'),('publisher','สำนักพิมพ์','/ˈpʌblɪʃə(r)/','🏢'),
   ('royalties','ค่าลิขสิทธิ์ผู้เขียน','/ˈrɔɪəltiz/','💰'),('bestseller','หนังสือขายดี','/ˌbestˈselə(r)/','🏆'),
   ('excerpt','บทตัดตอน','/ˈeksɜːpt/','✂️'),('prologue','บทนำเรื่อง','/ˈprəʊlɒɡ/','🚪'),
   ('epilogue','บทส่งท้าย','/ˈepɪlɒɡ/','🌅'),('retelling','การเล่าใหม่ในสื่ออื่น','/ˌriːˈtelɪŋ/','🎬'),
   ('screenplay','บทภาพยนตร์','/ˈskriːnpleɪ/','🎞️')],
  "A finished typescript is the beginning of the work, not the end. A publisher takes the financial risk and earns the larger share for it. Royalties usually arrive twice a year and rarely change a life. A bestseller is made in the first three weeks or not at all. An excerpt in a magazine sells more copies than any advertisement. A prologue should earn its place or be deleted. An epilogue answers the question the reader will otherwise ask on the last page. Every retelling must cut something the readers loved. A screenplay is mostly what people do, not what they think.",
  ["A finished typescript is the beginning of the work, not the end.",
   "A publisher takes the financial risk and earns the larger share for it.",
   "A bestseller is made in the first three weeks or not at all.",
   "A prologue should earn its place or be deleted.",
   "Every retelling must cut something the readers loved."],
  ["A finished typescript is the beginning of the work, not the end.",
   "A prologue should earn its place or be deleted.",
   "Every retelling must cut something the readers loved."],
  "When is a bestseller made?","In the first three weeks or not at all."),

D(403,402,'Reading Closely','🔍','Day404_Week58Review_B2.html','⭐','tiles',
  'Literary judgement: the passage suggests / the choice of word implies.',
  [('theme','แก่นเรื่อง','/θiːm/','🧭'),('recurringimage','ภาพที่วนกลับมาซ้ำ','/rɪˈkɜːrɪŋˌɪmɪdʒ/','🔷'),
   ('pacing','จังหวะการดำเนินเรื่อง','/ˈpeɪsɪŋ/','⏱️'),('closure','การจบลงอย่างลงตัว','/ˈkləʊʒə(r)/','✅'),
   ('interpretive','เชิงตีความ','/ɪnˈtɜːprətɪv/','🔬'),('criticism','การวิจารณ์วรรณกรรม','/ˈkrɪtɪsɪzəm/','✒️'),
   ('canon','ชุดวรรณกรรมที่ยอมรับกัน','/ˈkænən/','🏛️'),('closeread','การอ่านเจาะลึกทีละบรรทัด','/ˈkləʊsriːd/','🔎'),
   ('resonate','สะเทือนใจกินใจ','/ˈrezəneɪt/','🔔')],
  "A theme is what the book is about underneath what happens in it. A recurringimage is a small thing that keeps coming back until you notice it. Pacing is the difference between a long book and a slow one. Closure need not be happy; it must be earned. An interpretive reading offers evidence, not merely a feeling. Criticism at its best makes you want to read the book again. Every canon reflects who was allowed to publish at the time. A closeread exercise asks you to defend a reading from six lines alone. A story that continues to resonate is usually about something ordinary.",
  ["A theme is what the book is about underneath what happens in it.",
   "A recurringimage is a small thing that keeps coming back until you notice it.",
   "Pacing is the difference between a long book and a slow one.",
   "Closure need not be happy; it must be earned.",
   "Criticism at its best makes you want to read the book again."],
  ["A recurringimage is a small thing that keeps coming back until you notice it.",
   "Pacing is the difference between a long book and a slow one.",
   "Closure need not be happy; it must be earned."],
  "Must closure be happy?","No, but it must be earned."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
