# -*- coding: utf-8 -*-
# Level 12 · B2 · Week 50 Technology & Digital Life (Day 338–343) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level12/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=12, cefr='B2', title=title, emoji=emoji, theme='Technology',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(338,337,'How Machines Think','💻','Day339_TheNetworkBeneath_B2.html','🌐','tiles',
  'Explaining limits: can only / is unable to / is limited by.',
  [('binary','ระบบเลขฐานสอง','/ˈbaɪnəri/','🔢'),('processor','หน่วยประมวลผล','/ˈprəʊsesə(r)/','🧠'),
   ('cache','หน่วยความจำพักข้อมูล','/kæʃ/','🗃️'),('interface','ส่วนติดต่อผู้ใช้','/ˈɪntəfeɪs/','🖥️'),
   ('pixel','จุดภาพ','/ˈpɪksl/','🟦'),('resolution','ความละเอียดภาพ','/ˌrezəˈluːʃn/','🔎'),
   ('render','ประมวลผลออกเป็นภาพ','/ˈrendə(r)/','🖼️'),('glitch','ความผิดพลาดชั่วคราว','/ɡlɪtʃ/','⚠️'),
   ('obsolete','ล้าสมัยจนใช้ไม่ได้','/ˈɒbsəliːt/','🕰️')],
  "A computer knows only binary: on and off, nothing in between. The processor does simple things extremely quickly, and that is all. A cache keeps the answer nearby so it need not be found twice. A good interface disappears; you notice only the bad ones. One pixel is a single coloured square in a grid of millions. Higher resolution means more detail and a much larger file. To render a page is to turn code into something you can look at. A glitch is temporary; a fault is not. Software becomes obsolete faster than the machine it runs on.",
  ["A computer knows only binary: on and off, nothing in between.",
   "A cache keeps the answer nearby so it need not be found twice.",
   "A good interface disappears; you notice only the bad ones.",
   "Higher resolution means more detail and a much larger file.",
   "A glitch is temporary; a fault is not."],
  ["A good interface disappears; you notice only the bad ones.",
   "Higher resolution means more detail and a much larger file.",
   "A glitch is temporary; a fault is not."],
  "What does a good interface do?","It disappears; you notice only the bad ones."),

D(339,338,'The Network Beneath','🌐','Day340_StayingSafeOnline_B2.html','🔐','scramble',
  'Sequencing technical steps: first the request is sent, then it is routed.',
  [('protocol','ระเบียบวิธีสื่อสาร','/ˈprəʊtəkɒl/','📋'),('router','เราเตอร์','/ˈruːtə(r)/','📡'),
   ('bandwidth','แบนด์วิดท์','/ˈbændwɪdθ/','🛣️'),('latency','ความหน่วง','/ˈleɪtənsi/','⏱️'),
   ('wireless','ไร้สาย','/ˈwaɪələs/','📶'),('streaming','การส่งข้อมูลต่อเนื่อง','/ˈstriːmɪŋ/','▶️'),
   ('buffering','การพักข้อมูลรอเล่น','/ˈbʌfərɪŋ/','⏳'),('browser','เว็บเบราว์เซอร์','/ˈbraʊzə(r)/','🧭'),
   ('cookie','คุกกี้เว็บ','/ˈkʊki/','🍪')],
  "A protocol is an agreement about how two machines will speak. Your router decides where each small packet goes next. Bandwidth is how wide the road is. Latency is how long the journey takes. A wireless signal weakens through walls and through water. Streaming sends the film in pieces so you need not wait for all of it. Buffering means the pieces are arriving more slowly than you are watching. A browser is a program that reads instructions written by strangers. A cookie remembers you, which is convenient and worth thinking about.",
  ["A protocol is an agreement about how two machines will speak.",
   "Bandwidth is how wide the road is.",
   "Latency is how long the journey takes.",
   "A wireless signal weakens through walls and through water.",
   "A browser is a program that reads instructions written by strangers."],
  ["Bandwidth is how wide the road is.",
   "Latency is how long the journey takes.",
   "A wireless signal weakens through walls and through water."],
  "What is latency?","It is how long the journey takes."),

D(340,339,'Staying Safe Online','🔐','Day341_MachinesThatLearn_B2.html','🤖','memory',
  'Warnings: on no account should you / never under any circumstances.',
  [('encryption','การเข้ารหัส','/ɪnˈkrɪpʃn/','🔐'),('firewall','ไฟร์วอลล์','/ˈfaɪəwɔːl/','🧱'),
   ('malware','โปรแกรมมุ่งร้าย','/ˈmælweə(r)/','🐛'),('phishing','การหลอกเอาข้อมูล','/ˈfɪʃɪŋ/','🎣'),
   ('scam','การหลอกลวง','/skæm/','🚨'),('passcode','รหัสผ่าน','/ˈpɑːskəʊd/','🔑'),
   ('biometric','ใช้ลักษณะทางกาย','/ˌbaɪəʊˈmetrɪk/','👆'),('backup','ข้อมูลสำรอง','/ˈbækʌp/','💾'),
   ('anonymity','การไม่เปิดเผยตัวตน','/ˌænəˈnɪməti/','🎭')],
  "Encryption turns a message into noise for everyone except the reader you chose. A firewall decides what is allowed through the door. Malware usually arrives because somebody clicked, not because somebody hacked. Phishing works by creating hurry: act now, or lose access. A scam that seems urgent and secret is almost always a scam. A long passcode beats a complicated short one. Biometric locks are convenient, and you cannot change your fingerprint. A backup you have never tested is a hope, not a backup. Anonymity protects the vulnerable and shelters the cruel at the same time.",
  ["Encryption turns a message into noise for everyone except the reader you chose.",
   "Malware usually arrives because somebody clicked.",
   "Phishing works by creating hurry: act now, or lose access.",
   "A long passcode beats a complicated short one.",
   "A backup you have never tested is a hope, not a backup."],
  ["Malware usually arrives because somebody clicked.",
   "A long passcode beats a complicated short one.",
   "A backup you have never tested is a hope, not a backup."],
  "How does phishing work?","It works by creating hurry."),

D(341,340,'Machines That Learn','🤖','Day342_TheAttentionMarket_B2.html','📱','wordsearch',
  'Qualified claims: appears to / is often assumed to / is not necessarily.',
  [('dataset','ชุดข้อมูลฝึก','/ˈdeɪtəset/','📚'),('throttle','จำกัดความเร็วการใช้งาน','/ˈθrɒtl/','🧮'),
   ('chatbot','แชตบอต','/ˈtʃætbɒt/','💬'),('deepfake','วิดีโอปลอมด้วย AI','/ˈdiːpfeɪk/','🪄'),
   ('autocorrect','การแก้คำอัตโนมัติ','/ˌɔːtəʊkəˈrekt/','✏️'),('recommendation','การแนะนำเนื้อหา','/ˌrekəmenˈdeɪʃn/','👍'),
   ('explainable','อธิบายเหตุผลได้','/ɪkˈspleɪnəbl/','🪟'),('auditable','ตรวจสอบย้อนหลังได้','/ˈɔːdɪtəbl/','⚖️'),
   ('automate','ทำให้เป็นอัตโนมัติ','/ˈɔːtəmeɪt/','⚙️')],
  "A model is only as fair as the dataset it was trained on. A system may throttle your access when you ask for too much at once. A chatbot sounds confident whether or not it is correct. A convincing deepfake costs almost nothing to make now. Autocorrect has quietly changed how a generation spells. A recommendation is a guess dressed as a suggestion. An explainable system lets people ask how a decision was reached. An auditable system keeps a record somebody can check later. To automate a bad process is to do the wrong thing faster.",
  ["A model is only as fair as the dataset it was trained on.",
   "A system may throttle your access when you ask for too much at once.",
   "A chatbot sounds confident whether or not it is correct.",
   "A recommendation is a guess dressed as a suggestion.",
   "To automate a bad process is to do the wrong thing faster."],
  ["A system may throttle your access when you ask for too much at once.",
   "A chatbot sounds confident whether or not it is correct.",
   "To automate a bad process is to do the wrong thing faster."],
  "What happens if you automate a bad process?","You do the wrong thing faster."),

D(342,341,'The Attention Market','📱','Day343_LivingWellwithScreens_B2.html','🌿','vowels',
  'Describing incentives: is designed to / is optimised for / rewards.',
  [('marketplace','ตลาดออนไลน์','/ˈmɑːkɪtpleɪs/','🏗️'),('engagement','การมีส่วนร่วมกับเนื้อหา','/ɪnˈɡeɪdʒmənt/','❤️'),
   ('viral','แพร่กระจายเร็วมาก','/ˈvaɪrəl/','🚀'),('tracker','ตัวติดตามพฤติกรรม','/ˈtrækə(r)/','👣'),
   ('spam','ข้อความขยะ','/spæm/','🗑️'),('troll','ผู้ป่วนออนไลน์','/trəʊl/','👹'),
   ('misinformation','ข้อมูลผิดที่แพร่ไป','/ˌmɪsɪnfəˈmeɪʃn/','📰'),('curate','คัดสรรเนื้อหา','/kjʊəˈreɪt/','🗂️'),
   ('subscription','การสมัครสมาชิก','/səbˈskrɪpʃn/','🎟️')],
  "An online marketplace is not neutral; it is built to hold your attention. Engagement counts anger just as happily as it counts delight. Something goes viral because it makes people feel, not because it is true. A tracker follows you across sites you never asked it to visit. Spam survives because it costs almost nothing to send a million messages. Do not feed a troll; a troll is fed by replies. Misinformation spreads faster than the correction ever will. To curate your own feed is a small act of self defence. A subscription is honest: you pay with money instead of with attention.",
  ["An online marketplace is not neutral; it is built to hold your attention.",
   "Engagement counts anger just as happily as it counts delight.",
   "Something goes viral because it makes people feel, not because it is true.",
   "Misinformation spreads faster than the correction ever will.",
   "To curate your own feed is a small act of self defence."],
  ["An online marketplace is not neutral; it is built to hold your attention.",
   "Misinformation spreads faster than the correction ever will.",
   "To curate your own feed is a small act of self defence."],
  "Why does something go viral?","Because it makes people feel, not because it is true."),

D(343,342,'Living Well with Screens','🌿','Day344_Week50Review_B2.html','⭐','tiles',
  'Balanced conclusion: on balance / all things considered / it comes down to.',
  [('upgrade','ปรับรุ่นให้ใหม่ขึ้น','/ˌʌpˈɡreɪd/','⬆️'),('compatible','ใช้ร่วมกันได้','/kəmˈpætəbl/','🔌'),
   ('archive','จัดเก็บถาวร','/ˈɑːkaɪv/','📦'),('unplugged','ถอดปลั๊กจากโลกออนไลน์','/ˌʌnˈplʌɡd/','✈️'),
   ('moderate','กำกับดูแลเนื้อหา','/ˈmɒdəreɪt/','🛡️'),('harassment','การคุกคาม','/ˈhærəsmənt/','🚫'),
   ('restraint','การยับยั้งชั่งใจ','/rɪˈstreɪnt/','🚧'),('deliberate','ทำอย่างตั้งใจ','/dɪˈlɪbərət/','🎯'),
   ('intentional','ทำอย่างมีเจตนาชัดเจน','/ɪnˈtenʃənl/','👁️')],
  "You do not need to upgrade a device that still does its job. Check whether the new file is compatible before you delete the old one. Archive what matters and delete what does not. An unplugged evening is not a punishment. Communities that moderate well are pleasant places to be. Online harassment is not less real for happening through a screen. A little restraint about when you are reachable protects everyone, including you. Deliberate use means opening an app for a reason you can name. Intentional use is the difference between a tool and a habit.",
  ["You do not need to upgrade a device that still does its job.",
   "Archive what matters and delete what does not.",
   "Online harassment is not less real for happening through a screen.",
   "Deliberate use means opening an app for a reason you can name.",
   "Intentional use is the difference between a tool and a habit."],
  ["Archive what matters and delete what does not.",
   "Deliberate use means opening an app for a reason you can name.",
   "Intentional use is the difference between a tool and a habit."],
  "What does deliberate use mean?","Opening an app for a reason you can name."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
