# -*- coding: utf-8 -*-
# Level 10 · B1 · Week 43 Art, Craft & Performance (Day 285–290)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level10/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=10, cefr='B1', title=title, emoji=emoji, theme='Art & Creativity',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(285,284,'Lines and Colours','🎨','Day286_WaysofMaking_B1.html','🏺','tiles',
  'Describing with -ing clauses: a girl holding a brush, standing by the window.',
  [('outline','เส้นร่างโครง','/ˈaʊtlaɪn/','✏️'),('shading','การลงน้ำหนักเงา','/ˈʃeɪdɪŋ/','🌑'),
   ('texture','พื้นผิว','/ˈtekstʃə(r)/','🧱'),('palette','จานสี','/ˈpælət/','🎨'),
   ('pigment','เม็ดสี','/ˈpɪɡmənt/','🧪'),('canvas','ผ้าใบวาดภาพ','/ˈkænvəs/','⬜'),
   ('easel','ขาตั้งภาพ','/ˈiːzl/','🔺'),('brushstroke','ฝีแปรง','/ˈbrʌʃstrəʊk/','🖌️')],
  "Start with a light outline you can still erase. Shading is what turns a circle into a ball. Rough paper gives a drawing texture. Keep your palette small and the picture stays calm. Blue pigment was once more costly than gold. A fresh canvas frightens almost every artist. Set the easel where the light falls from the side. One confident brushstroke beats ten careful ones.",
  ["Start with a light outline you can still erase.",
   "Shading is what turns a circle into a ball.",
   "Keep your palette small and the picture stays calm.",
   "A fresh canvas frightens almost every artist.",
   "One confident brushstroke beats ten careful ones."],
  ["Shading is what turns a circle into a ball.",
   "A fresh canvas frightens almost every artist.",
   "One confident brushstroke beats ten careful ones."],
  "What turns a circle into a ball?","Shading turns a circle into a ball."),

D(286,285,'Ways of Making','🏺','Day287_IntheGallery_B1.html','🖼️','scramble',
  'Materials and method: made of / made from / made by hand.',
  [('sculpture','งานประติมากรรม','/ˈskʌlptʃə(r)/','🗿'),('ceramic','เครื่องเซรามิก','/səˈræmɪk/','🍶'),
   ('mosaic','ภาพโมเสก','/məʊˈzeɪɪk/','🔲'),('engraving','งานแกะสลักลาย','/ɪnˈɡreɪvɪŋ/','🔨'),
   ('printmaking','งานพิมพ์ภาพ','/ˈprɪntmeɪkɪŋ/','📰'),('handmade','ทำด้วยมือ','/ˌhændˈmeɪd/','🤲'),
   ('artisan','ช่างฝีมือ','/ˌɑːtɪˈzæn/','🧑‍🔧'),('portrait','ภาพเหมือนบุคคล','/ˈpɔːtreɪt/','🧑‍🎨')],
  "A sculpture is finished when nothing more can be removed. Every ceramic bowl bends a little in the fire. A mosaic is thousands of small decisions. An engraving keeps its line for four hundred years. Printmaking lets one idea reach a hundred homes. Handmade does not mean perfect, and that is the point. An artisan learns by repeating, not by reading. A good portrait shows the person on an ordinary day.",
  ["A sculpture is finished when nothing more can be removed.",
   "Every ceramic bowl bends a little in the fire.",
   "A mosaic is thousands of small decisions.",
   "Handmade does not mean perfect.",
   "An artisan learns by repeating, not by reading."],
  ["A mosaic is thousands of small decisions.",
   "Handmade does not mean perfect.",
   "An artisan learns by repeating, not by reading."],
  "How does an artisan learn?","By repeating, not by reading."),

D(287,286,'In the Gallery','🖼️','Day288_ClothandThread_B1.html','🧵','memory',
  'Opinion language: it strikes me as / what I find interesting is.',
  [('exhibition','นิทรรศการ','/ˌeksɪˈbɪʃn/','🏛️'),('gallery','หอศิลป์','/ˈɡæləri/','🖼️'),
   ('curator','ภัณฑารักษ์','/kjʊəˈreɪtə(r)/','🗝️'),('masterpiece','ผลงานชิ้นเอก','/ˈmɑːstəpiːs/','⭐'),
   ('abstract','นามธรรม','/ˈæbstrækt/','🌀'),('realistic','เหมือนจริง','/ˌrɪəˈlɪstɪk/','📷'),
   ('symmetry','ความสมมาตร','/ˈsɪmətri/','🦋'),('proportion','สัดส่วน','/prəˈpɔːʃn/','📐')],
  "The exhibition runs for three more weeks. This gallery is free on the first Sunday. A curator decides what you see and in what order. Nobody agrees on which painting is the masterpiece. An abstract picture asks you to feel before you understand. A realistic drawing hides all its hard work. Perfect symmetry can look cold. Getting the proportion right matters more than getting the colour right.",
  ["The exhibition runs for three more weeks.",
   "This gallery is free on the first Sunday.",
   "A curator decides what you see and in what order.",
   "An abstract picture asks you to feel before you understand.",
   "Perfect symmetry can look cold."],
  ["This gallery is free on the first Sunday.",
   "A curator decides what you see and in what order.",
   "Perfect symmetry can look cold."],
  "When is the gallery free?","On the first Sunday."),

D(288,287,'Cloth and Thread','🧵','Day289_DesignThatWorks_B1.html','📐','wordsearch',
  'Purpose and result: so as to / in such a way that.',
  [('embroidery','งานปักผ้า','/ɪmˈbrɔɪdəri/','🪡'),('weaving','การทอผ้า','/ˈwiːvɪŋ/','🧶'),
   ('dye','ย้อมสี','/daɪ/','🫙'),('vibrant','สีสดใส','/ˈvaɪbrənt/','🌈'),
   ('muted','สีนุ่มไม่ฉูดฉาด','/ˈmjuːtɪd/','🌫️'),('motif','ลวดลายซ้ำ','/məʊˈtiːf/','🔷'),
   ('backdrop','ฉากหลัง','/ˈbækdrɒp/','🎦'),('choreography','การออกแบบท่าเต้น','/ˌkɒriˈɒɡrəfi/','🕺')],
  "Her grandmother taught her embroidery at seven. Weaving turns thread into something that can hold weight. Village families dye cloth with leaves and mud. A vibrant red comes from one small insect. Muted colours last longer in the sun. A repeated motif turns cloth into a story. The stage backdrop was sewn by the students themselves. Good choreography makes eight dancers look like one.",
  ["Her grandmother taught her embroidery at seven.",
   "Weaving turns thread into something that can hold weight.",
   "Village families dye cloth with leaves and mud.",
   "Muted colours last longer in the sun.",
   "Good choreography makes eight dancers look like one."],
  ["Village families dye cloth with leaves and mud.",
   "Muted colours last longer in the sun.",
   "Good choreography makes eight dancers look like one."],
  "What does good choreography do?","It makes eight dancers look like one."),

D(289,288,'Design That Works','📐','Day290_MakingMusicTogether_B1.html','🎼','vowels',
  'Evaluating: works well / falls short / could be improved by.',
  [('typography','การออกแบบตัวอักษร','/taɪˈpɒɡrəfi/','🔠'),('layout','การจัดวางองค์ประกอบ','/ˈleɪaʊt/','📄'),
   ('illustration','ภาพประกอบ','/ˌɪləˈstreɪʃn/','🖍️'),('mockup','แบบจำลองงานออกแบบ','/ˈmɒkʌp/','🧩'),
   ('improvise','ด้นสด','/ˈɪmprəvaɪz/','🎲'),('audition','การคัดเลือกตัวแสดง','/ɔːˈdɪʃn/','🎤'),
   ('encore','การแสดงเพิ่มตอนท้าย','/ˈɒŋkɔː(r)/','👏'),('soloist','ผู้แสดงเดี่ยว','/ˈsəʊləʊɪst/','🌟')],
  "Good typography is invisible until it is bad. A clean layout leaves room for the reader to breathe. One clear illustration replaces a page of words. Show your rough mockup early, not late. Learn the rules well enough to improvise inside them. Forty people came to the audition for six parts. The crowd would not leave without an encore. Every soloist began in the back row.",
  ["Good typography is invisible until it is bad.",
   "A clean layout leaves room for the reader to breathe.",
   "One clear illustration replaces a page of words.",
   "Show your rough mockup early, not late.",
   "Every soloist began in the back row."],
  ["A clean layout leaves room for the reader to breathe.",
   "Show your rough mockup early, not late.",
   "Every soloist began in the back row."],
  "Where did every soloist begin?","Every soloist began in the back row."),

D(290,289,'Making Music Together','🎼','Day291_Week43Review_B1.html','⭐','tiles',
  'Relative clauses without which: the song we sang last night.',
  [('harmony','เสียงประสาน','/ˈhɑːməni/','🎶'),('tempo','จังหวะความเร็ว','/ˈtempəʊ/','🥁'),
   ('chord','คอร์ดดนตรี','/kɔːd/','🎸'),('lyric','เนื้อเพลง','/ˈlɪrɪk/','📃'),
   ('composer','ผู้ประพันธ์เพลง','/kəmˈpəʊzə(r)/','🖊️'),('conductor','วาทยกร','/kənˈdʌktə(r)/','🪄'),
   ('orchestra','วงออร์เคสตรา','/ˈɔːkɪstrə/','🎻'),('choir','คณะนักร้องประสานเสียง','/ˈkwaɪə(r)/','👨‍👩‍👧')],
  "Harmony is what happens when nobody sings louder than everyone. The tempo must be agreed before the first note. Three chords are enough for a thousand songs. A simple lyric said honestly beats a clever one. A composer hears the piece long before anyone plays it. The conductor makes no sound at all. An orchestra is sixty people breathing together. Our school choir sings every Friday afternoon.",
  ["Harmony is what happens when nobody sings louder than everyone.",
   "The tempo must be agreed before the first note.",
   "Three chords are enough for a thousand songs.",
   "The conductor makes no sound at all.",
   "An orchestra is sixty people breathing together."],
  ["The tempo must be agreed before the first note.",
   "The conductor makes no sound at all.",
   "An orchestra is sixty people breathing together."],
  "Who makes no sound at all?","The conductor makes no sound."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn)
