# -*- coding: utf-8 -*-
# Level 8 · B1 · Week 36 Inclusion & Community (232–238) + 239–240 จบ Level 8
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level8/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta, theme='Community'):
    return dict(n=n, prev=prev, level=8, cefr='B1', title=title, emoji=emoji, theme=theme,
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(232,231,'Everyone Belongs','🫂','Day233_ADoorForAll_B1.html','♿','tiles',
  'Inclusive language: people with disabilities, rather than "the disabled".',
  [('inclusion','การอยู่ร่วมกัน','/ɪnˈkluːʒn/','🫂'),('diversity','ความหลากหลาย','/daɪˈvɜːsəti/','🌈'),
   ('belong','เป็นส่วนหนึ่ง','/bɪˈlɒŋ/','🧩'),('prejudice','อคติ','/ˈpredʒudɪs/','🚷'),
   ('stereotype','ภาพเหมารวม','/ˈsteriətaɪp/','🏷️'),('tolerance','ความอดกลั้น','/ˈtɒlərəns/','🕊️'),
   ('hospitality','การต้อนรับ','/ˌhɒspɪˈtæləti/','🚪'),('atmosphere','บรรยากาศ','/ˈætməsfɪə(r)/','🏫')],
  "Inclusion means nobody is left standing outside. Diversity makes a classroom far more interesting. Everyone should feel that they belong. Old prejudice usually comes from not knowing someone. A stereotype hides the real person behind it. Tolerance is the first step, but respect is the goal. Simple hospitality can change the whole atmosphere of a school.",
  ["Inclusion means nobody is left standing outside.",
   "Diversity makes a classroom far more interesting.",
   "Everyone should feel that they belong.",
   "A stereotype hides the real person behind it.",
   "Simple hospitality can change the whole atmosphere of a school."],
  ["Diversity makes a classroom far more interesting.",
   "A stereotype hides the real person behind it.",
   "Simple hospitality can change the whole atmosphere of a school."],
  "Where does old prejudice usually come from?","It comes from not knowing someone."),

D(233,232,'A Door for All','♿','Day234_HelpingNeighbours_B1.html','🏘️','scramble',
  'Purpose with so that: ramps are built so that everyone can enter.',
  [('accessible','เข้าถึงได้','/əkˈsesəbl/','🚪'),('ramp','ทางลาด','/ræmp/','📐'),
   ('wheelchair','รถเข็น','/ˈwiːltʃeə(r)/','♿'),('braille','อักษรเบรลล์','/breɪl/','⠿'),
   ('gesture','ท่าทางสื่อสาร','/ˈdʒestʃə(r)/','🤟'),('adjust','ปรับเปลี่ยน','/əˈdʒʌst/','🔧'),
   ('independent','พึ่งตนเองได้','/ˌɪndɪˈpendənt/','🦾'),('universal','ใช้ได้กับทุกคน','/ˌjuːnɪˈvɜːsl/','🧠')],
  "A truly accessible building works for every visitor. A gentle ramp is built so that everyone can enter. A person in a wheelchair should never need to ask for help. Braille labels appear beside each lift button. Some staff are learning hand gesture language this term. Small changes adjust a building at very low cost. Universal design keeps people independent.",
  ["A truly accessible building works for every visitor.",
   "A gentle ramp is built so that everyone can enter.",
   "Braille labels appear beside each lift button.",
   "Some staff are learning hand gesture language this term.",
   "Universal design keeps people independent."],
  ["A gentle ramp is built so that everyone can enter.",
   "Some staff are learning hand gesture language this term.",
   "Universal design keeps people independent."],
  "Why is a gentle ramp built?","So that everyone can enter."),

D(234,233,'Helping Neighbours','🏘️','Day235_NewInTown_B1.html','🧳','memory',
  'Offers and requests: Would you mind if...? / I would be glad to...',
  [('volunteering','การเป็นอาสาสมัคร','/ˌvɒlənˈtɪərɪŋ/','🙋'),('mentorship','การเป็นพี่เลี้ยง','/ˈmentɔːʃɪp/','🧑‍🏫'),
   ('refuge','ที่พักพิง','/ˈrefjuːdʒ/','🏠'),('donation','สิ่งของบริจาค','/dəʊˈneɪʃn/','📦'),
   ('homeless','ไร้ที่อยู่','/ˈhəʊmləs/','🛏️'),('outreach','การออกช่วยเหลือ','/ˈaʊtriːtʃ/','🍲'),
   ('compassion','ความเมตตา','/kəmˈpæʃn/','💌'),('ongoing','ต่อเนื่อง','/ˈɒnɡəʊɪŋ/','🔁')],
  "Volunteering costs time, not money. Mimi joined a mentorship programme for younger pupils. Their class collects warm clothes for a refuge. Any donation you no longer use will help. A homeless person is someone with a story, not a statistic. Every Sunday the group joins an outreach at the centre. Compassion reminded them why the work is ongoing.",
  ["Volunteering costs time, not money.",
   "Mimi joined a mentorship programme for younger pupils.",
   "Any donation you no longer use will help.",
   "A homeless person is someone with a story.",
   "Compassion reminded them why the work is ongoing."],
  ["Mimi joined a mentorship programme for younger pupils.",
   "A homeless person is someone with a story.",
   "Compassion reminded them why the work is ongoing."],
  "What does volunteering cost?","It costs time, not money."),

D(235,234,'New in Town','🧳','Day236_SpeakingUp_B1.html','📢','wordsearch',
  'Empathy phrases: I can imagine that / it must be difficult to...',
  [('refugee','ผู้ลี้ภัย','/ˌrefjuˈdʒiː/','🧳'),('resettle','ตั้งถิ่นฐานใหม่','/ˌriːˈsetl/','🏡'),
   ('barrier','อุปสรรค','/ˈbæriə(r)/','🚧'),('paperwork','เอกสารราชการ','/ˈpeɪpəwɜːk/','📄'),
   ('homesick','คิดถึงบ้าน','/ˈhəʊmsɪk/','🥺'),('integrate','ปรับตัวเข้ากับสังคม','/ˈɪntɪɡreɪt/','🔗'),
   ('translator','ล่ามแปลภาษา','/trænzˈleɪtə(r)/','🗣️'),('perseverance','ความอดทนมุ่งมั่น','/ˌpɜːsɪˈvɪərəns/','⏳')],
  "A refugee family moved into the flat downstairs. It must be difficult to resettle in one week. A language barrier makes every small task slow. Endless paperwork waits at each office. Their youngest boy felt homesick for months. School helped him integrate through football. A kind translator came twice a week. Perseverance matters more than perfect words.",
  ["A refugee family moved into the flat downstairs.",
   "A language barrier makes every small task slow.",
   "Their youngest boy felt homesick for months.",
   "School helped him integrate through football.",
   "Perseverance matters more than perfect words."],
  ["A language barrier makes every small task slow.",
   "School helped him integrate through football.",
   "Perseverance matters more than perfect words."],
  "How did school help the boy integrate?","It helped him through football."),

D(236,235,'Speaking Up','📢','Day237_SmallActsBigChange_B1.html','✨','vowels',
  'Reported requests: She asked us to stop. He told them not to shout.',
  [('bully','กลั่นแกล้ง','/ˈbʊli/','😠'),('bystander','ผู้เห็นเหตุการณ์','/ˈbaɪstændə(r)/','👀'),
   ('intervene','เข้าไปห้าม','/ˌɪntəˈviːn/','✋'),('inform','แจ้งให้ทราบ','/ɪnˈfɔːm/','📮'),
   ('victim','ผู้ถูกกระทำ','/ˈvɪktɪm/','🩹'),('accountability','ความรับผิดชอบ','/əˌkaʊntəˈbɪləti/','⚖️'),
   ('courageous','กล้าหาญ','/kəˈreɪdʒəs/','🦁'),('solidarity','ความเป็นน้ำหนึ่งใจเดียว','/ˌsɒlɪˈdærəti/','🛡️')],
  "Nobody has the right to bully another student. A silent bystander lets the problem continue. You do not have to fight in order to intervene. Inform a teacher you trust. The victim often feels alone and ashamed. Accountability follows every action, good or bad. Speaking up is courageous and builds real solidarity.",
  ["Nobody has the right to bully another student.",
   "A silent bystander lets the problem continue.",
   "You do not have to fight in order to intervene.",
   "The victim often feels alone and ashamed.",
   "Speaking up is courageous and builds solidarity."],
  ["A silent bystander lets the problem continue.",
   "The victim often feels alone and ashamed.",
   "Speaking up is courageous and builds solidarity."],
  "What does a silent bystander do?","A silent bystander lets the problem continue."),

D(237,236,'Small Acts, Big Change','✨','Day238_Week36Review_B1.html','⭐','tiles',
  'Cause and result: which means that / and therefore.',
  [('seedling','ต้นกล้า','/ˈsiːdlɪŋ/','🌱'),('ripple','ผลกระทบต่อเนื่อง','/ˈrɪpl/','💫'),
   ('ethos','ค่านิยมร่วม','/ˈiːθɒs/','🔥'),('multiply','ทวีคูณ','/ˈmʌltɪplaɪ/','✖️'),
   ('sustain','รักษาไว้ต่อเนื่อง','/səˈsteɪn/','🔋'),('evaluate','ประเมินผล','/ɪˈvæljueɪt/','📊'),
   ('legacy','มรดกที่ทิ้งไว้','/ˈleɡəsi/','🏛️'),('humility','ความถ่อมตน','/hjuːˈmɪləti/','🌰')],
  "One small idea can create a long ripple. Their tree project began with ten seedling plants. A shared ethos spreads with quiet humility, not speeches. When five schools joined, the effect began to multiply. It is harder to sustain a project than to begin one. Try to evaluate the result honestly each term. A real legacy is what keeps growing after you leave.",
  ["One small idea can create a long ripple.",
   "Their tree project began with ten seedlings.",
   "When five schools joined, the effect began to multiply.",
   "It is harder to sustain a project than to begin one.",
   "A real legacy keeps growing after you leave."],
  ["Their tree project began with ten seedlings.",
   "It is harder to sustain a project than to begin one.",
   "A real legacy keeps growing after you leave."],
  "What is harder than beginning a project?","It is harder to sustain it."),

D(239,238,'Two Hundred Forty','🎯','Day240_HalfwayThere_B1.html','🏁','scramble',
  'Reviewing: mix all tenses in one short paragraph about your progress.',
  [('halfway','ครึ่งทาง','/ˌhɑːfˈweɪ/','🏁'),('sustained','ต่อเนื่องยาวนาน','/səˈsteɪnd/','📶'),
   ('vocabulary','คลังคำศัพท์','/vəˈkæbjələri/','📚'),('comprehension','ความเข้าใจ','/ˌkɒmprɪˈhenʃn/','🧠'),
   ('accuracy','ความถูกต้อง','/ˈækjərəsi/','🎯'),('spontaneous','เป็นธรรมชาติทันที','/spɒnˈteɪniəs/','💬'),
   ('plateau','ช่วงที่ไม่ก้าวหน้า','/ˈplætəʊ/','➖'),('persistence','ความพากเพียร','/pəˈsɪstəns/','🔥')],
  "You are almost halfway through the whole course. Sustained effort has built a real vocabulary. Your listening comprehension is much faster now. Accuracy improves slowly, then suddenly. Soon your speech will feel more spontaneous. Everyone meets a plateau where nothing seems to improve. Persistence is what carries you past it.",
  ["You are almost halfway through the whole course.",
   "Sustained effort has built a real vocabulary.",
   "Your listening comprehension is much faster now.",
   "Everyone meets a plateau where nothing seems to improve.",
   "Persistence is what carries you past it."],
  ["Sustained effort has built a real vocabulary.",
   "Everyone meets a plateau where nothing seems to improve.",
   "Persistence is what carries you past it."],
  "What carries you past a plateau?","Persistence carries you past it.", 'Special'),

D(240,239,'Halfway There','🏁','../dashboard.html','🏠','memory',
  'Setting a target: By Day 300 I want to be able to...',
  [('remainder','ส่วนที่เหลือ','/rɪˈmeɪndə(r)/','🛣️'),('commitment','ความมุ่งมั่นผูกพัน','/kəˈmɪtmənt/','🤝'),
   ('regularity','ความสม่ำเสมอ','/ˌreɡjuˈlærəti/','⏰'),('measurable','วัดผลได้','/ˈmeʒərəbl/','📏'),
   ('incentive','สิ่งจูงใจ','/ɪnˈsentɪv/','🎁'),('integrity','ความซื่อตรง','/ɪnˈteɡrəti/','📌'),
   ('anticipate','คาดหวังล่วงหน้า','/ænˈtɪsɪpeɪt/','🎉'),('unstoppable','หยุดไม่อยู่','/ʌnˈstɒpəbl/','🚀')],
  "Two hundred and forty days is a serious commitment. The remainder of the road is exactly as long as the part behind. Keep the same regularity and it will carry you. Set one measurable target for the next hundred days. Give yourself a small incentive at Day 300. Integrity means working even when nobody is watching. Anticipate the next hundred days: you are unstoppable.",
  ["Two hundred and forty days is a serious commitment.",
   "The remainder is as long as the part behind.",
   "Set one measurable target for the next hundred days.",
   "Integrity means working when nobody is watching.",
   "Anticipate the next hundred days."],
  ["The remainder is as long as the part behind.",
   "Integrity means working when nobody is watching.",
   "Anticipate the next hundred days."],
  "What should you set for the next hundred days?","One measurable target.", 'Special'),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']),'คำ')
