# -*- coding: utf-8 -*-
# Level 10 · B1 · Week 42 Sport & Fitness (Day 278–283)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level10/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=10, cefr='B1', title=title, emoji=emoji, theme='Sport',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(278,277,'The Games We Play','⚽','Day279_RulesandReferees_B1.html','📏','tiles',
  'Present continuous for arrangements: We are playing them on Sunday.',
  [('league','ลีกการแข่งขัน','/liːɡ/','🏟️'),('squad','ทีมผู้เล่นทั้งหมด','/skwɒd/','👥'),
   ('fixture','โปรแกรมแข่ง','/ˈfɪkstʃə(r)/','🗓️'),('kickoff','การเริ่มเกม','/ˈkɪkɒf/','⏱️'),
   ('halftime','พักครึ่งเวลา','/ˌhɑːfˈtaɪm/','⏸️'),('whistle','นกหวีด','/ˈwɪsl/','📣'),
   ('jersey','เสื้อแข่ง','/ˈdʒɜːzi/','👕'),('formation','การจัดตำแหน่งผู้เล่น','/fɔːˈmeɪʃn/','🔷')],
  "Our school joined the city league last year. The squad has eighteen players but only eleven start. The next fixture is on Sunday morning. Kickoff is at nine, so be there at eight. At halftime the coach changed everything. One whistle stops the whole game. Each jersey carries a number and a name. A good formation hides a team's weakest side.",
  ["Our school joined the city league last year.",
   "The next fixture is on Sunday morning.",
   "Kickoff is at nine, so be there at eight.",
   "One whistle stops the whole game.",
   "Each jersey carries a number and a name."],
  ["The next fixture is on Sunday morning.",
   "One whistle stops the whole game.",
   "Each jersey carries a number and a name."],
  "What time is kickoff?","Kickoff is at nine."),

D(279,278,'Rules and Referees','📏','Day280_TrackandField_B1.html','🏃','scramble',
  'Third conditional: If he had passed, we would have scored.',
  [('umpire','ผู้ตัดสิน','/ˈʌmpaɪə(r)/','🧑‍⚖️'),('penalty','การลงโทษในเกม','/ˈpenəlti/','🥅'),
   ('foul','การทำฟาวล์','/faʊl/','🚩'),('offside','ล้ำหน้า','/ˌɒfˈsaɪd/','🚧'),
   ('substitute','ผู้เล่นสำรอง','/ˈsʌbstɪtjuːt/','🔄'),('dribble','เลี้ยงลูก','/ˈdrɪbl/','⚽'),
   ('scoreboard','กระดานคะแนน','/ˈskɔːbɔːd/','🔢'),('replay','ภาพย้อนหลัง','/ˈriːpleɪ/','📹')],
  "The umpire is never popular for very long. A penalty is given only inside the box. That foul was clumsy rather than cruel. The goal did not count because he was offside. Our best substitute changed the game in ten minutes. He can dribble past three players without looking up. The scoreboard said two all with a minute left. The replay showed the ball had crossed the line.",
  ["The umpire is never popular for very long.",
   "That foul was clumsy rather than cruel.",
   "The goal did not count because he was offside.",
   "He can dribble past three players without looking up.",
   "The scoreboard said two all with a minute left."],
  ["That foul was clumsy rather than cruel.",
   "He can dribble past three players without looking up.",
   "The scoreboard said two all with a minute left."],
  "Why did the goal not count?","Because he was offside."),

D(280,279,'Track and Field','🏃','Day281_OtherSportsOtherSkills_B1.html','🤼','memory',
  'Superlatives with ever: the fastest race I have ever seen.',
  [('sprint','วิ่งระยะสั้น','/sprɪnt/','💨'),('marathon','วิ่งมาราธอน','/ˈmærəθən/','🛣️'),
   ('relay','วิ่งผลัด','/ˈriːleɪ/','🤝'),('hurdle','รั้วกระโดดข้าม','/ˈhɜːdl/','🚏'),
   ('javelin','พุ่งแหลน','/ˈdʒævlɪn/','🎯'),('archery','ยิงธนู','/ˈɑːtʃəri/','🏹'),
   ('gymnastics','ยิมนาสติก','/dʒɪmˈnæstɪks/','🤸'),('podium','แท่นรับรางวัล','/ˈpəʊdiəm/','🥇')],
  "A sprint is over before the crowd stops shouting. A marathon is won in the mind, not the legs. In a relay the handover matters more than the running. Clip one hurdle and your rhythm is gone. The javelin flew further than anyone expected. Archery looks calm and is not. Gymnastics asks for strength and grace at the same second. Only three athletes fit on the podium.",
  ["A sprint is over before the crowd stops shouting.",
   "A marathon is won in the mind, not the legs.",
   "In a relay the handover matters more than the running.",
   "The javelin flew further than anyone expected.",
   "Only three athletes fit on the podium."],
  ["A marathon is won in the mind, not the legs.",
   "The javelin flew further than anyone expected.",
   "Only three athletes fit on the podium."],
  "Where is a marathon won?","It is won in the mind, not the legs."),

D(281,280,'Other Sports, Other Skills','🤼','Day282_TrainandRecover_B1.html','💪','wordsearch',
  'Comparing activities: unlike / whereas / on the other hand.',
  [('wrestling','มวยปล้ำ','/ˈreslɪŋ/','🤼'),('fencing','ฟันดาบ','/ˈfensɪŋ/','🤺'),
   ('paddle','ไม้พาย','/ˈpædl/','🛶'),('racquet','ไม้แร็กเกต','/ˈrækɪt/','🎾'),
   ('goggles','แว่นตากันน้ำ','/ˈɡɒɡlz/','🥽'),('agility','ความคล่องแคล่ว','/əˈdʒɪləti/','🐆'),
   ('flexibility','ความยืดหยุ่นของร่างกาย','/ˌfleksəˈbɪləti/','🧘'),('aerobic','แบบใช้ออกซิเจน','/eəˈrəʊbɪk/','🫁')],
  "Wrestling is chess played with the whole body. In fencing the fastest hand is not always the winner. Hold the paddle loosely or your arms will ache. A heavy racquet is slower but hits harder. Swimmers wear goggles to see the wall coming. Agility is turning quickly without falling over. Flexibility is trained slowly and lost fast. Any aerobic sport makes your heart stronger.",
  ["Wrestling is chess played with the whole body.",
   "Hold the paddle loosely or your arms will ache.",
   "Swimmers wear goggles to see the wall coming.",
   "Agility is turning quickly without falling over.",
   "Any aerobic sport makes your heart stronger."],
  ["Hold the paddle loosely or your arms will ache.",
   "Agility is turning quickly without falling over.",
   "Any aerobic sport makes your heart stronger."],
  "Why do swimmers wear goggles?","To see the wall coming."),

D(282,281,'Train and Recover','💪','Day283_TheBigFinal_B1.html','🏆','vowels',
  'Warnings and advice: unless you / otherwise you will.',
  [('warmup','การอบอุ่นร่างกาย','/ˈwɔːmʌp/','🔥'),('sweat','เหงื่อ','/swet/','💦'),
   ('joint','ข้อต่อ','/dʒɔɪnt/','🦴'),('injury','อาการบาดเจ็บ','/ˈɪndʒəri/','🚑'),
   ('sprain','ข้อเท้าแพลง','/spreɪn/','🦶'),('bruise','รอยฟกช้ำ','/bruːz/','🟣'),
   ('physiotherapy','กายภาพบำบัด','/ˌfɪziəʊˈθerəpi/','🧑‍⚕️'),('rehabilitation','การฟื้นฟูร่างกาย','/ˌriːəˌbɪlɪˈteɪʃn/','📈')],
  "Never skip the warmup, however late you are. Sweat is not a measure of a good session. Every joint needs rest as much as work. One careless injury costs a whole season. A sprain heals faster when you stop using it. A bruise looks worse than it is. Six weeks of physiotherapy is not wasted time. Rehabilitation is training too, only quieter.",
  ["Never skip the warmup, however late you are.",
   "Sweat is not a measure of a good session.",
   "One careless injury costs a whole season.",
   "A sprain heals faster when you stop using it.",
   "Rehabilitation is training too, only quieter."],
  ["Sweat is not a measure of a good session.",
   "A sprain heals faster when you stop using it.",
   "Rehabilitation is training too, only quieter."],
  "What does one careless injury cost?","It costs a whole season."),

D(283,282,'The Big Final','🏆','Day284_Week42Review_B1.html','⭐','tiles',
  'Narrative tenses: had been leading when the whistle went.',
  [('qualifier','รอบคัดเลือก','/ˈkwɒlɪfaɪə(r)/','🎫'),('semifinal','รอบรองชนะเลิศ','/ˌsemiˈfaɪnl/','🥈'),
   ('underdog','ทีมรอง','/ˈʌndədɒɡ/','🐕'),('rivalry','การเป็นคู่แข่งกัน','/ˈraɪvlri/','⚔️'),
   ('comeback','การกลับมาชนะ','/ˈkʌmbæk/','🔙'),('sponsor','ผู้สนับสนุน','/ˈspɒnsə(r)/','💼'),
   ('trophy','ถ้วยรางวัล','/ˈtrəʊfi/','🏆'),('champion','แชมป์','/ˈtʃæmpiən/','👑')],
  "They almost lost the qualifier in September. The semifinal went to the last kick. Everyone loves an underdog until it beats their team. This rivalry is older than anyone in the crowd. Their comeback took twelve minutes and one substitution. A local sponsor paid for the new kit. The trophy is smaller than it looks on television. A champion is simply someone who kept turning up.",
  ["They almost lost the qualifier in September.",
   "The semifinal went to the last kick.",
   "This rivalry is older than anyone in the crowd.",
   "A local sponsor paid for the new kit.",
   "A champion is simply someone who kept turning up."],
  ["The semifinal went to the last kick.",
   "A local sponsor paid for the new kit.",
   "A champion is simply someone who kept turning up."],
  "What is a champion?","Someone who kept turning up."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn)
