# -*- coding: utf-8 -*-
# Level 8 · B1 · Week 33 History (211–217) · Week 34 Traditions (218–224)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level8/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta, theme='History'):
    return dict(n=n, prev=prev, level=8, cefr='B1', title=title, emoji=emoji, theme=theme,
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(211,210,'Long Ago','🏛️','Day212_DiggingThePast_B1.html','⛏️','tiles',
  'Time markers for the past: in the 14th century, during the war, around 1900.',
  [('century','ศตวรรษ','/ˈsentʃəri/','💯'),('decade','ทศวรรษ','/ˈdekeɪd/','🔟'),
   ('era','ยุคสมัย','/ˈɪərə/','⏳'),('empire','จักรวรรดิ','/ˈempaɪə(r)/','👑'),
   ('kingdom','อาณาจักร','/ˈkɪŋdəm/','🏯'),('dynasty','ราชวงศ์','/ˈdɪnəsti/','🧬'),
   ('timeline','เส้นเวลา','/ˈtaɪmlaɪn/','📏'),('modern','สมัยใหม่','/ˈmɒdn/','🏙️')],
  "In the fourteenth century this land was a powerful kingdom. An empire can last for many decade or fall in one year. Each era leaves something behind for us to find. One royal dynasty ruled for more than two hundred years. The class drew a long timeline on the wall. Modern life looks very different from that world. Yet many customs have survived until today.",
  ["In the fourteenth century this land was a powerful kingdom.",
   "An empire can last for many decade or fall in one year.",
   "Each era leaves something behind for us to find.",
   "The class drew a long timeline on the wall.",
   "Modern life looks very different from that world."],
  ["Each era leaves something behind for us to find.",
   "The class drew a long timeline on the wall.",
   "Modern life looks very different from that world."],
  "How long did the royal dynasty rule?","It ruled for more than two hundred years."),

D(212,211,'Digging the Past','⛏️','Day213_LessonsFromHistory_B1.html','📜','scramble',
  'Passive in the past: The pot was buried. The city was destroyed.',
  [('archaeology','โบราณคดี','/ˌɑːkiˈɒlədʒi/','🔬'),('artefact','โบราณวัตถุ','/ˈɑːtɪfækt/','🏺'),
   ('excavate','ขุดค้น','/ˈekskəveɪt/','⛏️'),('ruins','ซากปรักหักพัง','/ˈruːɪnz/','🏚️'),
   ('civilisation','อารยธรรม','/ˌsɪvəlaɪˈzeɪʃn/','🏛️'),('buried','ถูกฝัง','/ˈberid/','⚰️'),
   ('fragile','เปราะบาง','/ˈfrædʒaɪl/','🫙'),('reveal','เปิดเผย','/rɪˈviːl/','🔦')],
  "Archaeology is the science of studying old things. Last year a team came to excavate a field near the river. Every artefact was carefully cleaned and numbered. The ruins had been buried under two metres of soil. A fragile clay pot can break in one second. The find helped reveal how that civilisation ate and worked. History is a puzzle with missing pieces.",
  ["Archaeology is the science of studying old things.",
   "A team came to excavate a field near the river.",
   "The ruins had been buried under two metres of soil.",
   "A fragile clay pot can break in one second.",
   "History is a puzzle with missing pieces."],
  ["A team came to excavate a field near the river.",
   "A fragile clay pot can break in one second.",
   "History is a puzzle with missing pieces."],
  "What was buried under the soil?","The ruins were buried under two metres of soil."),

D(213,212,'Lessons from History','📜','Day214_FestivalTime_B1.html','🎊','memory',
  'Third conditional: If they had listened, the city would have survived.',
  [('conquer','พิชิต','/ˈkɒŋkə(r)/','⚔️'),('revolution','การปฏิวัติ','/ˌrevəˈluːʃn/','✊'),
   ('monument','อนุสาวรีย์','/ˈmɒnjumənt/','🗿'),('interpret','ตีความ','/ɪnˈtɜːprɪt/','🔍'),
   ('bias','ความลำเอียง','/ˈbaɪəs/','🎭'),('narrative','เรื่องเล่าประวัติศาสตร์','/ˈnærətɪv/','📖'),
   ('repeat','ทำซ้ำ','/rɪˈpiːt/','🔁'),('gradual','ค่อยเป็นค่อยไป','/ˈɡrædʒuəl/','🐢')],
  "Armies used to conquer land to gain power. A revolution changes a country very quickly. A stone monument reminds people what happened. Two historians may interpret the same letter differently. Every account carries some bias. If we ignore the old narrative, we repeat the same mistakes. Real change is gradual but it never stops completely.",
  ["Armies used to conquer land to gain power.",
   "A revolution changes a country very quickly.",
   "A stone monument reminds people what happened.",
   "Two historians may interpret the same letter differently.",
   "Real change is gradual but it never stops."],
  ["A revolution changes a country very quickly.",
   "Two historians may interpret the same letter differently.",
   "Real change is gradual but it never stops."],
  "What does a stone monument do?","It reminds people what happened."),

D(214,213,'Festival Time','🎊','Day215_FamilyTraditions_B1.html','🏮','wordsearch',
  'Describing routines in the past: every year we would gather...',
  [('parade','ขบวนแห่','/pəˈreɪd/','🥁'),('lantern','โคมไฟ','/ˈlæntən/','🏮'),
   ('offering','เครื่องบูชา','/ˈɒfərɪŋ/','🍚'),('ritual','พิธีกรรม','/ˈrɪtʃuəl/','🕯️'),
   ('attire','เครื่องแต่งกาย','/əˈtaɪə(r)/','👘'),('procession','ขบวน','/prəˈseʃn/','🚛'),
   ('firework','พลุ','/ˈfaɪəwɜːk/','🎆'),('assemble','มาชุมนุมกัน','/əˈsembl/','👥')],
  "Every November the whole town holds a parade. Children carry a paper lantern down the main road. Families assemble and place an offering at the small shrine. This ritual is older than anyone can remember. Mimi wore bright traditional attire made by her aunt. A long procession moved slowly down the street. At midnight one firework lit the whole sky.",
  ["Every November the whole town holds a parade.",
   "Children carry a paper lantern down the main road.",
   "Families assemble and place an offering at the small shrine.",
   "This ritual is older than anyone can remember.",
   "At midnight one firework lit the whole sky."],
  ["Children carry a paper lantern down the main road.",
   "This ritual is older than anyone can remember.",
   "At midnight one firework lit the whole sky."],
  "What do children carry in the parade?","They carry a paper lantern."),

D(215,214,'Family Traditions','🏮','Day216_SportsDay_B1.html','🏃','vowels',
  'Expressing habit in the past: used to + verb / would + verb.',
  [('ancestry','บรรพชน','/ˈænsestri/','👴'),('inherit','สืบทอด','/ɪnˈherɪt/','🎁'),
   ('heirloom','ของตกทอด','/ˈeəluːm/','🍲'),('gathering','การรวมตัว','/ˈɡæðərɪŋ/','🏠'),
   ('devotion','ความเคารพรัก','/dɪˈvəʊʃn/','🙏'),('storytelling','การเล่าเรื่อง','/ˈstɔːritelɪŋ/','📚'),
   ('keepsake','ของที่เก็บไว้','/ˈkiːpseɪk/','📿'),('meaningful','มีความหมาย','/ˈmiːnɪŋfl/','💗')],
  "Our ancestry adds something new to the family story. Mimi will inherit her grandmother's silver ring. The soup heirloom recipe has never been written down. Every April there is a big gathering at the old house. Devotion to family greets every older relative. Grandpa is famous for his long storytelling. A simple keepsake can be more meaningful than money.",
  ["Our ancestry adds something to the family story.",
   "Mimi will inherit her grandmother's silver ring.",
   "Every April there is a big gathering at the old house.",
   "Grandpa is famous for his long storytelling.",
   "A simple keepsake can be meaningful."],
  ["Mimi will inherit her grandmother's silver ring.",
   "Grandpa is famous for his long storytelling.",
   "A simple keepsake can be meaningful."],
  "What will Mimi inherit?","She will inherit her grandmother's silver ring."),

D(216,215,'Sports Day','🏃','Day217_Week33Review_B1.html','⭐','tiles',
  'Superlatives + present perfect: the fastest time we have ever seen.',
  [('athlete','นักกีฬา','/ˈæθliːt/','🏅'),('tournament','การแข่งขัน','/ˈtʊənəmənt/','🏆'),
   ('opponent','คู่แข่ง','/əˈpəʊnənt/','🤺'),('tactic','กลยุทธ์','/ˈtæktɪk/','♟️'),
   ('endurance','ความอดทน','/ɪnˈdjʊərəns/','🔋'),('spectator','ผู้ชมการแข่ง','/spekˈteɪtə(r)/','📣'),
   ('stadium','สนามกีฬา','/ˈsteɪdiəm/','🏟️'),('sportsmanship','น้ำใจนักกีฬา','/ˈspɔːtsmənʃɪp/','🤝')],
  "Every athlete trained hard for the school tournament. Leo studied the tactic of his opponent. Long races need endurance more than speed. The stadium was full of noisy spectator. Ben ran the fastest time we have ever seen. He shook hands after losing the final match. Good sportsmanship is remembered longer than a score.",
  ["Every athlete trained hard for the school tournament.",
   "Leo studied the tactic of his opponent.",
   "Long races need endurance more than speed.",
   "Ben ran the fastest time we have ever seen.",
   "Good sportsmanship is remembered longer than a score."],
  ["Leo studied the tactic of his opponent.",
   "Ben ran the fastest time we have ever seen.",
   "Good sportsmanship is remembered longer than a score."],
  "What do long races need?","They need endurance more than speed."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']),'คำ')
