# -*- coding: utf-8 -*-
# Level 12 · B2 · Week 49 Science: Matter, Energy & Life (Day 331–336) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level12/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=12, cefr='B2', title=title, emoji=emoji, theme='Science',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(331,330,'What Everything Is Made Of','⚛️','Day332_ChangingStates_B2.html','💨','tiles',
  'Scientific definition: is defined as / consists of / is composed of.',
  [('atom','อะตอม','/ˈætəm/','⚛️'),('molecule','โมเลกุล','/ˈmɒlɪkjuːl/','🔗'),
   ('nucleus','นิวเคลียส','/ˈnjuːkliəs/','🎯'),('proton','โปรตอน','/ˈprəʊtɒn/','➕'),
   ('neutron','นิวตรอน','/ˈnjuːtrɒn/','⚪'),('electron','อิเล็กตรอน','/ɪˈlektrɒn/','➖'),
   ('isotope','ไอโซโทป','/ˈaɪsətəʊp/','🧬'),('particle','อนุภาค','/ˈpɑːtɪkl/','🔵'),
   ('density','ความหนาแน่น','/ˈdensəti/','🧱')],
  "An atom is mostly empty space, which is difficult to believe. Two or more atoms joined together form a molecule. The nucleus holds almost all the mass in a very small place. A proton carries a positive charge and never leaves. A neutron carries no charge and keeps the nucleus stable. An electron is light, fast and impossible to pin down exactly. An isotope is the same element with a different number of neutrons. Every particle behaves like a wave when it is small enough. Density explains why iron sinks and wood floats.",
  ["An atom is mostly empty space, which is difficult to believe.",
   "Two or more atoms joined together form a molecule.",
   "The nucleus holds almost all the mass in a very small place.",
   "An electron is light, fast and impossible to pin down exactly.",
   "Density explains why iron sinks and wood floats."],
  ["Two or more atoms joined together form a molecule.",
   "The nucleus holds almost all the mass in a very small place.",
   "Density explains why iron sinks and wood floats."],
  "What does density explain?","It explains why iron sinks and wood floats."),

D(332,331,'Changing States','💨','Day333_ForcesandMotion_B2.html','🚀','scramble',
  'Conditions in science: when heated / once cooled / provided that.',
  [('dissolve','ละลาย','/dɪˈzɒlv/','🥄'),('solvent','ตัวทำละลาย','/ˈsɒlvənt/','🧴'),
   ('evaporate','ระเหย','/ɪˈvæpəreɪt/','☁️'),('condense','ควบแน่น','/kənˈdens/','💧'),
   ('crystallise','ตกผลึก','/ˈkrɪstəlaɪz/','❄️'),('catalyst','ตัวเร่งปฏิกิริยา','/ˈkætəlɪst/','🏎️'),
   ('acid','กรด','/ˈæsɪd/','🍋'),('alkaline','ด่าง','/ˈælkəlaɪn/','🧼'),
   ('oxidise','ทำปฏิกิริยากับออกซิเจน','/ˈɒksɪdaɪz/','🟠')],
  "Salt will dissolve in water but not in oil. Water is called the universal solvent for a good reason. Puddles evaporate faster on a windy day than on a hot still one. Warm air will condense on a cold window and leave drops. Sugar syrup left alone will slowly crystallise. A catalyst speeds up a reaction without being used up. An acid tastes sour and turns litmus paper red. An alkaline solution feels slippery and is often worse to touch. Iron left in wet air will oxidise into rust.",
  ["Salt will dissolve in water but not in oil.",
   "Puddles evaporate faster on a windy day.",
   "Warm air will condense on a cold window and leave drops.",
   "A catalyst speeds up a reaction without being used up.",
   "Iron left in wet air will oxidise into rust."],
  ["Salt will dissolve in water but not in oil.",
   "A catalyst speeds up a reaction without being used up.",
   "Iron left in wet air will oxidise into rust."],
  "What does a catalyst do?","It speeds up a reaction without being used up."),

D(333,332,'Forces and Motion','🚀','Day334_LightSoundandWaves_B2.html','🌈','memory',
  'Stating laws: the greater the mass, the greater the force required.',
  [('friction','แรงเสียดทาน','/ˈfrɪkʃn/','🛞'),('inertia','ความเฉื่อย','/ɪˈnɜːʃə/','🪨'),
   ('velocity','ความเร็วเชิงเวกเตอร์','/vəˈlɒsəti/','🏹'),('acceleration','ความเร่ง','/əkˌseləˈreɪʃn/','📈'),
   ('kinetic','เกี่ยวกับพลังงานจลน์','/kɪˈnetɪk/','🏃'),('thermal','เกี่ยวกับความร้อน','/ˈθɜːml/','🔥'),
   ('equilibrium','สมดุล','/ˌiːkwɪˈlɪbriəm/','⚖️'),('buoyancy','แรงลอยตัว','/ˈbɔɪənsi/','🛟'),
   ('vacuum','สุญญากาศ','/ˈvækjuːm/','🕳️')],
  "Friction is the reason we can walk and the reason engines wear out. Inertia is not laziness; it is an object keeping its own mind. Velocity is speed with a direction attached. Acceleration is any change in velocity, including slowing down. A moving bicycle carries kinetic energy that has to go somewhere. Thermal energy always flows from the warmer body to the cooler one. An object in equilibrium is not still; it is balanced. Buoyancy pushes up with the weight of the water pushed aside. In a vacuum a feather and a hammer fall at exactly the same rate.",
  ["Friction is the reason we can walk.",
   "Velocity is speed with a direction attached.",
   "Acceleration is any change in velocity, including slowing down.",
   "Thermal energy always flows from the warmer body to the cooler one.",
   "An object in equilibrium is not still; it is balanced."],
  ["Velocity is speed with a direction attached.",
   "An object in equilibrium is not still; it is balanced.",
   "Friction is the reason we can walk."],
  "What is velocity?","It is speed with a direction attached."),

D(334,333,'Light, Sound and Waves','🌈','Day335_ElectricityandMagnets_B2.html','🧲','wordsearch',
  'Measurement language: is measured in / is expressed as / ranges from.',
  [('wavelength','ความยาวคลื่น','/ˈweɪvleŋθ/','〰️'),('amplitude','แอมพลิจูด','/ˈæmplɪtjuːd/','📊'),
   ('oscillate','แกว่งไปมา','/ˈɒsɪleɪt/','🔄'),('resonance','การสั่นพ้อง','/ˈrezənəns/','🔔'),
   ('spectrum','สเปกตรัม','/ˈspektrəm/','🌈'),('refraction','การหักเหของแสง','/rɪˈfrækʃn/','🥃'),
   ('photon','โฟตอน','/ˈfəʊtɒn/','✨'),('radiation','การแผ่รังสี','/ˌreɪdiˈeɪʃn/','☢️'),
   ('turbulence','ความปั่นป่วน','/ˈtɜːbjələns/','🌪️')],
  "A short wavelength means a high note or a blue light. Amplitude decides how loud or how bright, not how high. A pendulum will oscillate until friction takes its energy away. Resonance can shatter a glass or bring down a bridge. White light splits into a full spectrum through a prism. Refraction is why a straw looks broken in a glass of water. A photon has no mass and still carries energy. Not all radiation is dangerous; the light in this room is radiation. Turbulence is common, poorly understood and rarely dangerous.",
  ["A short wavelength means a high note or a blue light.",
   "Amplitude decides how loud or how bright, not how high.",
   "Resonance can shatter a glass or bring down a bridge.",
   "Refraction is why a straw looks broken in a glass of water.",
   "A photon has no mass and still carries energy."],
  ["Amplitude decides how loud or how bright, not how high.",
   "Refraction is why a straw looks broken in a glass of water.",
   "A photon has no mass and still carries energy."],
  "Why does a straw look broken in water?","Because of refraction."),

D(335,334,'Electricity and Magnets','🧲','Day336_TheMachineryofLife_B2.html','🧬','vowels',
  'Cause and requirement: for X to happen, Y must first.',
  [('voltage','แรงดันไฟฟ้า','/ˈvəʊltɪdʒ/','🔋'),('resistance','ความต้านทาน','/rɪˈzɪstəns/','🚧'),
   ('insulator','ฉนวน','/ˈɪnsjuleɪtə(r)/','🧤'),('magnetism','แม่เหล็ก','/ˈmæɡnətɪzəm/','🧲'),
   ('compress','อัดให้แน่น','/kəmˈpres/','🗜️'),('viscosity','ความหนืด','/vɪˈskɒsəti/','🍯'),
   ('charge','ประจุไฟฟ้า','/tʃɑːdʒ/','⚡'),('specimen','ตัวอย่างที่นำมาศึกษา','/ˈspesɪmən/','🔬'),
   ('dissect','ผ่าศึกษา','/dɪˈsekt/','✂️')],
  "Voltage is the push; current is what actually moves. Resistance turns electrical energy into heat, usefully or wastefully. A good insulator is simply a very poor conductor. Magnetism and electricity are two faces of the same force. Gases compress easily; liquids almost refuse to. Honey has a high viscosity and water has a low one. An electric charge can be positive, negative or nothing at all. Label every specimen before you look at it, not after. To dissect a plant stem is to read how it carries water.",
  ["Voltage is the push; current is what actually moves.",
   "Resistance turns electrical energy into heat.",
   "A good insulator is simply a very poor conductor.",
   "Magnetism and electricity are two faces of the same force.",
   "Label every specimen before you look at it, not after."],
  ["A good insulator is simply a very poor conductor.",
   "Magnetism and electricity are two faces of the same force.",
   "Label every specimen before you look at it, not after."],
  "What is a good insulator?","It is simply a very poor conductor."),

D(336,335,'The Machinery of Life','🧬','Day337_Week49Review_B2.html','⭐','tiles',
  'Function and purpose: serves to / is responsible for / enables.',
  [('organism','สิ่งมีชีวิต','/ˈɔːɡənɪzəm/','🐛'),('membrane','เยื่อหุ้ม','/ˈmembreɪn/','🫧'),
   ('enzyme','เอนไซม์','/ˈenzaɪm/','🧪'),('chromosome','โครโมโซม','/ˈkrəʊməsəʊm/','🧵'),
   ('mutation','การกลายพันธุ์','/mjuːˈteɪʃn/','🎲'),('heredity','การถ่ายทอดทางพันธุกรรม','/həˈredəti/','👪'),
   ('respiration','การหายใจระดับเซลล์','/ˌrespəˈreɪʃn/','🫁'),('photosynthesis','การสังเคราะห์แสง','/ˌfəʊtəʊˈsɪnθəsɪs/','🌿'),
   ('antibody','แอนติบอดี','/ˈæntibɒdi/','🛡️')],
  "Every organism, from a bacterium to a whale, is built from cells. A membrane decides what may enter and what must stay outside. An enzyme is a catalyst made of protein. A human chromosome carries thousands of instructions in order. Most mutation is harmless; a little is harmful; a very little is useful. Heredity explains why you have your grandmother's hands. Respiration releases energy from food inside every living cell. Photosynthesis does the opposite, storing sunlight inside sugar. An antibody recognises an invader it has met before.",
  ["Every organism, from a bacterium to a whale, is built from cells.",
   "A membrane decides what may enter and what must stay outside.",
   "An enzyme is a catalyst made of protein.",
   "Respiration releases energy from food inside every living cell.",
   "An antibody recognises an invader it has met before."],
  ["A membrane decides what may enter and what must stay outside.",
   "An enzyme is a catalyst made of protein.",
   "An antibody recognises an invader it has met before."],
  "What does a membrane decide?","It decides what may enter and what must stay outside."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
