# -*- coding: utf-8 -*-
# Level 12 · B2 · Week 51 Media, Information & Persuasion (Day 345–350) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level12/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=12, cefr='B2', title=title, emoji=emoji, theme='Media',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(345,344,'The Story Behind the News','📰','Day346_WhoSaidIt_B2.html','🎙️','tiles',
  'Attribution: according to / as reported by / sources close to.',
  [('journalism','วารสารศาสตร์','/ˈdʒɜːnəlɪzəm/','📰'),('editorial','บทบรรณาธิการ','/ˌedɪˈtɔːriəl/','✒️'),
   ('bulletin','ข่าวสรุปสั้น','/ˈbʊlətɪn/','📻'),('correspondent','ผู้สื่อข่าวประจำพื้นที่','/ˌkɒrəˈspɒndənt/','🎒'),
   ('scoop','ข่าวที่ได้มาก่อนใคร','/skuːp/','🏆'),('byline','ชื่อผู้เขียนข่าว','/ˈbaɪlaɪn/','✍️'),
   ('circulation','ยอดจำหน่าย','/ˌsɜːkjəˈleɪʃn/','📦'),('paywall','กำแพงจ่ายเงินอ่าน','/ˈpeɪwɔːl/','🚪'),
   ('clickbait','พาดหัวล่อคลิก','/ˈklɪkbeɪt/','🪝')],
  "Journalism is the discipline of finding out what someone would rather you did not know. An editorial is the newspaper's own opinion, and it should say so. A bulletin gives you the facts in ninety seconds and no context at all. A correspondent who lives in a place reports it differently from a visitor. A scoop is exciting for one morning and forgotten by the afternoon. Look at the byline before you decide how much to trust a report. Falling circulation changed what newspapers could afford to investigate. A paywall keeps out both the freeloader and the curious student. Clickbait promises a feeling and delivers an advertisement.",
  ["Journalism is the discipline of finding out what someone would rather you did not know.",
   "An editorial is the newspaper's own opinion, and it should say so.",
   "A scoop is exciting for one morning and forgotten by the afternoon.",
   "Look at the byline before you decide how much to trust a report.",
   "Clickbait promises a feeling and delivers an advertisement."],
  ["An editorial is the newspaper's own opinion.",
   "Look at the byline before you decide how much to trust a report.",
   "Clickbait promises a feeling and delivers an advertisement."],
  "What should you look at before trusting a report?","Look at the byline."),

D(346,345,'Who Said It','🎙️','Day347_HowaStoryIsShaped_B2.html','🖼️','scramble',
  'Reporting sources: on condition of anonymity / declined to comment.',
  [('attribution','การระบุแหล่งที่มา','/ˌætrɪˈbjuːʃn/','🔖'),('offtherecord','พูดนอกบันทึก','/ˌɒfðəˈrekɔːd/','🤫'),
   ('embargo','การห้ามเผยแพร่ก่อนกำหนด','/ɪmˈbɑːɡəʊ/','⏰'),('leak','การรั่วไหลของข้อมูล','/liːk/','💧'),
   ('whistleblower','ผู้เปิดโปงความผิด','/ˈwɪslbləʊə(r)/','📣'),('factcheck','การตรวจสอบข้อเท็จจริง','/ˈfæktʃek/','🔍'),
   ('retraction','การถอนข่าวที่ผิด','/rɪˈtrækʃn/','↩️'),('libel','การหมิ่นประมาทด้วยลายลักษณ์','/ˈlaɪbl/','⚖️'),
   ('rebuttal','การโต้แย้งกลับ','/rɪˈbʌtl/','🛡️')],
  "Clear attribution tells you who is claiming this, not merely that it is claimed. A conversation offtherecord may inform a reporter without ever being printed. An embargo lets every outlet publish at the same minute. A leak is information released by someone who was not supposed to. A whistleblower usually loses more than they gain. A factcheck published a week later reaches a tenth of the original readers. An honest retraction is printed as loudly as the mistake was. Libel is a false written claim that damages a reputation. A rebuttal deserves the same space as the accusation.",
  ["Clear attribution tells you who is claiming this.",
   "An embargo lets every outlet publish at the same minute.",
   "A whistleblower usually loses more than they gain.",
   "An honest retraction is printed as loudly as the mistake was.",
   "A rebuttal deserves the same space as the accusation."],
  ["An embargo lets every outlet publish at the same minute.",
   "An honest retraction is printed as loudly as the mistake was.",
   "A rebuttal deserves the same space as the accusation."],
  "What does a rebuttal deserve?","The same space as the accusation."),

D(347,346,'How a Story Is Shaped','🖼️','Day348_TheBusinessofAttention_B2.html','💰','memory',
  'Analysing choices: by choosing to / by omitting / the effect of which is.',
  [('framing','การวางกรอบการเล่าเรื่อง','/ˈfreɪmɪŋ/','🖼️'),('slant','การเอียงข้าง','/slɑːnt/','📐'),
   ('sensational','เร้าอารมณ์เกินจริง','/senˈseɪʃənl/','💥'),('tabloid','หนังสือพิมพ์แนวเร้าใจ','/ˈtæblɔɪd/','🗞️'),
   ('broadsheet','หนังสือพิมพ์แนวจริงจัง','/ˈbrɔːdʃiːt/','📄'),('propaganda','การโฆษณาชวนเชื่อ','/ˌprɒpəˈɡændə/','📢'),
   ('testimonial','คำรับรองจากผู้ใช้','/ˌtestɪˈməʊniəl/','💬'),('spin','การบิดข่าวให้ดูดี','/spɪn/','🌀'),
   ('publicist','นักประชาสัมพันธ์','/ˈpʌblɪsɪst/','🕴️')],
  "Framing decides what the story is about before a single fact is stated. A slant is not always dishonest; it is often simply unexamined. A sensational headline sells a paper and shortens a reader's patience. The tabloid asks what will be talked about. The broadsheet asks what will still matter next month. Propaganda is not always false; often it is true and carefully incomplete. One warm testimonial persuades more than a table of results. Spin does not change the facts, only the order you meet them in. A publicist is paid to decide which sentence you hear first.",
  ["Framing decides what the story is about before a single fact is stated.",
   "A slant is not always dishonest; it is often simply unexamined.",
   "The broadsheet asks what will still matter next month.",
   "Propaganda is not always false; often it is true and carefully incomplete.",
   "Spin does not change the facts, only the order you meet them in."],
  ["A slant is not always dishonest.",
   "Propaganda is not always false; often it is carefully incomplete.",
   "Spin does not change the facts, only the order you meet them in."],
  "What does spin change?","Only the order you meet the facts in."),

D(348,347,'The Business of Attention','💰','Day349_WhenWeStopListening_B2.html','🫧','wordsearch',
  'Explaining structure: is funded by / depends on / is owned by.',
  [('syndicate','ขายข่าวต่อหลายสำนัก','/ˈsɪndɪkeɪt/','🔗'),('bureau','สำนักข่าวประจำเมือง','/ˈbjʊərəʊ/','🏢'),
   ('ownership','การถือครองสื่อ','/ˈəʊnəʃɪp/','🗝️'),('pluralism','ความหลากหลายของสื่อ','/ˈplʊərəlɪzəm/','🎨'),
   ('outrage','ความโกรธเกรี้ยว','/ˈaʊtreɪdʒ/','🔥'),('polarise','ทำให้แบ่งขั้ว','/ˈpəʊləraɪz/','🧲'),
   ('echochamber','ห้องเสียงสะท้อน','/ˈekəʊtʃeɪmbə(r)/','🔁'),('filterbubble','ฟองข้อมูลที่ถูกคัด','/ˈfɪltəbʌbl/','🫧'),
   ('civility','ความสุภาพในการถกเถียง','/səˈvɪləti/','🤝')],
  "A small paper may syndicate one article to forty towns. Closing a foreign bureau saves money and costs understanding. When ownership of the news narrows, the range of questions narrows too. Media pluralism means many owners, not many channels owned by one. Outrage is the cheapest emotion to produce and the most profitable to sell. A feed designed to keep you scrolling will slowly polarise what you believe. An echochamber is comfortable, which is exactly the danger. A filterbubble hides the disagreement rather than answering it. Civility is not weakness; it is what makes disagreement survivable.",
  ["Closing a foreign bureau saves money and costs understanding.",
   "When ownership of the news narrows, the range of questions narrows too.",
   "Outrage is the cheapest emotion to produce.",
   "An echochamber is comfortable, which is exactly the danger.",
   "Civility is what makes disagreement survivable."],
  ["Outrage is the cheapest emotion to produce.",
   "An echochamber is comfortable, which is exactly the danger.",
   "Civility is what makes disagreement survivable."],
  "Why is an echochamber dangerous?","Because it is comfortable."),

D(349,348,'When We Stop Listening','🫧','Day350_ReadingLikeaJournalist_B2.html','🔎','vowels',
  'Concession then correction: it is true that... however.',
  [('defamation','การทำให้เสียชื่อเสียง','/ˌdefəˈmeɪʃn/','⚔️'),('slander','การใส่ร้ายด้วยวาจา','/ˈslɑːndə(r)/','🗨️'),
   ('censor','เซ็นเซอร์','/ˈsensə(r)/','✂️'),('suppress','ปิดกั้นไม่ให้เผยแพร่','/səˈpres/','🤐'),
   ('dissent','ความเห็นต่าง','/dɪˈsent/','🙋'),('conformity','การคล้อยตามหมู่','/kənˈfɔːməti/','🐑'),
   ('wariness','ความระแวดระวัง','/ˈweərinəs/','🧐'),('cynicism','การไม่เชื่ออะไรเลย','/ˈsɪnɪsɪzəm/','🌑'),
   ('deliberation','การพิจารณาถกกันอย่างรอบคอบ','/dɪˌlɪbəˈreɪʃn/','🗣️')],
  "Defamation law protects reputation and can also protect the powerful. Slander is spoken; libel is written; both are hard to prove. To censor a story rarely makes it smaller. Governments that suppress bad news are usually the last to hear it. Dissent is not disloyalty, although it is often called that. Conformity feels like agreement and is often only silence. Healthy wariness keeps asking questions. Cynicism has already decided the answer and stopped asking. Public deliberation is what a society uses instead of force.",
  ["Slander is spoken; libel is written; both are hard to prove.",
   "To censor a story rarely makes it smaller.",
   "Dissent is not disloyalty, although it is often called that.",
   "Conformity feels like agreement and is often only silence.",
   "Public deliberation is what a society uses instead of force."],
  ["To censor a story rarely makes it smaller.",
   "Conformity feels like agreement and is often only silence.",
   "Public deliberation is what a society uses instead of force."],
  "Is dissent disloyalty?","No, dissent is not disloyalty."),

D(350,349,'Reading Like a Journalist','🔎','Day351_Week51Review_B2.html','⭐','tiles',
  'Checklists in formal English: verify whether / establish whether.',
  [('corroborate','ยืนยันจากอีกแหล่ง','/kəˈrɒbəreɪt/','✅'),('primary','แหล่งข้อมูลชั้นต้น','/ˈpraɪməri/','1️⃣'),
   ('secondary','แหล่งข้อมูลชั้นรอง','/ˈsekəndri/','2️⃣'),('vested','มีส่วนได้เสีย','/ˈvestɪd/','💼'),
   ('disclose','เปิดเผยข้อมูล','/dɪsˈkləʊz/','📤'),('context','บริบทแวดล้อม','/ˈkɒntekst/','🗺️'),
   ('omission','การละเว้นไม่กล่าวถึง','/əˈmɪʃn/','🕳️'),('plausible','ฟังดูมีเหตุผล','/ˈplɔːzəbl/','🤔'),
   ('substantiate','หาหลักฐานมายืนยัน','/səbˈstænʃieɪt/','🔬')],
  "Corroborate a surprising claim with a second independent source. A primary source was there. A secondary source read about it. Ask whether the speaker has a vested interest in what they are telling you. A writer should disclose any connection to the people in the story. A number without context is decoration, not evidence. An omission can mislead more effectively than a false statement. Plausible is not the same as true; the best lies are entirely plausible. If you cannot substantiate it, say so plainly.",
  ["Corroborate a surprising claim with a second independent source.",
   "A primary source was there. A secondary source read about it.",
   "A number without context is decoration, not evidence.",
   "An omission can mislead more effectively than a false statement.",
   "Plausible is not the same as true."],
  ["A number without context is decoration, not evidence.",
   "An omission can mislead more than a false statement.",
   "Plausible is not the same as true."],
  "What is a number without context?","It is decoration, not evidence."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
