# -*- coding: utf-8 -*-
# Level 11 · B2 · Week 47 Environment & Climate (Day 315–320) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level11/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=11, cefr='B2', title=title, emoji=emoji, theme='Environment',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(315,314,'One Warming Planet','🌡️','Day316_ExtremeWeather_B2.html','🌪️','tiles',
  'Expressing certainty in science: it is well established that / evidence indicates.',
  [('fossil','เชื้อเพลิงฟอสซิล','/ˈfɒsl/','🛢️'),('methane','ก๊าซมีเทน','/ˈmiːθeɪn/','🐄'),
   ('ozone','โอโซน','/ˈəʊzəʊn/','🛡️'),('albedo','ค่าการสะท้อนแสง','/ælˈbiːdəʊ/','🪞'),
   ('permafrost','ชั้นดินเยือกแข็ง','/ˈpɜːməfrɒst/','🧊'),('sealevel','ระดับน้ำทะเล','/ˈsiːlevl/','📏'),
   ('emitter','ผู้ปล่อยก๊าซ','/ɪˈmɪtə(r)/','🏭'),('offset','การชดเชยคาร์บอน','/ˈɒfset/','🌳'),
   ('mitigate','บรรเทาผลกระทบ','/ˈmɪtɪɡeɪt/','🩹')],
  "Burning fossil fuel releases gas that took millions of years to store. Methane traps far more heat than carbon dioxide, though it fades faster. The ozone layer recovered because countries agreed to act together. White ice has a high albedo and sends sunlight back to space. Melting permafrost releases gas that was frozen for ten thousand years. A rising sealevel does not need to be dramatic to be expensive. The ten largest emitter countries produce most of the problem. Planting trees to offset a flight is better than nothing and less than enough. To mitigate is to make the damage smaller before it arrives.",
  ["The ozone layer recovered because countries agreed to act together.",
   "White ice has a high albedo and sends sunlight back to space.",
   "Melting permafrost releases gas that was frozen for ten thousand years.",
   "A rising sealevel does not need to be dramatic to be expensive.",
   "To mitigate is to make the damage smaller before it arrives."],
  ["The ozone layer recovered because countries agreed to act together.",
   "A rising sealevel does not need to be dramatic to be expensive.",
   "To mitigate is to make the damage smaller before it arrives."],
  "Why did the ozone layer recover?","Because countries agreed to act together."),

D(316,315,'Extreme Weather','🌪️','Day317_LandWaterandWaste_B2.html','🗑️','scramble',
  'Predicting with data: is projected to / is expected to / is forecast to.',
  [('flooding','น้ำท่วม','/ˈflʌdɪŋ/','🌊'),('cyclone','พายุหมุน','/ˈsaɪkləʊn/','🌀'),
   ('wildfire','ไฟป่า','/ˈwaɪldfaɪə(r)/','🔥'),('heatwave','คลื่นความร้อน','/ˈhiːtweɪv/','🥵'),
   ('monsoon','ลมมรสุม','/mɒnˈsuːn/','☔'),('desertification','การกลายเป็นทะเลทราย','/dɪˌzɜːtɪfɪˈkeɪʃn/','🏜️'),
   ('adaptation','การปรับตัว','/ˌædæpˈteɪʃn/','🔧'),('quota','โควตา','/ˈkwəʊtə/','📊'),
   ('regulator','หน่วยงานกำกับดูแล','/ˈreɡjuleɪtə(r)/','👮')],
  "Flooding kills more people worldwide than any other natural event. A cyclone gathers its strength from warm ocean water. One wildfire can release the carbon of a whole city's year. A heatwave is dangerous mostly at night, when nobody cools down. When the monsoon arrives late, two harvests are lost. Desertification spreads slowly and is almost never reversed. Adaptation means building for the climate we will have, not the one we had. A fishing quota is unpopular until the fish return. An independent regulator is only useful if it can say no.",
  ["Flooding kills more people worldwide than any other natural event.",
   "A cyclone gathers its strength from warm ocean water.",
   "A heatwave is dangerous mostly at night, when nobody cools down.",
   "When the monsoon arrives late, two harvests are lost.",
   "A fishing quota is unpopular until the fish return."],
  ["A cyclone gathers its strength from warm ocean water.",
   "When the monsoon arrives late, two harvests are lost.",
   "A fishing quota is unpopular until the fish return."],
  "Where does a cyclone get its strength?","From warm ocean water."),

D(317,316,'Land, Water and Waste','🗑️','Day318_LifeontheEdge_B2.html','🐾','memory',
  'Describing cycles: is broken down into / is released back into.',
  [('landfill','หลุมฝังกลบขยะ','/ˈlændfɪl/','🚮'),('incinerate','เผาทำลาย','/ɪnˈsɪnəreɪt/','♨️'),
   ('decompose','ย่อยสลาย','/ˌdiːkəmˈpəʊz/','🍂'),('biodegradable','ย่อยสลายได้เอง','/ˌbaɪəʊdɪˈɡreɪdəbl/','🌱'),
   ('microplastic','ไมโครพลาสติก','/ˌmaɪkrəʊˈplæstɪk/','🔬'),('contamination','การปนเปื้อน','/kənˌtæmɪˈneɪʃn/','☣️'),
   ('aquifer','ชั้นน้ำใต้ดิน','/ˈækwɪfə(r)/','💧'),('sanitation','การสุขาภิบาล','/ˌsænɪˈteɪʃn/','🚰'),
   ('runoff','น้ำไหลบ่า','/ˈrʌnɒf/','🏞️')],
  "A landfill is not a solution; it is a decision to wait. To incinerate rubbish creates energy and also creates air pollution. Food waste will decompose in weeks; a plastic bottle will not. Biodegradable packaging only works if it is sent to the right place. Microplastic has been found in rain, in fish and in human blood. Contamination of one well can affect a whole district. An aquifer refills over centuries and empties in decades. Safe sanitation has saved more lives than almost any medicine. Farm runoff carries fertiliser into the river and starves it of oxygen.",
  ["A landfill is not a solution; it is a decision to wait.",
   "Food waste will decompose in weeks; a plastic bottle will not.",
   "Microplastic has been found in rain, in fish and in human blood.",
   "An aquifer refills over centuries and empties in decades.",
   "Safe sanitation has saved more lives than almost any medicine."],
  ["A landfill is not a solution; it is a decision to wait.",
   "An aquifer refills over centuries and empties in decades.",
   "Safe sanitation has saved more lives than almost any medicine."],
  "What is a landfill?","It is a decision to wait, not a solution."),

D(318,317,'Life on the Edge','🐾','Day319_PowerWithoutSmoke_B2.html','⚡','wordsearch',
  'Relative clauses in science: species which depend on / areas where.',
  [('biodiversity','ความหลากหลายทางชีวภาพ','/ˌbaɪəʊdaɪˈvɜːsəti/','🦜'),('ecosystem','ระบบนิเวศ','/ˈiːkəʊsɪstəm/','🕸️'),
   ('extinction','การสูญพันธุ์','/ɪkˈstɪŋkʃn/','🦤'),('poaching','การล่าสัตว์ผิดกฎหมาย','/ˈpəʊtʃɪŋ/','🚫'),
   ('wetland','พื้นที่ชุ่มน้ำ','/ˈwetlənd/','🦩'),('reforestation','การปลูกป่าทดแทน','/ˌriːfɒrɪˈsteɪʃn/','🌲'),
   ('conservation','การอนุรักษ์','/ˌkɒnsəˈveɪʃn/','🐾'),('acidification','ภาวะเป็นกรด','/əˌsɪdɪfɪˈkeɪʃn/','🧪'),
   ('sediment','ตะกอน','/ˈsedɪmənt/','🪨')],
  "Biodiversity is insurance that a system cannot buy anywhere else. Remove one species and the ecosystem rearranges itself in ways nobody predicted. Extinction is the only environmental problem that cannot be undone. Poaching survives because the buyers are far away and comfortable. A single wetland filters more water than an expensive plant. Reforestation works when local people gain from the trees standing. Conservation that ignores the nearest village usually fails. Ocean acidification makes it harder for shells to form. Sediment washed from bare hills buries the coral below.",
  ["Biodiversity is insurance that a system cannot buy anywhere else.",
   "Extinction is the only environmental problem that cannot be undone.",
   "A single wetland filters more water than an expensive plant.",
   "Reforestation works when local people gain from the trees standing.",
   "Conservation that ignores the nearest village usually fails."],
  ["Extinction is the only environmental problem that cannot be undone.",
   "A single wetland filters more water than an expensive plant.",
   "Conservation that ignores the nearest village usually fails."],
  "Which environmental problem cannot be undone?","Extinction cannot be undone."),

D(319,318,'Power Without Smoke','⚡','Day320_LivingwithLess_B2.html','♻️','vowels',
  'Comparing options: outperforms / falls short of / is comparable to.',
  [('photovoltaic','เซลล์แสงอาทิตย์','/ˌfəʊtəʊvɒlˈteɪɪk/','🔆'),('turbine','กังหันผลิตไฟ','/ˈtɜːbaɪn/','🌬️'),
   ('geothermal','พลังงานความร้อนใต้พิภพ','/ˌdʒiːəʊˈθɜːml/','🌋'),('hydropower','พลังน้ำ','/ˈhaɪdrəʊpaʊə(r)/','⚙️'),
   ('biomass','ชีวมวล','/ˈbaɪəʊmæs/','🪵'),('insulate','บุฉนวนกันความร้อน','/ˈɪnsjuleɪt/','🧥'),
   ('retrofit','ปรับปรุงอาคารเดิม','/ˈretrəʊfɪt/','🔩'),('consumption','การบริโภคพลังงาน','/kənˈsʌmpʃn/','🔌'),
   ('footprint','รอยเท้าคาร์บอน','/ˈfʊtprɪnt/','👣')],
  "A photovoltaic panel has no moving parts and lasts thirty years. One large turbine can power six hundred homes on a windy day. Geothermal energy is steady, which wind and sun are not. Hydropower is clean to run and difficult to build. Burning biomass is only clean if the plants are replanted. It is cheaper to insulate a house than to heat a cold one forever. To retrofit an old building saves more carbon than replacing it. The cleanest unit of energy is the consumption that never happens. Measure your footprint before you try to shrink it.",
  ["A photovoltaic panel has no moving parts and lasts thirty years.",
   "Geothermal energy is steady, which wind and sun are not.",
   "Burning biomass is only clean if the plants are replanted.",
   "It is cheaper to insulate a house than to heat a cold one forever.",
   "Measure your footprint before you try to shrink it."],
  ["Geothermal energy is steady, which wind and sun are not.",
   "It is cheaper to insulate a house than to heat a cold one forever.",
   "Measure your footprint before you try to shrink it."],
  "What is the cleanest unit of energy?","The consumption that never happens."),

D(320,319,'Living with Less','♻️','Day321_Week47Review_B2.html','⭐','tiles',
  'Proposing solutions: one option would be to / a further step is to.',
  [('circular','เศรษฐกิจหมุนเวียน','/ˈsɜːkjələ(r)/','🔄'),('reuse','ใช้ซ้ำ','/ˌriːˈjuːz/','🧺'),
   ('repurpose','ดัดแปลงไปใช้อย่างอื่น','/ˌriːˈpɜːpəs/','🪛'),('toxic','เป็นพิษ','/ˈtɒksɪk/','☠️'),
   ('salinity','ความเค็มของน้ำ','/səˈlɪnəti/','🧂'),('desalination','การผลิตน้ำจืดจากน้ำทะเล','/ˌdiːsælɪˈneɪʃn/','🧴'),
   ('irrigate','ทดน้ำเข้าพื้นที่','/ˈɪrɪɡeɪt/','🚿'),('nitrate','ไนเตรต','/ˈnaɪtreɪt/','🧫'),
   ('robustness','ความทนทานต่อแรงกระแทก','/rəʊˈbʌstnəs/','🌾')],
  "A circular economy treats waste as a design mistake. To reuse a container twenty times beats recycling it once. You can repurpose an old door into a desk in an afternoon. Some cleaning products are toxic long after the smell has gone. Rising salinity is turning good farmland into salt flats. Desalination gives water to dry cities and uses a great deal of power. Farmers who irrigate at night lose far less to the air. Too much nitrate in a river feeds algae and nothing else. Robustness is not resisting change; it is recovering from it.",
  ["A circular economy treats waste as a design mistake.",
   "To reuse a container twenty times beats recycling it once.",
   "Rising salinity is turning good farmland into salt flats.",
   "Farmers who irrigate at night lose far less to the air.",
   "Robustness is not resisting change; it is recovering from it."],
  ["A circular economy treats waste as a design mistake.",
   "Farmers who irrigate at night lose far less to the air.",
   "Robustness is not resisting change; it is recovering from it."],
  "What is robustness?","It is recovering from change, not resisting it."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
