# -*- coding: utf-8 -*-
# Level 8 · B1 · Week 35 Cities & Building (225–231) · Week 36 Health Deep (232–238) + 239–240
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level8/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta, theme='City'):
    return dict(n=n, prev=prev, level=8, cefr='B1', title=title, emoji=emoji, theme=theme,
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(225,224,'How Buildings Rise','🏗️','Day226_CityLife_B1.html','🌆','tiles',
  'Order of adjectives: a tall modern glass tower.',
  [('architecture','สถาปัตยกรรม','/ˈɑːkɪtektʃə(r)/','📐'),('structure','โครงสร้าง','/ˈstrʌktʃə(r)/','🏢'),
   ('foundation','ฐานราก','/faʊnˈdeɪʃn/','🧱'),('concrete','คอนกรีต','/ˈkɒŋkriːt/','🪨'),
   ('beam','คาน','/biːm/','➖'),('blueprint','แบบแปลน','/ˈbluːprɪnt/','📄'),
   ('construct','ก่อสร้าง','/kənˈstrʌkt/','🔨'),('skyscraper','ตึกระฟ้า','/ˈskaɪskreɪpə(r)/','🏙️')],
  "Good architecture is beautiful and useful at the same time. Every structure begins with a deep foundation. Workers pour concrete around the steel beam. The engineer checks the blueprint every morning. It takes two years to construct a tall modern skyscraper. A building must be safe before it is pretty. Cities grow upward when land becomes expensive.",
  ["Good architecture is beautiful and useful.",
   "Every structure begins with a deep foundation.",
   "Workers pour concrete around the steel beam.",
   "The engineer checks the blueprint every morning.",
   "A building must be safe before it is pretty."],
  ["Every structure begins with a deep foundation.",
   "The engineer checks the blueprint every morning.",
   "A building must be safe before it is pretty."],
  "What does every structure begin with?","It begins with a deep foundation."),

D(226,225,'City Life','🌆','Day227_GettingAround_B1.html','🚇','scramble',
  'Comparing places: more crowded than / not as quiet as.',
  [('urban','ในเมือง','/ˈɜːbən/','🏙️'),('rural','ชนบท','/ˈrʊərəl/','🌾'),
   ('population','ประชากร','/ˌpɒpjuˈleɪʃn/','👨‍👩‍👧'),('migrate','ย้ายถิ่น','/maɪˈɡreɪt/','🧳'),
   ('suburb','ชานเมือง','/ˈsʌbɜːb/','🏘️'),('noise','เสียงรบกวน','/nɔɪz/','🔊'),
   ('convenience','ความสะดวก','/kənˈviːniəns/','🛒'),('anonymous','ไม่มีใครรู้จัก','/əˈnɒnɪməs/','🕵️')],
  "An urban area is far more crowded than a rural village. The population of this city doubled in twenty years. Many families migrate here to find work. Ben's cousin lives in a quiet suburb outside the centre. City noise never really stops at night. The convenience of shops and trains is the main attraction. Yet you can feel anonymous among a million people.",
  ["An urban area is far more crowded than a rural village.",
   "The population of this city doubled in twenty years.",
   "Many families migrate here to find work.",
   "City noise never really stops at night.",
   "You can feel anonymous among a million people."],
  ["The population of this city doubled in twenty years.",
   "City noise never really stops at night.",
   "You can feel anonymous among a million people."],
  "Why do many families migrate to the city?","They migrate to find work."),

D(227,226,'Getting Around','🚇','Day228_FoodLabels_B1.html','🏷️','memory',
  'Making complaints politely: I am afraid the bus was late again.',
  [('infrastructure','โครงสร้างพื้นฐาน','/ˈɪnfrəstrʌktʃə(r)/','🛤️'),('commute','เดินทางไปทำงาน','/kəˈmjuːt/','🚌'),
   ('congestion','การจราจรติดขัด','/kənˈdʒestʃən/','🚗'),('pedestrian','คนเดินเท้า','/pəˈdestriən/','🚶'),
   ('cyclist','คนขี่จักรยาน','/ˈsaɪklɪst/','🚴'),('subway','รถไฟใต้ดิน','/ˈsʌbweɪ/','🚇'),
   ('service','บริการเดินรถ','/ˈsɜːvɪs/','⚡'),('punctuality','การตรงเวลา','/ˌpʌŋktʃuˈæləti/','⏱️')],
  "Good infrastructure decides how a city feels. Dad has to commute forty minutes each way. Traffic congestion is worst between seven and nine. A safe pedestrian crossing saves lives. More people would ride if a cyclist felt protected. The subway service is the most reliable at rush hour. I am afraid punctuality was poor again this morning.",
  ["Good infrastructure decides how a city feels.",
   "Dad has to commute forty minutes each way.",
   "Traffic congestion is worst between seven and nine.",
   "A safe pedestrian crossing saves lives.",
   "The subway service is the most reliable at rush hour."],
  ["Dad has to commute forty minutes each way.",
   "A safe pedestrian crossing saves lives.",
   "The subway service is the most reliable at rush hour."],
  "When is traffic congestion worst?","It is worst between seven and nine."),

D(228,227,'Food Labels','🏷️','Day229_MindAndBody_B1.html','🧘','wordsearch',
  'Quantifiers: a great deal of sugar, hardly any fibre.',
  [('organic','ปลอดสารเคมี','/ɔːˈɡænɪk/','🌱'),('processed','ผ่านการแปรรูป','/ˈprəʊsest/','📦'),
   ('additive','สารเจือปน','/ˈædətɪv/','🧫'),('preservative','สารกันเสีย','/prɪˈzɜːvətɪv/','🧴'),
   ('calorie','แคลอรี','/ˈkæləri/','🔥'),('vegetarian','มังสวิรัติ','/ˌvedʒəˈteəriən/','🥗'),
   ('allergy','ภูมิแพ้','/ˈælədʒi/','🤧'),('digest','ย่อยอาหาร','/daɪˈdʒest/','🫄')],
  "Organic food is grown without strong chemicals. A processed snack often contains a great deal of sugar. Read the additive list on the back of the packet. Some preservative keeps bread fresh for weeks. One small cake can hold three hundred calorie. Mimi became vegetarian last year. Ben has a nut allergy so he checks every label. Fresh food is also easier to digest.",
  ["Organic food is grown without strong chemicals.",
   "A processed snack often contains a great deal of sugar.",
   "Read the additive list on the back of the packet.",
   "Mimi became vegetarian last year.",
   "Fresh food is also easier to digest."],
  ["A processed snack often contains a great deal of sugar.",
   "Mimi became vegetarian last year.",
   "Fresh food is also easier to digest."],
  "Why does Ben check every label?","Because he has a nut allergy."),

D(229,228,'Mind and Body','🧘','Day230_HelpingMinds_B1.html','💚','vowels',
  'Advice with gerunds: Getting enough sleep helps. Skipping meals does not.',
  [('immune','ภูมิคุ้มกัน','/ɪˈmjuːn/','🛡️'),('metabolism','การเผาผลาญ','/məˈtæbəlɪzəm/','🔄'),
   ('appetite','ความอยากอาหาร','/ˈæpɪtaɪt/','🍽️'),('posture','ท่าทาง','/ˈpɒstʃə(r)/','🧍'),
   ('hydrate','ดื่มน้ำให้พอ','/haɪˈdreɪt/','💧'),('recovery','การฟื้นตัว','/rɪˈkʌvəri/','🔁'),
   ('mindfulness','การมีสติ','/ˈmaɪndflnəs/','🧠'),('burnout','ภาวะหมดไฟ','/ˈbɜːnaʊt/','🕯️')],
  "Sleep builds a strong immune system. Regular meals keep your metabolism steady. Stress can change your appetite very quickly. Sitting all day damages your posture. Remember to hydrate before you feel thirsty. Rest is part of training, not the opposite: recovery matters. Ten minutes of mindfulness lowers stress. Ignoring all of this leads to burnout.",
  ["Sleep builds a strong immune system.",
   "Regular meals keep your metabolism steady.",
   "Stress can change your appetite very quickly.",
   "Remember to hydrate before you feel thirsty.",
   "Ten minutes of mindfulness lowers stress."],
  ["Regular meals keep your metabolism steady.",
   "Remember to hydrate before you feel thirsty.",
   "Ten minutes of mindfulness lowers stress."],
  "What does sleep build?","Sleep builds a strong immune system."),

D(230,229,'Helping Minds','💚','Day231_Week35Review_B1.html','⭐','tiles',
  'Softening language: it can be hard to / it might help to / you may want to.',
  [('emotional','ทางอารมณ์','/ɪˈməʊʃənl/','💗'),('counsellor','ผู้ให้คำปรึกษา','/ˈkaʊnsələ(r)/','🧑‍⚕️'),
   ('therapy','การบำบัด','/ˈθerəpi/','🛋️'),('stigma','ตราบาปทางสังคม','/ˈstɪɡmə/','🚫'),
   ('cope','รับมือ','/kəʊp/','🪢'),('vulnerable','เปราะบาง','/ˈvʌlnərəbl/','🫧'),
   ('openness','การเปิดใจ','/ˈəʊpənnəs/','💬'),('heal','เยียวยา','/hiːl/','🌤️')],
  "Emotional health matters as much as physical health. A school counsellor is there to listen, not to judge. Therapy is simply a place to think out loud. Old stigma stops many people from asking for help. Everyone needs a way to cope with hard weeks. It is human to feel vulnerable sometimes. Openness with someone you trust helps you heal faster.",
  ["Emotional health matters as much as physical health.",
   "A school counsellor is there to listen, not to judge.",
   "Old stigma stops many people from asking for help.",
   "Everyone needs a way to cope with hard weeks.",
   "It is human to feel vulnerable sometimes."],
  ["A school counsellor is there to listen, not to judge.",
   "Everyone needs a way to cope with hard weeks.",
   "It is human to feel vulnerable sometimes."],
  "What stops many people from asking for help?","Old stigma stops them."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']),'คำ')
