# -*- coding: utf-8 -*-
# Level 9 · B1 · Week 40 Independent Life (Day 262–267)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level9/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=9, cefr='B1', title=title, emoji=emoji, theme='Independent Life',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(262,261,'Borrowing and Saving','💰','Day263_APlaceofMyOwn_B1.html','🏠','tiles',
  'Purpose: so that / in order to / to avoid + -ing.',
  [('loan','เงินกู้','/ləʊn/','🏦'),('insurance','ประกันภัย','/ɪnˈʃʊərəns/','🛡️'),
   ('mortgage','สินเชื่อบ้าน','/ˈmɔːɡɪdʒ/','🏡'),('guarantee','การรับประกัน','/ˌɡærənˈtiː/','📜'),
   ('pension','เงินบำนาญ','/ˈpenʃn/','👵'),('instalment','เงินผ่อนงวด','/ɪnˈstɔːlmənt/','📆'),
   ('surplus','เงินเหลือ','/ˈsɜːpləs/','➕'),('overdraft','เบิกเกินบัญชี','/ˈəʊvədrɑːft/','➖')],
  "A loan is easy to take and slow to repay. Good insurance is boring until the day you need it. A mortgage lasts longer than most jobs. Keep the guarantee in a safe place. Your pension starts with the first coin you save. Pay each instalment on the same day every month. A small surplus each month becomes calm sleep at night. An overdraft is not extra money.",
  ["A loan is easy to take and slow to repay.",
   "A mortgage lasts longer than most jobs.",
   "Keep the guarantee in a safe place.",
   "Pay each instalment on the same day every month.",
   "An overdraft is not extra money."],
  ["A mortgage lasts longer than most jobs.",
   "Keep the guarantee in a safe place.",
   "An overdraft is not extra money."],
  "When is good insurance important?","On the day you need it."),

D(263,262,'A Place of My Own','🏠','Day264_LookingAfterYourself_B1.html','💊','scramble',
  'Passive voice: The rent is paid on the first of the month.',
  [('tenant','ผู้เช่า','/ˈtenənt/','🔑'),('rental','บ้านเช่า','/ˈrentl/','🏘️'),
   ('lease','สัญญาเช่า','/liːs/','📃'),('utility','ค่าน้ำค่าไฟ','/juːˈtɪləti/','💡'),
   ('furnish','ตกแต่งใส่เฟอร์นิเจอร์','/ˈfɜːnɪʃ/','🛋️'),('pantry','ตู้เก็บอาหารแห้ง','/ˈpæntri/','🥫'),
   ('grocery','ของชำ','/ˈɡrəʊsəri/','🛒'),('leftover','อาหารเหลือ','/ˈleftəʊvə(r)/','🍱')],
  "A tenant has rights, not only bills. Tell the rental office about a leak the same day. Read the lease before you sign it. Each utility is billed separately here. You do not need to furnish every room at once. A full pantry saves money on busy evenings. Write a grocery list before you leave home. Tonight we eat the leftover curry.",
  ["A tenant has rights, not only bills.",
   "Read the lease before you sign it.",
   "You do not need to furnish every room at once.",
   "Write a grocery list before you leave home.",
   "Tonight we eat the leftover curry."],
  ["Read the lease before you sign it.",
   "Write a grocery list before you leave home.",
   "Tonight we eat the leftover curry."],
  "When should you read the lease?","Before you sign it."),

D(264,263,'Looking After Yourself','💊','Day265_PapersandPermission_B1.html','📑','memory',
  'Advice in the past: should have / ought to have.',
  [('prescription','ใบสั่งยา','/prɪˈskrɪpʃn/','📝'),('ailment','อาการเจ็บป่วย','/ˈeɪlmənt/','🤕'),
   ('pharmacy','ร้านขายยา','/ˈfɑːməsi/','⚕️'),('optician','ร้านตัดแว่น','/ɒpˈtɪʃn/','👓'),
   ('vaccination','การฉีดวัคซีน','/ˌvæksɪˈneɪʃn/','💉'),('dosage','ขนาดยาที่ใช้','/ˈdəʊsɪdʒ/','🥄'),
   ('checkup','การตรวจสุขภาพ','/ˈtʃekʌp/','🩺'),('immunity','ภูมิคุ้มกัน','/ɪˈmjuːnəti/','🦠')],
  "Never share a prescription with a friend. Write down every ailment before the appointment. The pharmacy on the corner opens late. Book an optician if the letters look blurred. One vaccination protects a whole classroom. Read the dosage twice, especially at night. A yearly checkup costs less than a hospital week. Sleep builds immunity better than any drink.",
  ["Never share a prescription with a friend.",
   "Write down every ailment before the appointment.",
   "The pharmacy on the corner opens late.",
   "Read the dosage twice, especially at night.",
   "Sleep builds immunity better than any drink."],
  ["Never share a prescription with a friend.",
   "Read the dosage twice, especially at night.",
   "Sleep builds immunity better than any drink."],
  "What builds immunity better than any drink?","Sleep builds immunity."),

D(265,264,'Papers and Permission','📑','Day266_HealthyHabits_B1.html','🧘','wordsearch',
  'Requirement: You are required to / You are not allowed to.',
  [('licence','ใบอนุญาต','/ˈlaɪsns/','🪪'),('permit','ใบอนุญาตเฉพาะ','/ˈpɜːmɪt/','✅'),
   ('visa','วีซ่า','/ˈviːzə/','🛂'),('embassy','สถานทูต','/ˈembəsi/','🏛️'),
   ('customs','ศุลกากร','/ˈkʌstəmz/','🧳'),('terminal','อาคารผู้โดยสาร','/ˈtɜːmɪnl/','🛫'),
   ('boarding','การขึ้นเครื่อง','/ˈbɔːdɪŋ/','🎫'),('refundable','ขอเงินคืนได้','/rɪˈfʌndəbl/','↩️')],
  "You need a licence before you drive alone. A work permit is not the same as a visa. Apply for your visa early, never the week before. The embassy answers questions by email now. Declare everything at customs and nothing goes wrong. Terminal two is a long walk from terminal one. Boarding closes twenty minutes before take off. Only the flexible ticket is refundable.",
  ["You need a licence before you drive alone.",
   "A work permit is not the same as a visa.",
   "The embassy answers questions by email now.",
   "Declare everything at customs and nothing goes wrong.",
   "Only the flexible ticket is refundable."],
  ["A work permit is not the same as a visa.",
   "The embassy answers questions by email now.",
   "Only the flexible ticket is refundable."],
  "Which ticket is refundable?","Only the flexible ticket is refundable."),

D(266,265,'Healthy Habits','🧘','Day267_StandingonMyOwn_B1.html','🌱','vowels',
  'Frequency and habit: tend to / used to / no longer.',
  [('hydration','การดื่มน้ำให้พอ','/haɪˈdreɪʃn/','💧'),('wellbeing','สุขภาวะ','/ˌwelˈbiːɪŋ/','🌈'),
   ('caffeine','คาเฟอีน','/ˈkæfiːn/','☕'),('screentime','เวลาอยู่หน้าจอ','/ˈskriːntaɪm/','📱'),
   ('priority','สิ่งที่สำคัญก่อน','/praɪˈɒrəti/','🥇'),('reflection','การทบทวนตนเอง','/rɪˈflekʃn/','🪞'),
   ('purpose','เป้าหมายในชีวิต','/ˈpɜːpəs/','🧭'),('cautious','ระมัดระวัง','/ˈkɔːʃəs/','🐢')],
  "Hydration is the cheapest medicine you own. Wellbeing is built on ordinary days, not holidays. Caffeine after four keeps you awake at eleven. Cut your screentime by ten minutes a week. Sleep is a priority, not a reward. A few minutes of reflection each evening is enough. A clear purpose makes hard mornings easier. Be cautious with any habit that promises quick results.",
  ["Hydration is the cheapest medicine you own.",
   "Wellbeing is built on ordinary days, not holidays.",
   "Cut your screentime by ten minutes a week.",
   "Sleep is a priority, not a reward.",
   "A clear purpose makes hard mornings easier."],
  ["Hydration is the cheapest medicine you own.",
   "Sleep is a priority, not a reward.",
   "A clear purpose makes hard mornings easier."],
  "Is sleep a priority or a reward?","Sleep is a priority, not a reward."),

D(267,266,'Standing on My Own','🌱','Day268_Week40Review_B1.html','⭐','tiles',
  'Definitions with relative clauses: a person who / a habit that.',
  [('trustworthy','ไว้ใจได้','/ˈtrʌstwɜːði/','🤞'),('organised','เป็นระเบียบ','/ˈɔːɡənaɪzd/','🗄️'),
   ('adulthood','วัยผู้ใหญ่','/ˈædʌlthʊd/','🧑'),('errand','ธุระเล็กๆ','/ˈerənd/','🚲'),
   ('sensible','มีเหตุผลรอบคอบ','/ˈsensəbl/','🧠'),('foresight','การมองการณ์ไกล','/ˈfɔːsaɪt/','🔭'),
   ('prudent','สุขุมรอบคอบ','/ˈpruːdnt/','⚓'),('responsibility','ความรับผิดชอบ','/rɪˌspɒnsəˈbɪləti/','🎒')],
  "A trustworthy person keeps small promises too. Being organised is a skill, not a personality. Adulthood arrives slowly, one decision at a time. Offer to run an errand before you are asked. A sensible choice is rarely the exciting one. Foresight means paying today for a calmer next year. A prudent saver is never in a hurry. Responsibility is what you do when nobody checks.",
  ["A trustworthy person keeps small promises too.",
   "Being organised is a skill, not a personality.",
   "Offer to run an errand before you are asked.",
   "A sensible choice is rarely the exciting one.",
   "Responsibility is what you do when nobody checks."],
  ["Being organised is a skill, not a personality.",
   "A sensible choice is rarely the exciting one.",
   "Responsibility is what you do when nobody checks."],
  "What is responsibility?","It is what you do when nobody checks."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn)
