# -*- coding: utf-8 -*-
# Level 15 · B2 · Week 62 Life on Earth (Day 428–433) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level15/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=15, cefr='B2', title=title, emoji=emoji, theme='Life on Earth',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(428,427,'The Story of Life','🧬','Day429_SortingtheLiving_B2.html','🗂️','tiles',
  'Explaining mechanism: over many generations / those that survive tend to.',
  [('evolution','วิวัฒนาการ','/ˌiːvəˈluːʃn/','🧬'),('naturalselection','การคัดเลือกโดยธรรมชาติ','/ˌnætʃrəlsɪˈlekʃn/','🎯'),
   ('variation','ความแตกต่างในหมู่ประชากร','/ˌveəriˈeɪʃn/','🎲'),('speciation','การเกิดสปีชีส์ใหม่','/ˌspiːʃiˈeɪʃn/','🌿'),
   ('lineage','สายวิวัฒนาการ','/ˈlɪniɪdʒ/','🌳'),('fossilrecord','บันทึกซากดึกดำบรรพ์','/ˈfɒslrekɔːd/','🦴'),
   ('phylogeny','แผนภูมิสายวิวัฒนาการ','/faɪˈlɒdʒəni/','🕸️'),('vestigial','เหลือร่องรอยจากอดีต','/veˈstɪdʒiəl/','🪶'),
   ('convergent','วิวัฒนาการมาบรรจบกัน','/kənˈvɜːdʒənt/','🔀')],
  "Evolution is not a plan; it is what remains after everything else fails. Naturalselection needs three things: variation, inheritance and pressure. Without variation in a population, selection has nothing to choose between. Speciation usually begins when a mountain or a river separates two groups. A lineage can be traced backwards but never predicted forwards. The fossilrecord is incomplete because fossilisation is rare and lucky. A phylogeny is a family tree for every living thing. A vestigial structure is a leftover from an ancestor that needed it. Convergent evolution gave wings to birds, bats and insects separately.",
  ["Evolution is not a plan; it is what remains after everything else fails.",
   "Naturalselection needs variation, inheritance and pressure.",
   "Speciation usually begins when a mountain or a river separates two groups.",
   "The fossilrecord is incomplete because fossilisation is rare and lucky.",
   "A vestigial structure is a leftover from an ancestor that needed it."],
  ["Naturalselection needs variation, inheritance and pressure.",
   "The fossilrecord is incomplete because fossilisation is rare and lucky.",
   "A vestigial structure is a leftover from an ancestor that needed it."],
  "What three things does naturalselection need?","Variation, inheritance and pressure."),

D(429,428,'Sorting the Living','🗂️','Day430_HowAnimalsSurvive_B2.html','🦎','scramble',
  'Classification language: belongs to / is grouped with / is distinguished by.',
  [('taxonomy','อนุกรมวิธาน','/tækˈsɒnəmi/','🗂️'),('genus','สกุลของสิ่งมีชีวิต','/ˈdʒiːnəs/','🏷️'),
   ('phylum','ไฟลัม','/ˈfaɪləm/','🌐'),('vertebrate','สัตว์มีกระดูกสันหลัง','/ˈvɜːtɪbrət/','🐟'),
   ('invertebrate','สัตว์ไม่มีกระดูกสันหลัง','/ɪnˈvɜːtɪbrət/','🐙'),('mammal','สัตว์เลี้ยงลูกด้วยนม','/ˈmæml/','🐘'),
   ('amphibian','สัตว์สะเทินน้ำสะเทินบก','/æmˈfɪbiən/','🐸'),('arthropod','สัตว์ขาปล้อง','/ˈɑːθrəpɒd/','🦂'),
   ('metamorphosis','การเปลี่ยนรูปร่าง','/ˌmetəˈmɔːfəsɪs/','🦋')],
  "Taxonomy gives every organism a two part name that works in any language. A genus groups species that share a recent common ancestor. A phylum is one of the very largest divisions of the animal kingdom. Every vertebrate on earth shares the same basic skeleton plan. More than ninety five per cent of animal species are invertebrate. A mammal feeds its young on milk and almost always has hair. An amphibian begins in water and moves onto land halfway through its life. The arthropod group includes insects, spiders and crabs together. Complete metamorphosis rebuilds an animal from the inside out.",
  ["Taxonomy gives every organism a two part name that works in any language.",
   "Every vertebrate on earth shares the same basic skeleton plan.",
   "More than ninety five per cent of animal species are invertebrate.",
   "A mammal feeds its young on milk and almost always has hair.",
   "Complete metamorphosis rebuilds an animal from the inside out."],
  ["Every vertebrate on earth shares the same basic skeleton plan.",
   "A mammal feeds its young on milk and almost always has hair.",
   "Complete metamorphosis rebuilds an animal from the inside out."],
  "What does a mammal do?","It feeds its young on milk."),

D(430,429,'How Animals Survive','🦎','Day431_LivingTogether_B2.html','🤝','memory',
  'Adaptive purpose: which allows them to / in order to avoid.',
  [('camouflage','การพรางตัว','/ˈkæməflɑːʒ/','🍃'),('mimicry','การเลียนแบบสิ่งอื่น','/ˈmɪmɪkri/','🎭'),
   ('nocturnal','หากินกลางคืน','/nɒkˈtɜːnl/','🌙'),('echolocation','การหาตำแหน่งด้วยเสียงสะท้อน','/ˌekəʊləʊˈkeɪʃn/','🦇'),
   ('hibernate','จำศีล','/ˈhaɪbəneɪt/','❄️'),('burrow','โพรงใต้ดิน','/ˈbʌrəʊ/','🕳️'),
   ('plumage','ขนนกทั้งชุด','/ˈpluːmɪdʒ/','🦜'),('talon','กรงเล็บนกล่าเหยื่อ','/ˈtælən/','🦅'),
   ('instinct','สัญชาตญาณ','/ˈɪnstɪŋkt/','🧭')],
  "Camouflage works by matching the background and by breaking up an outline. Mimicry lets a harmless insect borrow the reputation of a dangerous one. A nocturnal animal avoids both the heat and most of its predators. Echolocation lets a bat build a picture of a room in complete darkness. To hibernate is to lower the body temperature and wait out the shortage. A deep burrow stays within a few degrees all year. Bright plumage advertises health and attracts exactly the wrong attention. A talon is a tool that a bird cannot put down. Instinct is a behaviour that works the first time it is needed.",
  ["Camouflage works by matching the background and by breaking up an outline.",
   "Mimicry lets a harmless insect borrow the reputation of a dangerous one.",
   "Echolocation lets a bat build a picture of a room in complete darkness.",
   "A deep burrow stays within a few degrees all year.",
   "Instinct is a behaviour that works the first time it is needed."],
  ["Mimicry lets a harmless insect borrow the reputation of a dangerous one.",
   "A deep burrow stays within a few degrees all year.",
   "Instinct is a behaviour that works the first time it is needed."],
  "What is instinct?","A behaviour that works the first time it is needed."),

D(431,430,'Living Together','🤝','Day432_TheWebofEating_B2.html','🕸️','wordsearch',
  'Relationship types: benefits both / harms one / neither is affected.',
  [('symbiosis','การอยู่ร่วมกันของสองสปีชีส์','/ˌsɪmbaɪˈəʊsɪs/','🤝'),('parasite','ปรสิต','/ˈpærəsaɪt/','🪱'),
   ('pollinator','ผู้ผสมเกสร','/ˈpɒləneɪtə(r)/','🐝'),('swarm','ฝูงแมลงจำนวนมาก','/swɔːm/','🦗'),
   ('pheromone','สารเคมีสื่อสาร','/ˈferəməʊn/','💨'),('territory','อาณาเขตหวงห้าม','/ˈterətri/','🚩'),
   ('courtship','พฤติกรรมเกี้ยวพาราสี','/ˈkɔːtʃɪp/','💗'),('imprinting','การจดจำผู้เลี้ยงแรกเกิด','/ˈɪmprɪntɪŋ/','🐣'),
   ('anthill','รังมดใต้ดิน','/ˈænthɪl/','🐜')],
  "Symbiosis covers every arrangement from generous to brutal. A parasite must not kill its host too quickly, or it dies as well. A pollinator is paid in sugar for a delivery it does not understand. A swarm has no leader and still behaves as one animal. An ant follows a pheromone trail laid down by an ant it never met. Defending a territory costs energy and saves fighting later. Courtship displays are honest because they are expensive to fake. Imprinting means a duckling will follow whatever it first sees moving. An anthill makes decisions no single ant could make.",
  ["A parasite must not kill its host too quickly, or it dies as well.",
   "A pollinator is paid in sugar for a delivery it does not understand.",
   "A swarm has no leader and still behaves as one animal.",
   "Defending a territory costs energy and saves fighting later.",
   "An anthill makes decisions no single ant could make."],
  ["A swarm has no leader and still behaves as one animal.",
   "Defending a territory costs energy and saves fighting later.",
   "An anthill makes decisions no single ant could make."],
  "Why must a parasite not kill its host quickly?","Because it dies as well."),

D(432,431,'The Web of Eating','🕸️','Day433_WhenSpeciesDisappear_B2.html','🚨','vowels',
  'Trophic description: feeds on / is preyed upon by / is at the top of.',
  [('herbivore','สัตว์กินพืช','/ˈhɜːbɪvɔː(r)/','🐄'),('carnivore','สัตว์กินเนื้อ','/ˈkɑːnɪvɔː(r)/','🐅'),
   ('omnivore','สัตว์กินทั้งพืชและเนื้อ','/ˈɒmnɪvɔː(r)/','🐗'),('scavenger','สัตว์กินซาก','/ˈskævɪndʒə(r)/','🪰'),
   ('decomposer','ผู้ย่อยสลาย','/ˌdiːkəmˈpəʊzə(r)/','🍄'),('foodweb','สายใยอาหาร','/ˈfuːdweb/','🔗'),
   ('niche','ช่องว่างทางนิเวศ','/niːʃ/','🧩'),('keystone','สปีชีส์หลักค้ำระบบ','/ˈkiːstəʊn/','🗿'),
   ('cascade','ผลกระทบต่อเนื่องเป็นทอด','/kæˈskeɪd/','💦')],
  "A herbivore spends most of its waking life eating, because plants are poor fuel. A carnivore eats rarely and rests a great deal. An omnivore is flexible, which is why humans reached every continent. A scavenger prevents disease by removing what has already died. Without a decomposer the world would be buried in its own dead leaves. A foodweb is more honest than a food chain, because everything eats several things. A niche is not a place; it is a way of making a living. Remove a keystone species and the whole system rearranges itself. That rearrangement is called a trophic cascade.",
  ["A herbivore spends most of its waking life eating.",
   "An omnivore is flexible, which is why humans reached every continent.",
   "Without a decomposer the world would be buried in its own dead leaves.",
   "A niche is not a place; it is a way of making a living.",
   "Remove a keystone species and the whole system rearranges itself."],
  ["Without a decomposer the world would be buried in its own dead leaves.",
   "A niche is not a place; it is a way of making a living.",
   "Remove a keystone species and the whole system rearranges itself."],
  "What is a niche?","It is a way of making a living, not a place."),

D(433,432,'When Species Disappear','🚨','Day434_Week62Review_B2.html','⭐','tiles',
  'Conservation argument: unless action is taken / at the current rate.',
  [('endemic','พบเฉพาะถิ่นเดียว','/enˈdemɪk/','🏝️'),('invasive','สปีชีส์รุกราน','/ɪnˈveɪsɪv/','⚔️'),
   ('fragmentation','การแตกเป็นหย่อมของถิ่นอาศัย','/ˌfræɡmenˈteɪʃn/','🧱'),('linkway','ทางเชื่อมผืนป่า','/ˈlɪŋkweɪ/','🛤️'),
   ('captivebreeding','การเพาะเลี้ยงเพื่อขยายพันธุ์','/ˈkæptɪvˌbriːdɪŋ/','🏛️'),('rewilding','การคืนธรรมชาติสู่พื้นที่','/ˌriːˈwaɪldɪŋ/','🌲'),
   ('genepool','กองพันธุกรรมของประชากร','/ˈdʒiːnpuːl/','🧪'),('inbreeding','การผสมในสายเลือดใกล้','/ˈɪnbriːdɪŋ/','⚠️'),
   ('monitoring','การเฝ้าติดตามประชากร','/ˈmɒnɪtərɪŋ/','🔭')],
  "An endemic species exists in one place and nowhere else on earth. An invasive species arrives without the predators that used to control it. Habitat fragmentation can be as damaging as habitat loss. A wildlife linkway lets a small population stop being small. Captivebreeding is a last resort and has genuinely saved several species. Rewilding returns a missing animal and lets the landscape rebuild itself. A narrow genepool leaves a population unable to answer a new disease. Inbreeding in a tiny group produces problems within a few generations. Long term monitoring is unglamorous and decides which programmes actually worked.",
  ["An endemic species exists in one place and nowhere else on earth.",
   "An invasive species arrives without the predators that used to control it.",
   "A wildlife linkway lets a small population stop being small.",
   "Rewilding returns a missing animal and lets the landscape rebuild itself.",
   "A narrow genepool leaves a population unable to answer a new disease."],
  ["An invasive species arrives without the predators that used to control it.",
   "A wildlife linkway lets a small population stop being small.",
   "A narrow genepool leaves a population unable to answer a new disease."],
  "What is an endemic species?","One that exists in one place and nowhere else."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
