# -*- coding: utf-8 -*-
# Level 10 · B1 · Week 44 Roots & The Wider World (Day 292–297)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level10/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=10, cefr='B1', title=title, emoji=emoji, theme='Roots & World',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(292,291,'Where We Come From','🌳','Day293_CustomsandBeliefs_B1.html','🙏','tiles',
  'Used to and would for the past: my grandmother would tell us stories.',
  [('elder','ผู้อาวุโส','/ˈeldə(r)/','🧓'),('descendant','ลูกหลานสืบสายเลือด','/dɪˈsendənt/','👶'),
   ('kinship','ความเป็นเครือญาติ','/ˈkɪnʃɪp/','🫱'),('clan','ตระกูล','/klæn/','🏯'),
   ('surname','นามสกุล','/ˈsɜːneɪm/','🔤'),('homeland','บ้านเกิดเมืองนอน','/ˈhəʊmlænd/','🗾'),
   ('nostalgia','ความคิดถึงอดีต','/nɒˈstældʒə/','📻'),('belonging','ความรู้สึกเป็นส่วนหนึ่ง','/bɪˈlɒŋɪŋ/','🧩')],
  "In many villages an elder settles arguments without any law. Every descendant carries something forward without choosing to. Kinship is not only blood, it is who shows up. Our clan has kept the same recipe for a hundred years. A surname can tell you where a family once farmed. She left her homeland at nineteen and returned at sixty. Nostalgia makes the past softer than it really was. Belonging is knowing there is a chair for you.",
  ["In many villages an elder settles arguments without any law.",
   "Kinship is not only blood, it is who shows up.",
   "A surname can tell you where a family once farmed.",
   "She left her homeland at nineteen and returned at sixty.",
   "Belonging is knowing there is a chair for you."],
  ["Kinship is not only blood, it is who shows up.",
   "She left her homeland at nineteen and returned at sixty.",
   "Belonging is knowing there is a chair for you."],
  "What is belonging?","Belonging is knowing there is a chair for you."),

D(293,292,'Customs and Beliefs','🙏','Day294_ReadingtheMap_B1.html','🗺️','scramble',
  'Talking about custom: it is customary to / people are expected to.',
  [('etiquette','มารยาทสังคม','/ˈetɪket/','🎩'),('taboo','สิ่งต้องห้าม','/təˈbuː/','⛔'),
   ('superstition','ความเชื่อโชคลาง','/ˌsuːpəˈstɪʃn/','🐈‍⬛'),('pilgrimage','การจาริกแสวงบุญ','/ˈpɪlɡrɪmɪdʒ/','🛕'),
   ('shrine','ศาลเจ้า','/ʃraɪn/','⛩️'),('lunar','เกี่ยวกับดวงจันทร์','/ˈluːnə(r)/','🌙'),
   ('dialect','ภาษาถิ่น','/ˈdaɪəlekt/','💬'),('multicultural','หลากวัฒนธรรม','/ˌmʌltiˈkʌltʃərəl/','🌐')],
  "Table etiquette changes the moment you cross a border. What is polite here may be taboo one country away. Every culture keeps one superstition it laughs about and still obeys. A pilgrimage is measured in days, not kilometres. People leave flowers at the small shrine each morning. The lunar new year moves every year. A dialect is a language that lost an argument. A multicultural city argues more and learns faster.",
  ["Table etiquette changes the moment you cross a border.",
   "What is polite here may be taboo one country away.",
   "A pilgrimage is measured in days, not kilometres.",
   "People leave flowers at the small shrine each morning.",
   "The lunar new year moves every year."],
  ["What is polite here may be taboo one country away.",
   "People leave flowers at the small shrine each morning.",
   "The lunar new year moves every year."],
  "How is a pilgrimage measured?","It is measured in days, not kilometres."),

D(294,293,'Reading the Map','🗺️','Day295_LandandWater_B1.html','🏔️','memory',
  'Location and measurement: lies at / rises to / stretches from.',
  [('latitude','เส้นรุ้ง','/ˈlætɪtjuːd/','↔️'),('longitude','เส้นแวง','/ˈlɒŋɡɪtjuːd/','↕️'),
   ('hemisphere','ซีกโลก','/ˈhemɪsfɪə(r)/','🌗'),('equator','เส้นศูนย์สูตร','/ɪˈkweɪtə(r)/','🌍'),
   ('tropic','เขตร้อน','/ˈtrɒpɪk/','☀️'),('timezone','เขตเวลา','/ˈtaɪmzəʊn/','🕰️'),
   ('altitude','ความสูงจากระดับน้ำทะเล','/ˈæltɪtjuːd/','⛰️'),('terrain','ลักษณะภูมิประเทศ','/təˈreɪn/','🧭')],
  "Latitude tells you how hot a place is likely to be. Longitude tells you what time it is there. The southern hemisphere has summer in December. Countries on the equator have no real winter. Thailand sits inside the tropic zone. One country can hold five timezone lines. At high altitude water boils below one hundred degrees. Rough terrain slows an army more than any wall.",
  ["Latitude tells you how hot a place is likely to be.",
   "The southern hemisphere has summer in December.",
   "Countries on the equator have no real winter.",
   "At high altitude water boils below one hundred degrees.",
   "Rough terrain slows an army more than any wall."],
  ["The southern hemisphere has summer in December.",
   "Countries on the equator have no real winter.",
   "Rough terrain slows an army more than any wall."],
  "When is summer in the southern hemisphere?","Summer is in December."),

D(295,294,'Land and Water','🏔️','Day296_HotPlacesColdPlaces_B1.html','❄️','wordsearch',
  'Defining geography: a narrow strip of land which joins two seas.',
  [('peninsula','คาบสมุทร','/pəˈnɪnsjələ/','🗺️'),('archipelago','หมู่เกาะ','/ˌɑːkɪˈpeləɡəʊ/','🏝️'),
   ('canyon','หุบเขาลึก','/ˈkænjən/','🪨'),('glacier','ธารน้ำแข็ง','/ˈɡlæsiə(r)/','🧊'),
   ('delta','สามเหลี่ยมปากแม่น้ำ','/ˈdeltə/','🔺'),('estuary','ปากแม่น้ำ','/ˈestʃuəri/','🌊'),
   ('reef','แนวปะการัง','/riːf/','🐠'),('dune','เนินทราย','/djuːn/','🏜️')],
  "A peninsula has water on three sides and a road on the fourth. An archipelago can hold seventeen thousand islands. The river cut this canyon over two million years. A glacier moves so slowly that it looks asleep. Rice grows well in a river delta. Salt and fresh water meet in the estuary. One reef can shelter a quarter of all sea life. The wind rebuilds every dune each night.",
  ["A peninsula has water on three sides.",
   "An archipelago can hold seventeen thousand islands.",
   "A glacier moves so slowly that it looks asleep.",
   "Salt and fresh water meet in the estuary.",
   "The wind rebuilds every dune each night."],
  ["An archipelago can hold seventeen thousand islands.",
   "A glacier moves so slowly that it looks asleep.",
   "The wind rebuilds every dune each night."],
  "How many sides of a peninsula have water?","Three sides have water."),

D(296,295,'Hot Places, Cold Places','❄️','Day297_OntheRoad_B1.html','🎒','vowels',
  'Extremes: barely / hardly ever / almost never.',
  [('tundra','ทุ่งทุนดรา','/ˈtʌndrə/','🐻‍❄️'),('savannah','ทุ่งหญ้าสะวันนา','/səˈvænə/','🦁'),
   ('oasis','โอเอซิส','/əʊˈeɪsɪs/','🌴'),('crater','ปากปล่องภูเขาไฟ','/ˈkreɪtə(r)/','🌋'),
   ('fjord','อ่าวฟยอร์ด','/fiːɔːd/','⛵'),('trek','เดินป่าไกล','/trek/','🥾'),
   ('wander','เดินเรื่อยเปื่อย','/ˈwɒndə(r)/','🚶'),('roam','ท่องไปทั่ว','/rəʊm/','🐘')],
  "Nothing tall grows on the tundra. On the savannah the grass is taller than a child. An oasis is proof that water hides below the sand. This crater filled with rainwater and became a lake. A fjord is a valley the sea walked into. The trek to the village takes two days on foot. It is good to wander with no plan sometimes. Elephants roam further than any fence should allow.",
  ["Nothing tall grows on the tundra.",
   "On the savannah the grass is taller than a child.",
   "An oasis is proof that water hides below the sand.",
   "The trek to the village takes two days on foot.",
   "It is good to wander with no plan sometimes."],
  ["On the savannah the grass is taller than a child.",
   "The trek to the village takes two days on foot.",
   "It is good to wander with no plan sometimes."],
  "How long does the trek to the village take?","It takes two days on foot."),

D(297,296,'On the Road','🎒','Day298_Week44Review_B1.html','⭐','tiles',
  'Regret and hindsight: I wish I had / if only we had.',
  [('hostel','ที่พักราคาประหยัด','/ˈhɒstl/','🛏️'),('guidebook','หนังสือนำเที่ยว','/ˈɡaɪdbʊk/','📕'),
   ('phrasebook','หนังสือรวมประโยคพูด','/ˈfreɪzbʊk/','🗣️'),('jetlag','อาการเพลียจากต่างเวลา','/ˈdʒetlæɡ/','😴'),
   ('bilingual','พูดได้สองภาษา','/baɪˈlɪŋɡwəl/','🔀'),('detour','ทางอ้อม','/ˈdiːtʊə(r)/','↩️'),
   ('stopover','การแวะพัก','/ˈstɒpəʊvə(r)/','✈️'),('sightseeing','การเที่ยวชมสถานที่','/ˈsaɪtsiːɪŋ/','📸')],
  "A hostel costs less and teaches more. Read the guidebook on the plane, not in the street. A cheap phrasebook opens more doors than a full wallet. Jetlag is worse going east than going west. Every bilingual child has two ways of thinking. The best day of the trip was an accidental detour. We had a nine hour stopover and saw the whole old town. Sightseeing is not the same as seeing.",
  ["A hostel costs less and teaches more.",
   "Read the guidebook on the plane, not in the street.",
   "Jetlag is worse going east than going west.",
   "The best day of the trip was an accidental detour.",
   "Sightseeing is not the same as seeing."],
  ["Read the guidebook on the plane, not in the street.",
   "Jetlag is worse going east than going west.",
   "Sightseeing is not the same as seeing."],
  "When is jetlag worse?","It is worse going east than going west."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn)
