# -*- coding: utf-8 -*-
# Level 15 · B2 · Week 63 Materials & Making (Day 435–440) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level15/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=15, cefr='B2', title=title, emoji=emoji, theme='Materials & Making',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(435,434,'What Things Are Made Of','🧱','Day436_ShapingMetal_B2.html','🔨','tiles',
  'Property description: is prized for / suffers from / performs well under.',
  [('alloy','โลหะผสม','/ˈælɔɪ/','⚗️'),('polymer','พอลิเมอร์','/ˈpɒlɪmə(r)/','🧵'),
   ('composite','วัสดุผสม','/ˈkɒmpəzɪt/','🧩'),('carbonfibre','คาร์บอนไฟเบอร์','/ˈkɑːbənfaɪbə(r)/','🏎️'),
   ('elasticity','ความยืดหยุ่น','/ˌiːlæˈstɪsəti/','🪀'),('brittle','เปราะแตกง่าย','/ˈbrɪtl/','🥀'),
   ('ductile','ดึงเป็นเส้นได้','/ˈdʌktaɪl/','🪝'),('malleable','ตีแผ่เป็นแผ่นได้','/ˈmæliəbl/','🔨'),
   ('durability','ความทนทาน','/ˌdjʊərəˈbɪləti/','🛡️')],
  "An alloy is a mixture that behaves better than either metal alone. A polymer is a very long molecule repeated thousands of times. A composite combines two materials so that each covers the other's weakness. Carbonfibre is lighter than aluminium and stiffer than steel, and costly. Elasticity means a material returns to its shape after the load is removed. Glass is strong and brittle, which is a dangerous combination. A ductile metal can be drawn into wire without snapping. Gold is so malleable that one gram covers half a square metre. Durability is worth more than strength in almost every everyday object.",
  ["An alloy is a mixture that behaves better than either metal alone.",
   "A composite combines two materials so that each covers the other's weakness.",
   "Elasticity means a material returns to its shape after the load is removed.",
   "Glass is strong and brittle, which is a dangerous combination.",
   "Durability is worth more than strength in almost every everyday object."],
  ["An alloy behaves better than either metal alone.",
   "Elasticity means a material returns to its shape after the load is removed.",
   "Durability is worth more than strength in everyday objects."],
  "What does elasticity mean?","A material returns to its shape after the load is removed."),

D(436,435,'Shaping Metal','🔨','Day437_ThreadandCloth_B2.html','🧶','scramble',
  'Process passives: is heated until / is then cooled slowly.',
  [('forge','ตีขึ้นรูปโลหะ','/fɔːdʒ/','⚒️'),('weld','เชื่อมโลหะ','/weld/','⚡'),
   ('solder','บัดกรี','/ˈsəʊldə(r)/','🔌'),('anneal','อบอ่อนโลหะ','/əˈniːl/','♨️'),
   ('corrode','กัดกร่อน','/kəˈrəʊd/','🟫'),('galvanise','ชุบสังกะสีกันสนิม','/ˈɡælvənaɪz/','🪣'),
   ('lathe','เครื่องกลึง','/leɪð/','⚙️'),('kiln','เตาเผา','/kɪln/','🔥'),
   ('extrude','อัดรีดขึ้นรูป','/ɪkˈstruːd/','🍝')],
  "To forge metal is to shape it while it is hot enough to move. A weld joins two pieces by melting them into each other. Solder melts at a low temperature and joins without melting the parts. To anneal a metal is to heat it and cool it slowly so it stops being brittle. Iron will corrode wherever water and air meet it. Galvanised steel does not rust because the zinc corrodes instead. A lathe spins the work and holds the tool still. A pottery kiln reaches a temperature that changes clay permanently. To extrude aluminium is to squeeze it through a shaped hole like toothpaste.",
  ["To forge metal is to shape it while it is hot enough to move.",
   "Solder melts at a low temperature and joins without melting the parts.",
   "Iron will corrode wherever water and air meet it.",
   "Galvanised steel does not rust because the zinc corrodes instead.",
   "A lathe spins the work and holds the tool still."],
  ["Solder melts at a low temperature and joins without melting the parts.",
   "Galvanised steel does not rust because the zinc corrodes instead.",
   "A lathe spins the work and holds the tool still."],
  "Why does galvanised steel not rust?","Because the zinc corrodes instead."),

D(437,436,'Thread and Cloth','🧶','Day438_MakingaGarment_B2.html','👗','memory',
  'Material comparison: unlike cotton / whereas wool / in contrast to.',
  [('textile','สิ่งทอ','/ˈtekstaɪl/','👚'),('loom','กี่ทอผ้า','/luːm/','🪡'),
   ('spindle','แกนปั่นด้าย','/ˈspɪndl/','🌀'),('synthetic','เส้นใยสังเคราะห์','/sɪnˈθetɪk/','🧪'),
   ('breathable','ระบายอากาศได้','/ˈbriːðəbl/','💨'),('waterproof','กันน้ำ','/ˈwɔːtəpruːf/','☔'),
   ('dyeing','การย้อมสี','/ˈdaɪɪŋ/','🎨'),('tanning','การฟอกหนัง','/ˈtænɪŋ/','🐄'),
   ('crease','รอยยับ','/kriːs/','📄')],
  "The textile industry was the first to be mechanised anywhere. A loom holds one set of threads still and passes another set through. A spindle twists loose fibre into thread strong enough to pull. A synthetic fibre is cheap, strong and does not decay for centuries. Wool is breathable and stays warm even when it is damp. A waterproof jacket that is not breathable will soak you from the inside. Dyeing uses enormous quantities of water and is being redesigned. Leather tanning is ancient, effective and among the most polluting crafts there is. Linen creases beautifully, which is a polite way of saying it creases.",
  ["The textile industry was the first to be mechanised anywhere.",
   "A spindle twists loose fibre into thread strong enough to pull.",
   "Wool is breathable and stays warm even when it is damp.",
   "A waterproof jacket that is not breathable will soak you from the inside.",
   "Dyeing uses enormous quantities of water."],
  ["A spindle twists loose fibre into thread strong enough to pull.",
   "Wool is breathable and stays warm even when it is damp.",
   "Dyeing uses enormous quantities of water."],
  "What happens in a waterproof jacket that cannot breathe?","It will soak you from the inside."),

D(438,437,'Making a Garment','👗','Day439_TheCostofFashion_B2.html','🏷️','wordsearch',
  'Instruction sequence: cut along / press flat / stitch through both layers.',
  [('garment','เสื้อผ้าสำเร็จ','/ˈɡɑːmənt/','👕'),('seam','ตะเข็บ','/siːm/','➖'),
   ('hem','ชายผ้าพับเย็บ','/hem/','📏'),('lining','ผ้าซับใน','/ˈlaɪnɪŋ/','🧥'),
   ('bespoke','ตัดตามสั่งเฉพาะคน','/bɪˈspəʊk/','🎩'),('couture','แฟชั่นชั้นสูง','/kuːˈtjʊə(r)/','💎'),
   ('mending','การซ่อมเสื้อผ้า','/ˈmendɪŋ/','🧷'),('launder','ซักรีด','/ˈlɔːndə(r)/','🧼'),
   ('craftsmanship','ฝีมือช่าง','/ˈkrɑːftsmənʃɪp/','🏅')],
  "A garment is judged from the inside, where nobody is looking. A straight seam is harder than it sounds and impossible to hide. A good hem hangs level even when the wearer moves. A lining makes a jacket comfortable and doubles the work of making it. A bespoke suit is cut for one body and fits no other. Couture is made entirely by hand and priced accordingly. Ten minutes of mending saves a shirt for another two years. Wash less, launder gently, and clothes last three times longer. Craftsmanship is visible in the parts nobody photographs.",
  ["A garment is judged from the inside, where nobody is looking.",
   "A good hem hangs level even when the wearer moves.",
   "A bespoke suit is cut for one body and fits no other.",
   "Ten minutes of mending saves a shirt for another two years.",
   "Craftsmanship is visible in the parts nobody photographs."],
  ["A garment is judged from the inside, where nobody is looking.",
   "Ten minutes of mending saves a shirt for another two years.",
   "Craftsmanship is visible in the parts nobody photographs."],
  "Where is a garment judged from?","From the inside, where nobody is looking."),

D(439,438,'The Cost of Fashion','🏷️','Day440_ThingsThatLast_B2.html','♻️','vowels',
  'Ethical argument: at whose expense / who ultimately pays.',
  [('fastfashion','แฟชั่นผลิตเร็วราคาถูก','/ˈfɑːstfæʃn/','⏩'),('readytowear','เสื้อผ้าสำเร็จรูป','/ˌredɪtəˈweə(r)/','🛍️'),
   ('secondhand','มือสอง','/ˌsekəndˈhænd/','🔁'),('upcycle','แปลงของเก่าให้มีค่าขึ้น','/ˈʌpsaɪkl/','✨'),
   ('microfibre','เส้นใยจิ๋วที่หลุดจากผ้า','/ˈmaɪkrəʊfaɪbə(r)/','🧫'),('overproduction','การผลิตล้นเกิน','/ˌəʊvəprəˈdʌkʃn/','📦'),
   ('supplier','ผู้ผลิตต้นทาง','/səˈplaɪə(r)/','🏭'),('audit','การตรวจสอบโรงงาน','/ˈɔːdɪt/','🔍'),
   ('livingwage','ค่าจ้างที่พอเลี้ยงชีพ','/ˈlɪvɪŋweɪdʒ/','💵')],
  "Fastfashion sells fifty collections a year and expects none of them to last. Readytowear democratised clothing and standardised bodies at the same time. Buying secondhand is the single largest reduction most wardrobes can make. To upcycle is to make something more valuable, not merely to reuse it. Every wash releases microfibre plastic into the water system. Overproduction, not underselling, is the industry's real waste problem. A brand often does not know who its third supplier is. An unannounced audit finds what an announced one never will. A livingwage is not a minimum wage; it is what a family actually needs.",
  ["Fastfashion sells fifty collections a year.",
   "Buying secondhand is the single largest reduction most wardrobes can make.",
   "To upcycle is to make something more valuable, not merely to reuse it.",
   "An unannounced audit finds what an announced one never will.",
   "A livingwage is not a minimum wage; it is what a family actually needs."],
  ["Buying secondhand is the largest reduction most wardrobes can make.",
   "An unannounced audit finds what an announced one never will.",
   "A livingwage is what a family actually needs."],
  "What does an unannounced audit find?","What an announced one never will."),

D(440,439,'Things That Last','♻️','Day441_Week63Review_B2.html','⭐','tiles',
  'Design principle: is built to be / is designed for / can be taken apart.',
  [('repairable','ซ่อมได้','/rɪˈpeərəbl/','🔧'),('modularity','การออกแบบเป็นหน่วยถอดได้','/ˌmɒdjuˈlærəti/','🔲'),
   ('sparepart','อะไหล่','/ˈspeəpɑːt/','🔩'),('obsolescence','ความล้าสมัยที่ตั้งใจให้เกิด','/ˌɒbsəˈlesns/','⏳'),
   ('recyclable','นำกลับมาใช้ใหม่ได้','/ˌriːˈsaɪkləbl/','♻️'),('biodegrade','ย่อยสลายทางชีวภาพ','/ˌbaɪəʊdɪˈɡreɪd/','🍂'),
   ('lifecycle','วงจรชีวิตของผลิตภัณฑ์','/ˈlaɪfsaɪkl/','🔄'),('provenance','แหล่งที่มาที่ตรวจสอบได้','/ˈprɒvənəns/','🗺️'),
   ('memento','ของที่เก็บไว้เตือนความทรงจำ','/məˈmentəʊ/','🕰️')],
  "A repairable product is a decision made at the design stage, not later. Modularity means one broken part does not condemn the whole object. If no sparepart exists, the product was designed to be thrown away. Planned obsolescence is legal in most countries and increasingly unpopular. Recyclable is not the same as recycled; one is a hope and one is a fact. Very few plastics genuinely biodegrade in ordinary conditions. A lifecycle assessment counts the energy from mining to disposal. Clear provenance tells you where a material came from and who handled it. A memento is simply an object somebody chose to repair.",
  ["A repairable product is a decision made at the design stage.",
   "Modularity means one broken part does not condemn the whole object.",
   "Recyclable is not the same as recycled.",
   "A lifecycle assessment counts the energy from mining to disposal.",
   "A memento is simply an object somebody chose to repair."],
  ["Modularity means one broken part does not condemn the whole object.",
   "Recyclable is not the same as recycled.",
   "A memento is simply an object somebody chose to repair."],
  "What is a memento?","An object somebody chose to repair."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
