# -*- coding: utf-8 -*-
# Level 7 · B1 · Week 32 Digital & Giving Back (202–208) + 209–210 จบ Level 7
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level7/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta, theme='Digital'):
    return dict(n=n, prev=prev, level=7, cefr='B1', title=title, emoji=emoji, theme=theme,
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(202,201,'The Digital World','💻','Day203_LearningToCode_B1.html','⌨️','tiles',
  'Comparatives of quantity: more / fewer / less.',
  [('digital','ดิจิทัล','/ˈdɪdʒɪtl/','💠'),('software','ซอฟต์แวร์','/ˈsɒftweə(r)/','🧩'),
   ('hardware','ฮาร์ดแวร์','/ˈhɑːdweə(r)/','🖥️'),('network','เครือข่าย','/ˈnetwɜːk/','🕸️'),
   ('database','ฐานข้อมูล','/ˈdeɪtəbeɪs/','🗄️'),('virtual','เสมือนจริง','/ˈvɜːtʃuəl/','🥽'),
   ('website','เว็บไซต์','/ˈwebsaɪt/','🏗️'),('access','เข้าถึง','/ˈækses/','🔓')],
  "We live in a digital age that changes every year. Software is the set of instructions a computer follows. Hardware is the part you can actually touch. A network connects millions of machines together. A school database stores fewer records than a bank. Virtual classrooms let students join from far away. Anyone with a phone can now access a learning website.",
  ["We live in a digital age that changes every year.",
   "Software is the set of instructions a computer follows.",
   "A network connects millions of machines together.",
   "Virtual classrooms let students join from far away.",
   "Anyone with a phone can access a learning website."],
  ["Software is the set of instructions a computer follows.",
   "A network connects millions of machines together.",
   "Anyone with a phone can access a learning website."],
  "What is hardware?","Hardware is the part you can actually touch."),

D(203,202,'Learning to Code','⌨️','Day204_SmartMachines_B1.html','🤖','scramble',
  'Sequencing in instructions: first, then, after that, finally.',
  [('coding','การเขียนโปรแกรม','/ˈkəʊdɪŋ/','👨‍💻'),('algorithm','อัลกอริทึม','/ˈælɡərɪðəm/','🔢'),
   ('command','คำสั่ง','/kəˈmɑːnd/','▶️'),('loop','การวนซ้ำ','/luːp/','🔁'),
   ('debug','แก้จุดบกพร่อง','/ˌdiːˈbʌɡ/','🐞'),('logical','เป็นเหตุเป็นผล','/ˈlɒdʒɪkl/','🧠'),
   ('output','ผลลัพธ์ที่ได้','/ˈaʊtpʊt/','📤'),('sequence','ลำดับขั้น','/ˈsiːkwəns/','🔗')],
  "Coding is simply giving a machine clear instructions. An algorithm is a recipe written in a logical sequence. First you type a command, then the computer runs it. A loop repeats the same step many times. When something goes wrong you must debug the program. Check the output carefully after every change. Anyone patient enough can learn to code.",
  ["Coding is simply giving a machine clear instructions.",
   "An algorithm is a recipe written in a logical sequence.",
   "A loop repeats the same step many times.",
   "When something goes wrong you must debug the program.",
   "Anyone patient enough can learn to code."],
  ["An algorithm is a recipe written in a logical sequence.",
   "A loop repeats the same step many times.",
   "Anyone patient enough can learn to code."],
  "What is an algorithm?","It is a recipe written in a logical sequence."),

D(204,203,'Smart Machines','🤖','Day205_GivingBackAgain_B1.html','🤲','memory',
  'Predictions with will / might: Robots will do more of the heavy work.',
  [('artificial','ประดิษฐ์ขึ้น','/ˌɑːtɪˈfɪʃl/','🧠'),('automation','ระบบอัตโนมัติ','/ˌɔːtəˈmeɪʃn/','⚙️'),
   ('innovate','สร้างนวัตกรรม','/ˈɪnəveɪt/','💡'),('replace','แทนที่','/rɪˈpleɪs/','🔄'),
   ('collaborate','ทำงานร่วมกัน','/kəˈlæbəreɪt/','🫱'),('ethical','มีจริยธรรม','/ˈeθɪkl/','⚖️'),
   ('rely','พึ่งพา','/rɪˈlaɪ/','🪝'),('opportunity','โอกาส','/ˌɒpəˈtjuːnəti/','🚪')],
  "Artificial intelligence can already read and write. Automation will replace some simple jobs in factories. But new opportunity will appear at the same time. Machines collaborate with doctors instead of replacing them. Companies must innovate in an ethical way. We should not rely on technology for every decision. The future belongs to people who keep learning.",
  ["Artificial intelligence can already read and write.",
   "Automation will replace some simple jobs.",
   "New opportunity will appear at the same time.",
   "Companies must innovate in an ethical way.",
   "The future belongs to people who keep learning."],
  ["Automation will replace some simple jobs.",
   "Companies must innovate in an ethical way.",
   "The future belongs to people who keep learning."],
  "What will appear at the same time?","New opportunity will appear."),

D(205,204,'Giving Back Again','🤲','Day206_LeadTheWay_B1.html','🚩','wordsearch',
  'Purpose clauses: in order to / so that.',
  [('contribute','มีส่วนร่วม','/kənˈtrɪbjuːt/','🧱'),('fundraise','ระดมทุน','/ˈfʌndreɪz/','💰'),
   ('participant','ผู้เข้าร่วม','/pɑːˈtɪsɪpənt/','🙋'),('organise','จัดการ','/ˈɔːɡənaɪz/','📋'),
   ('cause','จุดมุ่งหมายเพื่อสังคม','/kɔːz/','🎗️'),('impactful','มีผลกระทบสูง','/ɪmˈpæktfl/','💥'),
   ('generosity','ความเอื้อเฟื้อ','/ˌdʒenəˈrɒsəti/','💞'),('selfless','ไม่เห็นแก่ตัว','/ˈselfləs/','🕊️')],
  "The students decided to contribute their Saturday morning. They wanted to fundraise for a village library. Each participant walked five kilometres. Mimi helped organise the route and the water stations. It is a cause that everyone believed in. A small group can be surprisingly impactful. Selfless work spreads generosity on both sides.",
  ["The students decided to contribute their Saturday morning.",
   "They wanted to fundraise for a village library.",
   "Each participant walked five kilometres.",
   "It is a cause that everyone believed in.",
   "A small group can be surprisingly impactful."],
  ["They wanted to fundraise for a village library.",
   "Each participant walked five kilometres.",
   "A small group can be surprisingly impactful."],
  "What did they want to fundraise for?","For a village library."),

D(206,205,'Lead the Way','🚩','Day207_Week32Review_B1.html','⭐','vowels',
  'Advice with should / ought to / had better.',
  [('leadership','ภาวะผู้นำ','/ˈliːdəʃɪp/','🚩'),('initiative','ความคิดริเริ่ม','/ɪˈnɪʃətɪv/','🌟'),
   ('motivating','สร้างแรงจูงใจ','/ˈməʊtɪveɪtɪŋ/','📣'),('modesty','ความถ่อมตน','/ˈmɒdɪsti/','🌾'),
   ('accountable','รับผิดชอบผลลัพธ์','/əˈkaʊntəbl/','📌'),('vision','วิสัยทัศน์','/ˈvɪʒn/','🔭'),
   ('example','แบบอย่าง','/ɪɡˈzɑːmpl/','👣'),('empower','เสริมพลังให้ผู้อื่น','/ɪmˈpaʊə(r)/','⚡')],
  "Leadership is not about giving orders all day. Mimi showed initiative when nobody else volunteered. A good leader is quietly motivating. Modesty means you listen before speaking. When a plan fails, be accountable instead of blaming others. Share your vision so that everyone understands the goal. Lead by example and empower the people around you.",
  ["Leadership is not about giving orders all day.",
   "Mimi showed initiative when nobody else volunteered.",
   "Modesty means you listen before speaking.",
   "When a plan fails, be accountable instead of blaming others.",
   "Lead by example and empower the people around you."],
  ["Mimi showed initiative when nobody else volunteered.",
   "When a plan fails, be accountable instead of blaming others.",
   "Lead by example and empower the people around you."],
  "What did Mimi show?","She showed initiative when nobody else volunteered."),

D(208,207,'One Thousand Words','🏆','Day209_ReadyForMore_B1.html','🚀','tiles',
  'Reviewing tenses: past, present, future in one paragraph.',
  [('accomplish','ทำสำเร็จ','/əˈkʌmplɪʃ/','🎯'),('threshold','จุดเริ่มต้นใหม่','/ˈθreʃhəʊld/','🚪'),
   ('revise','ทบทวน','/rɪˈvaɪz/','🔁'),('steadily','อย่างสม่ำเสมอ','/ˈstedɪli/','📶'),
   ('capable','มีความสามารถ','/ˈkeɪpəbl/','💪'),('proficiency','ความชำนาญ','/prəˈfɪʃnsi/','📜'),
   ('pathway','เส้นทาง','/ˈpɑːθweɪ/','🪞'),('onwards','ต่อไปข้างหน้า','/ˈɒnwədz/','🔭')],
  "Two hundred days ago you knew only a handful of words. You have now accomplish something real and lasting. Revise the old lists and you will see how far you came. Progress arrives steadily, not suddenly. You are capable of far more than you think. Real proficiency grows from daily practice. You are standing on the threshold of B2. Look at your pathway for a moment, then keep moving onwards.",
  ["Two hundred days ago you knew only a handful of words.",
   "You have now accomplish something real and lasting.",
   "Progress arrives steadily, not suddenly.",
   "You are capable of far more than you think.",
   "Real proficiency grows from daily practice."],
  ["Progress arrives steadily, not suddenly.",
   "You are capable of far more than you think.",
   "Real proficiency grows from daily practice."],
  "How does progress arrive?","It arrives steadily, not suddenly.", 'Special'),

D(209,208,'Ready For More','🚀','../dashboard.html','🏠','memory',
  'Looking ahead to B2: longer texts, opinion essays, natural speed listening.',
  [('advanced','ระดับสูง','/ədˈvɑːnst/','📈'),('complexity','ความซับซ้อน','/kəmˈpleksəti/','🧗'),
   ('nuance','ความละเอียดอ่อนของภาษา','/ˈnjuːɑːns/','🎚️'),('idiom','สำนวน','/ˈɪdiəm/','🗯️'),
   ('argument','การให้เหตุผล','/ˈɑːɡjumənt/','⚔️'),('essay','เรียงความ','/ˈeseɪ/','📝'),
   ('persevere','พากเพียร','/ˌpɜːsɪˈvɪə(r)/','🔥'),('mastery','ความเชี่ยวชาญ','/ˈmɑːstəri/','🌠')],
  "At the advanced level English becomes more natural. You will meet more complexity in every lesson. Native speakers use nuance that a dictionary cannot explain. An idiom like break the ice has a hidden meaning. You will build a real argument and write your first essay. Those who persevere reach fluency. Keep going and mastery of the whole language opens up!",
  ["At the advanced level English becomes more natural.",
   "You will meet more complexity in every lesson.",
   "An idiom like break the ice has a hidden meaning.",
   "You will write your first essay.",
   "Those who persevere reach fluency."],
  ["At the advanced level English becomes more natural.",
   "An idiom like break the ice has a hidden meaning.",
   "Those who persevere reach fluency."],
  "What do those who persevere reach?","They reach fluency.", 'Special'),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']),'คำ')

# ── Day 210 — วันสุดท้ายของ Level 7 ──
D210 = D(210,209,'The Next Chapter','📘','../dashboard.html','🏠','scramble',
  'Mixed review: put past, present and future together in one story.',
  [('consistent','สม่ำเสมอ','/kənˈsɪstənt/','📅'),('breakthrough','ความก้าวกระโดด','/ˈbreɪkθruː/','💥'),
   ('momentum','แรงส่ง','/məˈmentəm/','🌀'),('determined','มุ่งมั่น','/dɪˈtɜːmɪnd/','🔥'),
   ('stamina','ความอึด','/ˈstæmɪnə/','🏃'),('ultimate','สูงสุด','/ˈʌltɪmət/','👑'),
   ('proudly','อย่างภาคภูมิ','/ˈpraʊdli/','🎁'),('renew','เริ่มใหม่','/rɪˈnjuː/','📘')],
  "Consistent practice beats a sudden burst of effort. Last month Ben had a real breakthrough with listening. Once you build momentum, learning feels lighter. A determined learner keeps going on tired days. Language study needs stamina, like a long run. The ultimate goal is to think in English. Close this chapter proudly and renew your promise tomorrow.",
  ["Consistent practice beats a sudden burst of effort.",
   "Ben had a real breakthrough with listening.",
   "Once you build momentum, learning feels lighter.",
   "Language study needs stamina, like a long run.",
   "The ultimate goal is to think in English."],
  ["Ben had a real breakthrough with listening.",
   "Once you build momentum, learning feels lighter.",
   "The ultimate goal is to think in English."],
  "What is the ultimate goal?","The ultimate goal is to think in English.", 'Special')
out = build(D210)
open(OUT+'Day210_TheNextChapter_B1.html','w',encoding='utf-8').write(out)
print('OK Day210_TheNextChapter_B1.html 8 คำ')
