# -*- coding: utf-8 -*-
# Level 10 · B1 · Week 41 Food & Farming (Day 271–276)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level10/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=10, cefr='B1', title=title, emoji=emoji, theme='Food & Farming',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(271,270,'On the Farm','🌾','Day272_GrowingEnoughFood_B1.html','🌱','tiles',
  'Sequence in a process: first, then, after that, finally.',
  [('harvest','การเก็บเกี่ยว','/ˈhɑːvɪst/','🌾'),('cultivate','เพาะปลูก','/ˈkʌltɪveɪt/','🧑‍🌾'),
   ('plough','ไถดิน','/plaʊ/','⛏️'),('sow','หว่านเมล็ด','/səʊ/','🫘'),
   ('reap','เกี่ยวข้าว','/riːp/','🌿'),('barn','ยุ้งฉาง','/bɑːn/','🏚️'),
   ('tractor','รถแทรกเตอร์','/ˈtræktə(r)/','🚜'),('pasture','ทุ่งหญ้าเลี้ยงสัตว์','/ˈpɑːstʃə(r)/','🟩')],
  "The harvest is the end of a long year. Farmers cultivate the same field for many seasons. First they plough the hard ground. Then they sow the seed in straight lines. Months later they reap what they planted. The barn is full by October. One tractor does the work of twenty people. Beyond the fence, cows rest in the wide pasture.",
  ["The harvest is the end of a long year.",
   "First they plough the hard ground.",
   "Then they sow the seed in straight lines.",
   "Months later they reap what they planted.",
   "One tractor does the work of twenty people."],
  ["First they plough the hard ground.",
   "Months later they reap what they planted.",
   "One tractor does the work of twenty people."],
  "What do farmers do first?","First they plough the hard ground."),

D(272,271,'Growing Enough Food','🌱','Day273_AnimalsandBees_B1.html','🐝','scramble',
  'Cause and effect: because of / as a result / which means that.',
  [('irrigation','การชลประทาน','/ˌɪrɪˈɡeɪʃn/','🚿'),('fertiliser','ปุ๋ย','/ˈfɜːtəlaɪzə(r)/','🧪'),
   ('pesticide','ยาฆ่าแมลง','/ˈpestɪsaɪd/','🚫'),('compost','ปุ๋ยหมัก','/ˈkɒmpɒst/','🪱'),
   ('weed','วัชพืช','/wiːd/','🥀'),('greenhouse','เรือนกระจก','/ˈɡriːnhaʊs/','🏠'),
   ('yield','ผลผลิตที่ได้','/jiːld/','📊'),('orchard','สวนผลไม้','/ˈɔːtʃəd/','🍎')],
  "Good irrigation matters more than rain in a dry year. Too much fertiliser harms the river below the field. A strong pesticide kills useful insects as well as pests. Compost turns kitchen waste into free food for plants. Pull every weed while it is still small. Inside a greenhouse the season lasts all year. A higher yield is not always healthier food. The old orchard still gives fruit every August.",
  ["Good irrigation matters more than rain in a dry year.",
   "Too much fertiliser harms the river below the field.",
   "Compost turns kitchen waste into free food for plants.",
   "Pull every weed while it is still small.",
   "A higher yield is not always healthier food."],
  ["Compost turns kitchen waste into free food for plants.",
   "Pull every weed while it is still small.",
   "A higher yield is not always healthier food."],
  "When should you pull a weed?","While it is still small."),

D(273,272,'Animals and Bees','🐝','Day274_FromFarmtoShop_B1.html','🚚','memory',
  'Quantifiers: a great deal of / a large number of / plenty of.',
  [('livestock','ปศุสัตว์','/ˈlaɪvstɒk/','🐄'),('poultry','สัตว์ปีกเลี้ยง','/ˈpəʊltri/','🐔'),
   ('dairy','ผลิตภัณฑ์นม','/ˈdeəri/','🥛'),('graze','เล็มหญ้า','/ɡreɪz/','🐑'),
   ('herd','ฝูงสัตว์ใหญ่','/hɜːd/','🐂'),('flock','ฝูงนกหรือแกะ','/flɒk/','🦆'),
   ('hive','รังผึ้ง','/haɪv/','🍯'),('pollinate','ผสมเกสร','/ˈpɒləneɪt/','🌼')],
  "Livestock needs water before it needs anything else. The poultry shed is cleaned twice a day. A small dairy farm sells milk to the village. The sheep graze from morning until dusk. A herd of cattle moves slowly across the hill. A flock of ducks follows the youngest child. One hive holds fifty thousand bees. Without bees to pollinate them, most fruit trees give nothing.",
  ["Livestock needs water before it needs anything else.",
   "A small dairy farm sells milk to the village.",
   "The sheep graze from morning until dusk.",
   "A herd of cattle moves slowly across the hill.",
   "One hive holds fifty thousand bees."],
  ["A small dairy farm sells milk to the village.",
   "The sheep graze from morning until dusk.",
   "One hive holds fifty thousand bees."],
  "What happens without bees to pollinate the trees?","Most fruit trees give nothing."),

D(274,273,'From Farm to Shop','🚚','Day275_CookingWell_B1.html','🍳','wordsearch',
  'Passive in a process: The fruit is picked, packed and sent.',
  [('storage','การเก็บรักษา','/ˈstɔːrɪdʒ/','📦'),('wholesale','ขายส่ง','/ˈhəʊlseɪl/','🏭'),
   ('retail','ขายปลีก','/ˈriːteɪl/','🏪'),('chain','ห่วงโซ่','/tʃeɪn/','⛓️'),
   ('perishable','เน่าเสียง่าย','/ˈperɪʃəbl/','⏳'),('expiry','วันหมดอายุ','/ɪkˈspaɪəri/','📅'),
   ('packaging','บรรจุภัณฑ์','/ˈpækɪdʒɪŋ/','🎁'),('canning','การบรรจุกระป๋อง','/ˈkænɪŋ/','🥫')],
  "Cold storage buys a farmer two extra weeks. A wholesale buyer takes the whole field at one price. The retail price is often four times the farm price. Every step forms one long chain from soil to plate. Perishable food must move fast or it is lost. Check the expiry date before you buy. Clever packaging protects food but fills the bin. Canning has fed families for two hundred years.",
  ["Cold storage buys a farmer two extra weeks.",
   "The retail price is often four times the farm price.",
   "Perishable food must move fast or it is lost.",
   "Check the expiry date before you buy.",
   "Clever packaging protects food but fills the bin."],
  ["The retail price is often four times the farm price.",
   "Check the expiry date before you buy.",
   "Clever packaging protects food but fills the bin."],
  "Why must perishable food move fast?","Because it is lost if it moves slowly."),

D(275,274,'Cooking Well','🍳','Day276_WhatIsInOurFood_B1.html','🍎','vowels',
  'Instructions with until: Simmer until the sauce is thick.',
  [('seasoning','เครื่องปรุงรส','/ˈsiːzənɪŋ/','🧂'),('marinate','หมักให้เข้าเนื้อ','/ˈmærɪneɪt/','🥣'),
   ('simmer','เคี่ยวไฟอ่อน','/ˈsɪmə(r)/','♨️'),('roast','อบหรือย่าง','/rəʊst/','🔥'),
   ('garnish','ตกแต่งจานอาหาร','/ˈɡɑːnɪʃ/','🌸'),('cuisine','อาหารประจำชาติ','/kwɪˈziːn/','🍜'),
   ('culinary','เกี่ยวกับการทำอาหาร','/ˈkʌlɪnəri/','👨‍🍳'),('ferment','หมักดอง','/fəˈment/','🫙')],
  "Taste before you add more seasoning. Marinate the chicken for an hour, not five minutes. Simmer the sauce until it is thick. Roast the vegetables until the edges turn brown. A simple garnish makes an ordinary plate look careful. Thai cuisine balances sweet, sour, salty and hot. A culinary school teaches order before it teaches flavour. People ferment food in every country on earth.",
  ["Taste before you add more seasoning.",
   "Marinate the chicken for an hour, not five minutes.",
   "Simmer the sauce until it is thick.",
   "A simple garnish makes an ordinary plate look careful.",
   "Thai cuisine balances sweet, sour, salty and hot."],
  ["Taste before you add more seasoning.",
   "Simmer the sauce until it is thick.",
   "Thai cuisine balances sweet, sour, salty and hot."],
  "How long should you marinate the chicken?","For an hour, not five minutes."),

D(276,275,'What Is In Our Food','🍎','Day277_Week41Review_B1.html','⭐','tiles',
  'Generalising: tend to / on the whole / in general.',
  [('nutrient','สารอาหาร','/ˈnjuːtriənt/','💊'),('mineral','แร่ธาตุ','/ˈmɪnərəl/','🪨'),
   ('fibre','กากใยอาหาร','/ˈfaɪbə(r)/','🍞'),('carbohydrate','คาร์โบไฮเดรต','/ˌkɑːbəˈhaɪdreɪt/','🍚'),
   ('vegan','กินมังสวิรัติเข้มงวด','/ˈviːɡən/','🥦'),('pickle','ผักดอง','/ˈpɪkl/','🥒'),
   ('wholesome','มีประโยชน์ต่อร่างกาย','/ˈhəʊlsəm/','💚'),('balanced','สมดุล','/ˈbælənst/','⚖️')],
  "Every nutrient does one job your body cannot do alone. A mineral like iron comes mostly from what you eat. Fibre keeps everything moving as it should. A carbohydrate is fuel, not an enemy. A vegan meal can be rich in protein too. One small pickle wakes up a plain bowl of rice. Wholesome food is usually the food with the shortest list. A balanced plate beats a perfect plate.",
  ["Every nutrient does one job your body cannot do alone.",
   "Fibre keeps everything moving as it should.",
   "A carbohydrate is fuel, not an enemy.",
   "A vegan meal can be rich in protein too.",
   "A balanced plate beats a perfect plate."],
  ["Fibre keeps everything moving as it should.",
   "A carbohydrate is fuel, not an enemy.",
   "A balanced plate beats a perfect plate."],
  "Is a carbohydrate an enemy?","No, a carbohydrate is fuel."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn)
