# -*- coding: utf-8 -*-
# Level 12 · B2 · Week 52 History, Power & Change (Day 352–357) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level12/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=12, cefr='B2', title=title, emoji=emoji, theme='History & Power',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(352,351,'Who Holds Power','👑','Day353_HowSocietiesWereOrdered_B2.html','🏰','tiles',
  'Historical narrative: it was not until / by the time / no sooner had.',
  [('monarchy','ระบอบกษัตริย์','/ˈmɒnəki/','👑'),('republic','สาธารณรัฐ','/rɪˈpʌblɪk/','🏛️'),
   ('sovereign','ผู้มีอำนาจสูงสุด','/ˈsɒvrɪn/','🦁'),('successor','ผู้สืบทอดตำแหน่ง','/səkˈsesə(r)/','➡️'),
   ('coronation','พระราชพิธีบรมราชาภิเษก','/ˌkɒrəˈneɪʃn/','💎'),('abdicate','สละราชสมบัติ','/ˈæbdɪkeɪt/','🚪'),
   ('depose','ถอดจากอำนาจ','/dɪˈpəʊz/','⬇️'),('oligarchy','คณาธิปไตย','/ˈɒlɪɡɑːki/','🕴️'),
   ('tyranny','ทรราชย์','/ˈtɪrəni/','⛓️')],
  "A monarchy passes power through a family; a republic passes it through a vote. A sovereign was once believed to rule by right rather than by agreement. Naming a successor early prevented more wars than any treaty. A coronation is a ceremony designed to make power look inevitable. Few rulers abdicate willingly, and those who do are long remembered. To depose a ruler is easier than to replace the system around them. In an oligarchy the few govern for the few. Tyranny is not simply cruelty; it is power with nothing above it.",
  ["A monarchy passes power through a family; a republic passes it through a vote.",
   "Naming a successor early prevented more wars than any treaty.",
   "A coronation is a ceremony designed to make power look inevitable.",
   "Few rulers abdicate willingly.",
   "Tyranny is power with nothing above it."],
  ["Naming a successor early prevented more wars than any treaty.",
   "Few rulers abdicate willingly.",
   "Tyranny is power with nothing above it."],
  "What is tyranny?","It is power with nothing above it."),

D(353,352,'How Societies Were Ordered','🏰','Day354_WhenPeopleSaidNo_B2.html','✊','scramble',
  'Describing past systems: were expected to / were forbidden from.',
  [('feudal','ระบบศักดินา','/ˈfjuːdl/','🏰'),('serf','ไพร่ติดที่ดิน','/sɜːf/','🌾'),
   ('aristocracy','ชนชั้นสูง','/ˌærɪˈstɒkrəsi/','🎩'),('peasantry','ชนชั้นชาวนา','/ˈpezntri/','🧑‍🌾'),
   ('guild','สมาคมช่างฝีมือ','/ɡɪld/','🔨'),('charter','กฎบัตร','/ˈtʃɑːtə(r)/','📜'),
   ('decree','พระราชกฤษฎีกา','/dɪˈkriː/','📢'),('assembly','สภาผู้แทน','/əˈsembli/','👥'),
   ('industrialisation','การเปลี่ยนสู่อุตสาหกรรม','/ɪnˌdʌstriəlaɪˈzeɪʃn/','🏭')],
  "In a feudal system land was exchanged for loyalty and service. A serf was not a slave and was still not free to leave. The aristocracy inherited both privilege and, occasionally, obligation. The peasantry produced the food and owned almost none of it. A guild controlled who could learn a trade and what it cost. A town charter granted rights that the king could not easily take back. A decree could change a law overnight without a single debate. An assembly, however weak, created the habit of asking permission. Industrialisation moved millions from fields into factories within two generations.",
  ["In a feudal system land was exchanged for loyalty and service.",
   "A serf was not a slave and was still not free to leave.",
   "The peasantry produced the food and owned almost none of it.",
   "A decree could change a law overnight without a single debate.",
   "Industrialisation moved millions from fields into factories."],
  ["A serf was not a slave and was still not free to leave.",
   "A decree could change a law overnight without a single debate.",
   "Industrialisation moved millions from fields into factories."],
  "Who produced the food in a feudal system?","The peasantry produced the food."),

D(354,353,'When People Said No','✊','Day355_WarandPeace_B2.html','🕊️','memory',
  'Consequence over time: which eventually led to / paved the way for.',
  [('uprising','การลุกฮือ','/ˈʌpraɪzɪŋ/','🔥'),('rebellion','การกบฏ','/rɪˈbeljən/','⚔️'),
   ('abolition','การเลิกทาส','/ˌæbəˈlɪʃn/','🔓'),('emancipation','การปลดปล่อยให้เป็นอิสระ','/ɪˌmænsɪˈpeɪʃn/','🕊️'),
   ('suffrage','สิทธิเลือกตั้ง','/ˈsʌfrɪdʒ/','🗳️'),('reformer','นักปฏิรูป','/rɪˈfɔːmə(r)/','🛠️'),
   ('exile','การเนรเทศ','/ˈeksaɪl/','🚢'),('decolonise','ปลดอาณานิคม','/ˌdiːˈkɒlənaɪz/','🌍'),
   ('nationalism','ชาตินิยม','/ˈnæʃnəlɪzəm/','🚩')],
  "An uprising usually begins over bread and ends over dignity. A rebellion that succeeds is later called a founding. The abolition of the slave trade took decades of unglamorous work. Emancipation on paper and freedom in practice arrived many years apart. Suffrage was extended slowly, and never without being demanded. A reformer is often less popular than a revolutionary and changes more. Many leaders spent years in exile before they were welcomed home. To decolonise a country was the beginning of the work, not the end. Nationalism can unite a people and can also teach them whom to fear.",
  ["An uprising usually begins over bread and ends over dignity.",
   "A rebellion that succeeds is later called a founding.",
   "Emancipation on paper and freedom in practice arrived many years apart.",
   "Suffrage was extended slowly, and never without being demanded.",
   "A reformer is often less popular than a revolutionary."],
  ["A rebellion that succeeds is later called a founding.",
   "Suffrage was extended slowly, and never without being demanded.",
   "A reformer is often less popular than a revolutionary."],
  "How does an uprising usually begin?","It usually begins over bread."),

D(355,354,'War and Peace','🕊️','Day356_MapsThatChanged_B2.html','🗺️','wordsearch',
  'Formal negotiation language: on the understanding that / subject to.',
  [('conquest','การพิชิตดินแดน','/ˈkɒŋkwest/','🐎'),('armistice','การสงบศึก','/ˈɑːmɪstɪs/','🤝'),
   ('truce','การหยุดยิงชั่วคราว','/truːs/','⏸️'),('neutrality','ความเป็นกลาง','/njuːˈtræləti/','⚖️'),
   ('occupation','การยึดครอง','/ˌɒkjuˈpeɪʃn/','🥾'),('ratify','ให้สัตยาบัน','/ˈrætɪfaɪ/','✍️'),
   ('annex','ผนวกดินแดน','/əˈneks/','➕'),('partition','การแบ่งแยกดินแดน','/pɑːˈtɪʃn/','✂️'),
   ('diaspora','ชุมชนพลัดถิ่น','/daɪˈæspərə/','🧳')],
  "Conquest was once considered a normal way for a border to move. An armistice stops the fighting; a peace treaty ends the war. A truce can last an afternoon or accidentally last a decade. Neutrality is difficult to hold and expensive to defend. Occupation changes a country long after the soldiers leave. A parliament must ratify a treaty before it means anything. To annex a region is to take it and then argue that it was always yours. Partition drew straight lines through crowded places. A diaspora keeps a homeland alive in memory and in money.",
  ["An armistice stops the fighting; a peace treaty ends the war.",
   "Neutrality is difficult to hold and expensive to defend.",
   "Occupation changes a country long after the soldiers leave.",
   "A parliament must ratify a treaty before it means anything.",
   "Partition drew straight lines through crowded places."],
  ["An armistice stops the fighting; a peace treaty ends the war.",
   "Occupation changes a country long after the soldiers leave.",
   "A parliament must ratify a treaty before it means anything."],
  "What must a parliament do before a treaty means anything?","It must ratify the treaty."),

D(356,355,'Maps That Changed','🗺️','Day357_ReadingtheEvidence_B2.html','🏺','vowels',
  'Comparing outcomes: whereas one gained / the other was left.',
  [('colony','อาณานิคม','/ˈkɒləni/','⚓'),('protectorate','รัฐในอารักขา','/prəˈtektərət/','☂️'),
   ('federation','สหพันธรัฐ','/ˌfedəˈreɪʃn/','🔗'),('secede','แยกตัวออก','/sɪˈsiːd/','↔️'),
   ('unify','รวมเป็นหนึ่ง','/ˈjuːnɪfaɪ/','🧲'),('autonomy','การปกครองตนเอง','/ɔːˈtɒnəmi/','🏳️'),
   ('migration','การอพยพย้ายถิ่น','/maɪˈɡreɪʃn/','🚶'),('plague','โรคระบาดครั้งใหญ่','/pleɪɡ/','🦠'),
   ('starvation','ภาวะอดอยากรุนแรง','/stɑːˈveɪʃn/','🍽️')],
  "A colony sent raw materials one way and finished goods the other. A protectorate kept its flag and lost its foreign policy. A federation shares power between the centre and the regions. When a region tries to secede, the argument is rarely only about money. It took war, trade and language to unify most modern states. Real autonomy means deciding things the capital would decide differently. Migration has shaped every nation that now argues about it. One plague in the fourteenth century changed the price of labour across Europe. Mass starvation is almost never only about the weather.",
  ["A colony sent raw materials one way and finished goods the other.",
   "A federation shares power between the centre and the regions.",
   "Real autonomy means deciding things the capital would decide differently.",
   "Migration has shaped every nation that now argues about it.",
   "Mass starvation is almost never only about the weather."],
  ["A federation shares power between the centre and the regions.",
   "Migration has shaped every nation that now argues about it.",
   "Mass starvation is almost never only about the weather."],
  "Is mass starvation only about the weather?","No, it is almost never only about the weather."),

D(357,356,'Reading the Evidence','🏺','Day358_Week52Review_B2.html','⭐','tiles',
  'Historical caution: the record suggests / we cannot know whether.',
  [('chronicle','บันทึกเหตุการณ์ตามลำดับ','/ˈkrɒnɪkl/','📖'),('manuscript','ต้นฉบับลายมือ','/ˈmænjuskrɪpt/','🖋️'),
   ('inscription','ข้อความจารึก','/ɪnˈskrɪpʃn/','🪨'),('excavation','การขุดค้น','/ˌekskəˈveɪʃn/','⛏️'),
   ('relic','วัตถุตกทอดจากอดีต','/ˈrelɪk/','🏺'),('preservation','การอนุรักษ์ของเก่า','/ˌprezəˈveɪʃn/','🧊'),
   ('conjecture','การคาดเดาจากหลักฐาน','/kənˈdʒektʃə(r)/','🔍'),('revisionism','การเขียนประวัติศาสตร์ใหม่','/rɪˈvɪʒənɪzəm/','♻️'),
   ('inheritance','สิ่งที่ตกทอดถึงรุ่นหลัง','/ɪnˈherɪtəns/','🌳')],
  "A chronicle tells you what the writer's patron wanted recorded. One surviving manuscript may represent a thousand that burned. An inscription in stone lasts, which is why rulers preferred it. A careful excavation destroys the site as it reads it. Every relic answers one question and raises three more. Preservation costs money that no government enjoys spending. Two honest historians can build a different conjecture from the same letter. Revisionism is a normal part of history, and it can also be misused. An inheritance is what a generation leaves whether or not it meant to.",
  ["A chronicle tells you what the writer's patron wanted recorded.",
   "One surviving manuscript may represent a thousand that burned.",
   "A careful excavation destroys the site as it reads it.",
   "Every relic answers one question and raises three more.",
   "An inheritance is what a generation leaves whether or not it meant to."],
  ["One surviving manuscript may represent a thousand that burned.",
   "A careful excavation destroys the site as it reads it.",
   "Every relic answers one question and raises three more."],
  "What does every relic do?","It answers one question and raises three more."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
