# -*- coding: utf-8 -*-
# Level 11 · B2 · Week 46 Law, Rights & Justice (Day 308–313) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level11/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=11, cefr='B2', title=title, emoji=emoji, theme='Law & Rights',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(308,307,'The Rule of Law','⚖️','Day309_InsidetheCourtroom_B2.html','🏛️','tiles',
  'Formal obligation: shall / is required to / is prohibited from.',
  [('legislation','กฎหมายที่ออกใช้','/ˌledʒɪsˈleɪʃn/','📜'),('statute','บทบัญญัติ','/ˈstætʃuːt/','📕'),
   ('constitution','รัฐธรรมนูญ','/ˌkɒnstɪˈtjuːʃn/','🏛️'),('amendment','การแก้ไขเพิ่มเติม','/əˈmendmənt/','✏️'),
   ('jurisdiction','เขตอำนาจศาล','/ˌdʒʊərɪsˈdɪkʃn/','🗺️'),('precedent','คำพิพากษาที่เป็นบรรทัดฐาน','/ˈpresɪdənt/','🔖'),
   ('lawful','ชอบด้วยกฎหมาย','/ˈlɔːfl/','✅'),('unlawful','ผิดกฎหมาย','/ʌnˈlɔːfl/','⛔'),
   ('legitimate','ชอบธรรม','/lɪˈdʒɪtɪmət/','🎖️')],
  "Legislation is written slowly on purpose. A statute means nothing until a court applies it to a real person. A constitution sets limits on the people who write the rules. An amendment is how a country admits it was wrong. Each court has its own jurisdiction and cannot reach beyond it. One precedent can shape thousands of later decisions. What is lawful in one country may be unlawful across the border. A legitimate government is one people accept even when they disagree with it.",
  ["Legislation is written slowly on purpose.",
   "A constitution sets limits on the people who write the rules.",
   "An amendment is how a country admits it was wrong.",
   "One precedent can shape thousands of later decisions.",
   "What is lawful in one country may be unlawful across the border."],
  ["An amendment is how a country admits it was wrong.",
   "One precedent can shape thousands of later decisions.",
   "Legislation is written slowly on purpose."],
  "What is an amendment?","It is how a country admits it was wrong."),

D(309,308,'Inside the Courtroom','🏛️','Day310_CrimeandConsequence_B2.html','🔒','scramble',
  'Reporting formally: it was alleged that / the court held that.',
  [('prosecution','ฝ่ายอัยการ','/ˌprɒsɪˈkjuːʃn/','👔'),('defendant','จำเลย','/dɪˈfendənt/','🧍'),
   ('plaintiff','โจทก์','/ˈpleɪntɪf/','🙋'),('testimony','คำให้การ','/ˈtestɪməni/','🗣️'),
   ('jury','คณะลูกขุน','/ˈdʒʊəri/','👥'),('magistrate','ผู้พิพากษาศาลชั้นต้น','/ˈmædʒɪstreɪt/','🧑‍⚖️'),
   ('attorney','ทนายความ','/əˈtɜːni/','💼'),('verdict','คำตัดสิน','/ˈvɜːdɪkt/','🔨'),
   ('impartial','เป็นกลาง','/ɪmˈpɑːʃl/','⚖️')],
  "The prosecution must prove its case; the defendant proves nothing. In a civil case the plaintiff brings the complaint. Testimony given under oath still has to be tested. A jury of ordinary people is a strange idea that mostly works. A magistrate hears the smaller cases first. An attorney argues for one side and is meant to. The verdict is announced in one sentence after weeks of argument. A judge who is not impartial is not a judge.",
  ["The prosecution must prove its case; the defendant proves nothing.",
   "In a civil case the plaintiff brings the complaint.",
   "Testimony given under oath still has to be tested.",
   "The verdict is announced in one sentence after weeks of argument.",
   "A judge who is not impartial is not a judge."],
  ["In a civil case the plaintiff brings the complaint.",
   "Testimony given under oath still has to be tested.",
   "A judge who is not impartial is not a judge."],
  "Who must prove the case?","The prosecution must prove its case."),

D(310,309,'Crime and Consequence','🔒','Day311_WhenThingsGoWrong_B2.html','📄','memory',
  'Passive with modals: may be released / must be reviewed.',
  [('convict','ตัดสินว่ามีความผิด','/kənˈvɪkt/','🔒'),('acquit','ตัดสินว่าไม่ผิด','/əˈkwɪt/','🕊️'),
   ('custody','การควบคุมตัว','/ˈkʌstədi/','🚪'),('bail','การประกันตัว','/beɪl/','💰'),
   ('parole','การพักโทษ','/pəˈrəʊl/','📆'),('tribunal','คณะตุลาการพิเศษ','/traɪˈbjuːnl/','🏢'),
   ('appeal','การอุทธรณ์','/əˈpiːl/','⬆️'),('liable','ต้องรับผิด','/ˈlaɪəbl/','🎯'),
   ('negligence','ความประมาทเลินเล่อ','/ˈneɡlɪdʒəns/','⚠️')],
  "To convict someone, doubt must be removed, not merely reduced. Courts acquit more often than the news suggests. Custody before trial is not punishment, although it feels like it. Bail lets a person wait for trial at home. Parole is release with conditions and a long memory. A special tribunal is created when ordinary courts cannot cope. The right to appeal is what makes one mistake survivable. A company can be liable even when nobody meant any harm. Negligence is failing to take the care a reasonable person would take.",
  ["Courts acquit more often than the news suggests.",
   "Bail lets a person wait for trial at home.",
   "Parole is release with conditions and a long memory.",
   "The right to appeal is what makes one mistake survivable.",
   "A company can be liable even when nobody meant any harm."],
  ["Bail lets a person wait for trial at home.",
   "The right to appeal is what makes one mistake survivable.",
   "A company can be liable even when nobody meant any harm."],
  "What makes one mistake survivable?","The right to appeal."),

D(311,310,'When Things Go Wrong','📄','Day312_RightsandFreedoms_B2.html','🕊️','wordsearch',
  'Concession and counter: admittedly / that said / nevertheless.',
  [('compensation','ค่าชดเชย','/ˌkɒmpenˈseɪʃn/','💵'),('arbitration','อนุญาโตตุลาการ','/ˌɑːbɪˈtreɪʃn/','🤝'),
   ('mediation','การไกล่เกลี่ย','/ˌmiːdiˈeɪʃn/','🫱'),('clause','ข้อสัญญา','/klɔːz/','📎'),
   ('breach','การผิดสัญญา','/briːtʃ/','💔'),('litigation','การฟ้องร้อง','/ˌlɪtɪˈɡeɪʃn/','⚔️'),
   ('advocacy','การเรียกร้องแทนผู้อื่น','/ˈædvəkəsi/','📢'),('petitioner','ผู้ยื่นคำร้อง','/pəˈtɪʃənə(r)/','✍️'),
   ('sovereignty','อำนาจอธิปไตย','/ˈsɒvrənti/','🚩')],
  "Compensation cannot undo an injury; it can only share the cost. Arbitration is faster than court and harder to escape. Mediation asks both sides to invent the answer themselves. Read the small clause at the end before you sign anything. A breach of contract is not always dishonest, sometimes it is only careless. Litigation is expensive even when you win. Advocacy speaks for those who cannot speak in the room. The petitioner waited four years for a hearing. Every treaty asks a country to trade some sovereignty for something else.",
  ["Compensation cannot undo an injury; it can only share the cost.",
   "Mediation asks both sides to invent the answer themselves.",
   "Read the small clause at the end before you sign anything.",
   "Litigation is expensive even when you win.",
   "Advocacy speaks for those who cannot speak in the room."],
  ["Mediation asks both sides to invent the answer themselves.",
   "Litigation is expensive even when you win.",
   "Advocacy speaks for those who cannot speak in the room."],
  "What does advocacy do?","It speaks for those who cannot speak in the room."),

D(312,311,'Rights and Freedoms','🕊️','Day313_HowWeChoose_B2.html','🗳️','vowels',
  'Abstract nouns as subjects: freedom requires / privacy protects.',
  [('liberty','เสรีภาพ','/ˈlɪbəti/','🗽'),('censorship','การเซ็นเซอร์','/ˈsensəʃɪp/','🚫'),
   ('surveillance','การสอดส่องเฝ้าดู','/sɜːˈveɪləns/','📹'),('activism','การเคลื่อนไหวเรียกร้อง','/ˈæktɪvɪzəm/','✊'),
   ('asylum','การลี้ภัย','/əˈsaɪləm/','🛟'),('deport','ส่งกลับประเทศ','/dɪˈpɔːt/','✈️'),
   ('discrimination','การเลือกปฏิบัติ','/dɪˌskrɪmɪˈneɪʃn/','🚷'),('confidentiality','การรักษาความลับ','/ˌkɒnfɪˌdenʃiˈæləti/','🔐'),
   ('impunity','การลอยนวลพ้นผิด','/ɪmˈpjuːnəti/','🫥')],
  "Liberty is easiest to defend before it is taken. Censorship rarely announces itself as censorship. Surveillance changes how people behave even when nobody is watching. Activism is inconvenient by design. A person may seek asylum when returning home would be dangerous. To deport someone is a decision that should never be routine. Discrimination is often quiet and always expensive to the whole society. Confidentiality is not about hiding wrongdoing; it is about choosing what to share. Where powerful people act with impunity, the law is only decoration.",
  ["Liberty is easiest to defend before it is taken.",
   "Censorship rarely announces itself as censorship.",
   "Surveillance changes how people behave even when nobody is watching.",
   "Activism is inconvenient by design.",
   "Confidentiality is about choosing what to share."],
  ["Censorship rarely announces itself as censorship.",
   "Activism is inconvenient by design.",
   "Confidentiality is about choosing what to share."],
  "What is confidentiality about?","It is about choosing what to share."),

D(313,312,'How We Choose','🗳️','Day314_Week46Review_B2.html','⭐','tiles',
  'Describing systems: under this system / in practice / in principle.',
  [('referendum','การลงประชามติ','/ˌrefəˈrendəm/','📮'),('ballot','บัตรลงคะแนน','/ˈbælət/','🗳️'),
   ('candidacy','การลงสมัครรับเลือกตั้ง','/ˈkændɪdəsi/','🎽'),('coalition','รัฐบาลผสม','/ˌkəʊəˈlɪʃn/','🧩'),
   ('mandate','อาณัติจากประชาชน','/ˈmændeɪt/','🏅'),('turnout','จำนวนผู้มาใช้สิทธิ','/ˈtɜːnaʊt/','👣'),
   ('answerable','ต้องตอบคำถามต่อประชาชน','/ˈɑːnsərəbl/','🔍'),('scrutiny','การตรวจสอบอย่างเข้มงวด','/ˈskruːtəni/','🔬'),
   ('consensus','ฉันทามติ','/kənˈsensəs/','🤍')],
  "A referendum asks a complicated country a simple question. The secret ballot is a surprisingly recent invention. She announced her candidacy on a Tuesday morning. A coalition governs by argument rather than by command. A large majority is a mandate; a narrow one is a warning. Low turnout weakens whoever wins. A leader who is not answerable will not stay careful. Public scrutiny is uncomfortable and necessary. Consensus is slower than voting and lasts longer.",
  ["A referendum asks a complicated country a simple question.",
   "The secret ballot is a surprisingly recent invention.",
   "A coalition governs by argument rather than by command.",
   "Low turnout weakens whoever wins.",
   "Consensus is slower than voting and lasts longer."],
  ["A coalition governs by argument rather than by command.",
   "Low turnout weakens whoever wins.",
   "Consensus is slower than voting and lasts longer."],
  "What does low turnout do?","It weakens whoever wins."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
