# -*- coding: utf-8 -*-
# Level 9 · B1 · Week 39 Work & Career (Day 255–260)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level9/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=9, cefr='B1', title=title, emoji=emoji, theme='Work',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(255,254,'The Job Hunt','🔍','Day256_StartingOut_B1.html','🪪','tiles',
  'Present perfect for experience: I have worked, she has studied.',
  [('resume','ประวัติย่อสมัครงาน','/ˈrezjumeɪ/','📄'),('applicant','ผู้สมัคร','/ˈæplɪkənt/','🙋'),
   ('vacancy','ตำแหน่งว่าง','/ˈveɪkənsi/','🪑'),('shortlist','คัดเหลือรอบสุดท้าย','/ˈʃɔːtlɪst/','📋'),
   ('recruit','รับคนเข้าทำงาน','/rɪˈkruːt/','🤝'),('reference','บุคคลอ้างอิง','/ˈrefrəns/','📞'),
   ('portfolio','แฟ้มผลงาน','/pɔːtˈfəʊliəʊ/','🗂️'),('credential','หลักฐานคุณสมบัติ','/krəˈdenʃl/','🎖️')],
  "A good resume fits on one page. Every applicant sends the same nervous email. The school posted one vacancy for a science teacher. Only five people reached the shortlist. Managers recruit for attitude as much as for skill. Always ask before you name a reference. A portfolio shows what you have really done. A credential proves it.",
  ["A good resume fits on one page.",
   "The school posted one vacancy for a science teacher.",
   "Only five people reached the shortlist.",
   "Always ask before you name a reference.",
   "A portfolio shows what you have really done."],
  ["A good resume fits on one page.",
   "Only five people reached the shortlist.",
   "A portfolio shows what you have really done."],
  "How many people reached the shortlist?","Only five people reached the shortlist."),

D(256,255,'Starting Out','🪪','Day257_GettingThingsDone_B1.html','✅','scramble',
  'Obligation: have to / be supposed to / be expected to.',
  [('probation','ช่วงทดลองงาน','/prəˈbeɪʃn/','⏳'),('supervisor','หัวหน้างาน','/ˈsuːpəvaɪzə(r)/','👔'),
   ('apprentice','ผู้ฝึกงานฝีมือ','/əˈprentɪs/','🔧'),('trainee','ผู้เข้ารับการอบรม','/ˌtreɪˈniː/','🧑‍🎓'),
   ('shift','กะการทำงาน','/ʃɪft/','🕗'),('roster','ตารางเวร','/ˈrɒstə(r)/','🗓️'),
   ('briefing','การชี้แจงงาน','/ˈbriːfɪŋ/','📢'),('diligent','ขยันขันแข็ง','/ˈdɪlɪdʒənt/','🐜')],
  "The first three months are a probation period. Ask your supervisor when you are unsure. An apprentice learns a trade by doing it. Every trainee makes mistakes in week one. Nan works the early shift on Tuesdays. Check the roster before you plan your weekend. The morning briefing takes ten minutes. A diligent worker is trusted quickly.",
  ["The first three months are a probation period.",
   "Ask your supervisor when you are unsure.",
   "An apprentice learns a trade by doing it.",
   "Check the roster before you plan your weekend.",
   "A diligent worker is trusted quickly."],
  ["Ask your supervisor when you are unsure.",
   "An apprentice learns a trade by doing it.",
   "A diligent worker is trusted quickly."],
  "Who should you ask when you are unsure?","Ask your supervisor."),

D(257,256,'Getting Things Done','✅','Day258_WorkingWithOthers_B1.html','👥','memory',
  'Gerunds after verbs: keep doing, avoid doing, finish doing.',
  [('workload','ปริมาณงาน','/ˈwɜːkləʊd/','📚'),('streamline','ทำให้กระชับขึ้น','/ˈstriːmlaɪn/','🧵'),
   ('efficiency','ประสิทธิภาพ','/ɪˈfɪʃnsi/','⚙️'),('productivity','ผลิตภาพ','/ˌprɒdʌkˈtɪvəti/','📈'),
   ('multitask','ทำหลายอย่างพร้อมกัน','/ˌmʌltiˈtɑːsk/','🤹'),('postpone','เลื่อนออกไป','/pəˈspəʊn/','📤'),
   ('agenda','ระเบียบวาระ','/əˈdʒendə/','📑'),('minutes','บันทึกการประชุม','/ˈmɪnɪts/','🖊️')],
  "A heavy workload is not the same as good work. Learn to streamline before you start. Efficiency means less effort for the same result. Productivity rises when you stop switching tasks. People who multitask finish slower, not faster. We all postpone a job that feels too big. Send the agenda before the meeting. Someone should write the minutes.",
  ["A heavy workload is not the same as good work.",
   "Learn to streamline before you start.",
   "Productivity rises when you stop switching tasks.",
   "We all postpone a job that feels too big.",
   "Send the agenda before the meeting."],
  ["Learn to streamline before you start.",
   "We all postpone a job that feels too big.",
   "Send the agenda before the meeting."],
  "Why do people postpone a job?","Because a job feels too big."),

D(258,257,'Working With Others','👥','Day259_MovingUp_B1.html','📈','wordsearch',
  'Reported speech: He said that he would send it.',
  [('teammate','เพื่อนร่วมทีม','/ˈtiːmmeɪt/','👫'),('networking','การสร้างเครือข่าย','/ˈnetwɜːkɪŋ/','🕸️'),
   ('internship','การฝึกงาน','/ˈɪntɜːnʃɪp/','🎓'),('cubicle','โต๊ะทำงานกั้นห้อง','/ˈkjuːbɪkl/','🧱'),
   ('stationery','เครื่องเขียน','/ˈsteɪʃənri/','✏️'),('freelance','รับงานอิสระ','/ˈfriːlɑːns/','🦅'),
   ('contractor','ผู้รับจ้างตามสัญญา','/kənˈtræktə(r)/','🧰'),('vocation','งานที่เป็นดั่งใจรัก','/vəʊˈkeɪʃn/','💛')],
  "A good teammate shares the credit and takes the blame. Networking is simply staying useful to people. A summer internship teaches more than a textbook. Keep your cubicle clear at the end of the day. The stationery cupboard is beside the printer. A freelance designer chooses her own hours. A contractor is paid for the job, not the month. Work becomes a vocation when it matters to you.",
  ["A good teammate shares the credit and takes the blame.",
   "Networking is simply staying useful to people.",
   "A summer internship teaches more than a textbook.",
   "Keep your cubicle clear at the end of the day.",
   "A freelance designer chooses her own hours."],
  ["Networking is simply staying useful to people.",
   "A summer internship teaches more than a textbook.",
   "A freelance designer chooses her own hours."],
  "What does a freelance designer choose?","She chooses her own hours."),

D(259,258,'Moving Up','📈','Day260_MoneyFromWork_B1.html','💰','vowels',
  'Second conditional: If I worked harder, I would earn more.',
  [('promotion','การเลื่อนตำแหน่ง','/prəˈməʊʃn/','🪜'),('appraisal','การประเมินผลงาน','/əˈpreɪzl/','📝'),
   ('contract','สัญญาจ้าง','/ˈkɒntrækt/','📜'),('overtime','ทำงานล่วงเวลา','/ˈəʊvətaɪm/','🌙'),
   ('employee','ลูกจ้าง','/ɪmˈplɔɪiː/','🧑‍💼'),('resign','ลาออก','/rɪˈzaɪn/','🚪'),
   ('seniority','อาวุโสในงาน','/ˌsiːniˈɒrəti/','🏅'),('prospects','โอกาสก้าวหน้า','/ˈprɒspekts/','🔭')],
  "A promotion is earned long before it is announced. Your yearly appraisal should hold no surprises. Read every line of a contract twice. Too much overtime costs more than it pays. A happy employee stays for years. People rarely resign because of the money alone. Seniority is not the same as skill. Ask about prospects before you accept a job.",
  ["A promotion is earned long before it is announced.",
   "Read every line of a contract twice.",
   "Too much overtime costs more than it pays.",
   "A happy employee stays for years.",
   "Seniority is not the same as skill."],
  ["Read every line of a contract twice.",
   "A happy employee stays for years.",
   "Seniority is not the same as skill."],
  "How many times should you read a contract?","You should read every line twice."),

D(260,259,'Money From Work','💰','Day261_Week39Review_B1.html','⭐','tiles',
  'Comparing quantity: fewer / less / far more than.',
  [('savings','เงินออม','/ˈseɪvɪŋz/','🏦'),('thrifty','ใช้เงินเป็น','/ˈθrɪfti/','🧮'),
   ('frugal','ประหยัดมัธยัสถ์','/ˈfruːɡl/','🪙'),('deposit','ฝากเงิน','/dɪˈpɒzɪt/','⬇️'),
   ('withdraw','ถอนเงิน','/wɪðˈdrɔː/','⬆️'),('currency','สกุลเงิน','/ˈkʌrənsi/','💱'),
   ('wealth','ความมั่งคั่ง','/welθ/','💎'),('premium','เบี้ยประกัน','/ˈpriːmiəm/','🧾')],
  "Pay your savings first, before anything else. A thrifty person is not a mean person. Being frugal in small things buys freedom in big ones. Deposit part of every payment you receive. Only withdraw what you planned to spend. Each country prints its own currency. Real wealth is having enough and knowing it. The premium is what you pay to stay protected.",
  ["Pay your savings first, before anything else.",
   "A thrifty person is not a mean person.",
   "Deposit part of every payment you receive.",
   "Only withdraw what you planned to spend.",
   "Each country prints its own currency."],
  ["A thrifty person is not a mean person.",
   "Only withdraw what you planned to spend.",
   "Each country prints its own currency."],
  "What should you pay first?","Pay your savings first."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn)
