# -*- coding: utf-8 -*-
# Level 8 · B1 · Week 34 Entertainment (218–224) · Week 35 Money & Society (225–231)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level8/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta, theme='Media'):
    return dict(n=n, prev=prev, level=8, cefr='B1', title=title, emoji=emoji, theme=theme,
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(218,217,'Lights and Cameras','🎬','Day219_BehindTheScenes_B1.html','🎥','tiles',
  'Opinion adjectives: fascinating, disappointing, overrated.',
  [('blockbuster','หนังทำเงิน','/ˈblɒkbʌstə(r)/','💥'),('producer','ผู้อำนวยการสร้าง','/prəˈdjuːsə(r)/','💼'),
   ('soundtrack','เพลงประกอบ','/ˈsaʊndtræk/','🎧'),('critic','นักวิจารณ์','/ˈkrɪtɪk/','✍️'),
   ('rating','คะแนนวิจารณ์','/ˈreɪtɪŋ/','⭐'),('premiere','รอบปฐมทัศน์','/ˈpremieə(r)/','🎟️'),
   ('animation','แอนิเมชัน','/ˌænɪˈmeɪʃn/','🖍️'),('overrated','ดังเกินจริง','/ˌəʊvəˈreɪtɪd/','🫤')],
  "The new blockbuster opened last Friday night. A famous producer spent three years on the film. Its soundtrack became popular before the premiere. One critic gave it a very low rating. Honestly, I think the story is overrated, said Ben. Mimi preferred the short animation before the main film. Everyone leaves the cinema with a different opinion.",
  ["The new blockbuster opened last Friday night.",
   "A famous producer spent three years on the film.",
   "Its soundtrack became popular before the premiere.",
   "One critic gave it a very low rating.",
   "Everyone leaves with a different opinion."],
  ["A famous producer spent three years on the film.",
   "One critic gave it a very low rating.",
   "Everyone leaves with a different opinion."],
  "What did the critic give the film?","The critic gave it a very low rating."),

D(219,218,'Behind the Scenes','🎥','Day220_FameAndPrivacy_B1.html','📸','scramble',
  'Passive with modals: The scene must be filmed again.',
  [('backstage','หลังเวที','/ˌbækˈsteɪdʒ/','🚪'),('spotlight','ไฟส่องเวที','/ˈspɒtlaɪt/','🔦'),
   ('crew','ทีมงาน','/kruː/','👷'),('takes','การถ่ายซ้ำ','/teɪks/','🎬'),
   ('editing','การตัดต่อ','/ˈedɪtɪŋ/','✂️'),('effect','เทคนิคพิเศษ','/ɪˈfekt/','✨'),
   ('makeup','การแต่งหน้า','/ˈmeɪkʌp/','💄'),('exhausting','เหนื่อยมาก','/ɪɡˈzɔːstɪŋ/','😮‍💨')],
  "Backstage the work is far less glamorous than the spotlight. A film crew may have eighty people. One short scene can need twenty takes. The editing team then works for many weeks. A single special effect may cost more than a house. Makeup can take three hours every morning. Filming is exhausting but the team loves it.",
  ["Backstage the work is less glamorous than the spotlight.",
   "A film crew may have eighty people.",
   "One short scene can need twenty takes.",
   "Makeup can take three hours every morning.",
   "Filming is exhausting but the team loves it."],
  ["A film crew may have eighty people.",
   "One short scene can need twenty takes.",
   "Filming is exhausting but the team loves it."],
  "How many takes can one short scene need?","It can need twenty takes."),

D(220,219,'Fame and Privacy','📸','Day221_WhatWeWatch_B1.html','📺','memory',
  'Advantages and disadvantages: on the one hand / on the other hand.',
  [('celebrity','คนดัง','/səˈlebrəti/','🌟'),('fame','ชื่อเสียง','/feɪm/','📛'),
   ('autograph','ลายเซ็น','/ˈɔːtəɡrɑːf/','✒️'),('paparazzi','ช่างภาพตามติด','/ˌpæpəˈrætsi/','📷'),
   ('pressure','ความกดดัน','/ˈpreʃə(r)/','🫨'),('gossip','ข่าวซุบซิบ','/ˈɡɒsɪp/','🌀'),
   ('boundaries','ขอบเขตส่วนตัว','/ˈbaʊndriz/','🚧'),('ordinary','ธรรมดา','/ˈɔːdnri/','🙂')],
  "A celebrity lives a very unusual life. On the one hand fame brings money and opportunity. On the other hand it removes almost every private moment. Fans wait for hours to get one autograph. The paparazzi follow a star even to the supermarket. Constant pressure can hurt anyone's health, so clear boundaries matter. Gossip spreads in minutes online. Many famous people say they miss an ordinary day.",
  ["A celebrity lives a very unusual life.",
   "On the one hand fame brings money and opportunity.",
   "Fans wait for hours to get one autograph.",
   "Constant pressure can hurt anyone's health, so clear boundaries matter.",
   "Many famous people say they miss an ordinary day."],
  ["On the one hand fame brings money and opportunity.",
   "Constant pressure can hurt anyone's health, so clear boundaries matter.",
   "Many famous people say they miss an ordinary day."],
  "What do many famous people miss?","They miss an ordinary day."),

D(221,220,'What We Watch','📺','Day222_MoneyMatters_B1.html','💳','wordsearch',
  'Frequency and preference: I tend to / I usually end up watching...',
  [('series','ซีรีส์','/ˈsɪəriːz/','📼'),('episode','ตอน','/ˈepɪsəʊd/','🔢'),
   ('documentary','สารคดี','/ˌdɒkjuˈmentri/','🎞️'),('subscribe','สมัครสมาชิก','/səbˈskraɪb/','🔔'),
   ('binge','ดูรวดเดียว','/bɪndʒ/','🍿'),('recommend','แนะนำ','/ˌrekəˈmend/','👍'),
   ('addictive','ทำให้ติด','/əˈdɪktɪv/','🧲'),('moderation','ความพอดี','/ˌmɒdəˈreɪʃn/','⚖️')],
  "Their favourite series has forty episode in total. Leo tends to binge three at a time on Saturday. Mimi prefers a nature documentary instead. Dad decided to subscribe to only one service. Some shows are so addictive that hours disappear. Would you recommend it to a friend? Everything is fine in moderation.",
  ["Their favourite series has forty episode in total.",
   "Leo tends to binge three at a time.",
   "Mimi prefers a nature documentary instead.",
   "Some shows are so addictive that hours disappear.",
   "Everything is fine in moderation."],
  ["Leo tends to binge three at a time.",
   "Some shows are so addictive that hours disappear.",
   "Everything is fine in moderation."],
  "What does Mimi prefer?","She prefers a nature documentary."),

D(222,221,'Money Matters','💳','Day223_AFairSociety_B1.html','⚖️','vowels',
  'Numbers and quantity: approximately, roughly, at least, no more than.',
  [('income','รายได้','/ˈɪnkʌm/','📥'),('expense','รายจ่าย','/ɪkˈspens/','📤'),
   ('invest','ลงทุน','/ɪnˈvest/','📈'),('interest','ดอกเบี้ย','/ˈɪntrəst/','🏦'),
   ('debt','หนี้','/det/','🪤'),('inflation','เงินเฟ้อ','/ɪnˈfleɪʃn/','🎈'),
   ('economy','เศรษฐกิจ','/ɪˈkɒnəmi/','🏭'),('budgeting','การวางแผนการเงิน','/ˈbʌdʒɪtɪŋ/','✅')],
  "Adults must balance income against every expense. If you invest early, small amounts grow over time. A bank pays interest on money you save. Debt becomes dangerous when it grows faster than income. Inflation means the same note buys less each year. A strong economy creates more jobs. Careful budgeting answers that question honestly.",
  ["Adults must balance income against every expense.",
   "If you invest early, small amounts grow over time.",
   "A bank pays interest on money you save.",
   "Inflation means the same note buys less each year.",
   "A strong economy creates more jobs."],
  ["If you invest early, small amounts grow over time.",
   "Inflation means the same note buys less each year.",
   "A strong economy creates more jobs."],
  "When does debt become dangerous?","When it grows faster than income."),

D(223,222,'A Fair Society','⚖️','Day224_Week34Review_B1.html','⭐','tiles',
  'Expressing necessity: it is essential that / we need to ensure...',
  [('equality','ความเท่าเทียม','/iˈkwɒləti/','🟰'),('chance','โอกาส','/tʃɑːns/','🚪'),
   ('poverty','ความยากจน','/ˈpɒvəti/','🥀'),('schooling','การได้เรียนหนังสือ','/ˈskuːlɪŋ/','🎓'),
   ('discriminate','เลือกปฏิบัติ','/dɪˈskrɪmɪneɪt/','🚫'),('justice','ความยุติธรรม','/ˈdʒʌstɪs/','⚖️'),
   ('welfare','สวัสดิการ','/ˈwelfeə(r)/','🤲'),('dignity','ศักดิ์ศรี','/ˈdɪɡnəti/','👑')],
  "Equality does not mean everyone is the same. It means everyone gets a fair chance. Poverty stops many clever children from studying. Free schooling changes a whole family. It is wrong to discriminate against anyone. Justice protects the weak as much as the strong. Good welfare gives every person dignity.",
  ["Equality does not mean everyone is the same.",
   "Poverty stops many clever children from studying.",
   "It is wrong to discriminate against anyone.",
   "Justice protects the weak as much as the strong.",
   "Good welfare gives every person dignity."],
  ["Poverty stops many clever children from studying.",
   "Justice protects the weak as much as the strong.",
   "Good welfare gives every person dignity."],
  "What does justice protect?","It protects the weak as much as the strong."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']),'คำ')
