# -*- coding: utf-8 -*-
# Level 13 · B2 · Week 56 Buildings, Cities & Design (Day 382–387) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level13/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=13, cefr='B2', title=title, emoji=emoji, theme='Buildings & Cities',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(382,381,'How Cities Are Built','🏗️','Day383_TheArtoftheBuilding_B2.html','🏛️','tiles',
  'Technical necessity: must be capable of / is required to withstand.',
  [('facade','ด้านหน้าอาคาร','/fəˈsɑːd/','🏢'),('footing','ฐานรากรับน้ำหนัก','/ˈfʊtɪŋ/','🪨'),
   ('girder','คานเหล็กใหญ่','/ˈɡɜːdə(r)/','🔩'),('cantilever','โครงยื่นออก','/ˈkæntɪliːvə(r)/','➡️'),
   ('truss','โครงถัก','/trʌs/','🔺'),('scaffold','นั่งร้าน','/ˈskæfəʊld/','🪜'),
   ('loadbearing','รับน้ำหนักโครงสร้าง','/ˈləʊdbeərɪŋ/','🏋️'),('reinforced','เสริมเหล็ก','/ˌriːɪnˈfɔːst/','🧱'),
   ('masonry','งานก่ออิฐหิน','/ˈmeɪsənri/','🧑‍🏭')],
  "A facade is the face of a building and sometimes only that. The footing is the part nobody photographs and everybody depends on. A steel girder can carry a load that no stone beam ever could. A cantilever reaches out with no support beneath its far end. A simple truss turns a weak flat shape into a strong triangular one. Scaffold goes up first and comes down last. Never remove a loadbearing wall to make a room feel bigger. Reinforced concrete is strong in both directions, which plain concrete is not. Good masonry can stand for six hundred years with almost no maintenance.",
  ["A facade is the face of a building and sometimes only that.",
   "The footing is the part nobody photographs.",
   "A cantilever reaches out with no support beneath its far end.",
   "Never remove a loadbearing wall to make a room feel bigger.",
   "Reinforced concrete is strong in both directions."],
  ["The footing is the part nobody photographs.",
   "Never remove a loadbearing wall to make a room feel bigger.",
   "Reinforced concrete is strong in both directions."],
  "What must you never remove?","Never remove a loadbearing wall."),

D(383,382,'The Art of the Building','🏛️','Day384_LivingSpaces_B2.html','🏘️','scramble',
  'Aesthetic judgement: succeeds because / is let down by / holds up over time.',
  [('column','เสา','/ˈkɒləm/','🏛️'),('dome','โดม','/dəʊm/','⛪'),
   ('vault','เพดานโค้ง','/vɔːlt/','🌉'),('buttress','ค้ำยันผนัง','/ˈbʌtrəs/','📐'),
   ('atrium','โถงกลางอาคาร','/ˈeɪtriəm/','🌤️'),('courtyard','ลานกลางบ้าน','/ˈkɔːtjɑːd/','🌳'),
   ('ornament','เครื่องประดับตกแต่ง','/ˈɔːnəmənt/','🎀'),('minimalist','เรียบง่ายที่สุด','/ˈmɪnɪməlɪst/','⬜'),
   ('aesthetic','เกี่ยวกับความงาม','/iːsˈθetɪk/','👁️')],
  "A column carries weight and also tells you which century you are in. A dome covers a wide space without a single pillar in the middle. A stone vault turns the weight of a roof into a sideways push. A buttress exists to answer that push. An atrium brings daylight into the middle of a deep building. A courtyard cools a house in a hot climate better than any machine. For a century ornament was considered dishonest, and then it was not. A minimalist room is expensive to build and easy to photograph. An aesthetic choice is never only an aesthetic choice.",
  ["A dome covers a wide space without a single pillar in the middle.",
   "A stone vault turns the weight of a roof into a sideways push.",
   "An atrium brings daylight into the middle of a deep building.",
   "A courtyard cools a house in a hot climate better than any machine.",
   "An aesthetic choice is never only an aesthetic choice."],
  ["A dome covers a wide space without a single pillar in the middle.",
   "An atrium brings daylight into the middle of a deep building.",
   "An aesthetic choice is never only an aesthetic choice."],
  "What does a courtyard do in a hot climate?","It cools a house better than any machine."),

D(384,383,'Living Spaces','🏘️','Day385_MovingThroughtheCity_B2.html','🚇','memory',
  'Comfort and standards: is adequate for / falls below / meets the requirement.',
  [('floorplan','ผังพื้น','/ˈflɔːplæn/','📄'),('ventilation','การระบายอากาศ','/ˌventɪˈleɪʃn/','🌬️'),
   ('acoustics','คุณภาพเสียงในอาคาร','/əˈkuːstɪks/','🔊'),('insulation','ฉนวนกันความร้อน','/ˌɪnsjuˈleɪʃn/','🧥'),
   ('highrise','อาคารสูง','/ˈhaɪraɪz/','🏙️'),('tenement','ตึกแถวเช่าราคาถูก','/ˈtenəmənt/','🚪'),
   ('renovate','ปรับปรุงใหม่','/ˈrenəveɪt/','🔨'),('demolish','รื้อทิ้ง','/dɪˈmɒlɪʃ/','💥'),
   ('ergonomic','ออกแบบตามสรีระ','/ˌɜːɡəˈnɒmɪk/','🪑')],
  "A good floorplan is felt rather than noticed. Cross ventilation costs nothing and cools a room all night. Poor acoustics can make an expensive hall unusable. Insulation pays for itself in about six winters. A highrise concentrates people and needs generous public space at the bottom. A crowded tenement in eighteen fifty taught cities why building rules exist. It is often cheaper to renovate than to demolish, and always kinder to the planet. Nobody demolishes a building because it is ugly; they demolish it because it is empty. An ergonomic chair is one you stop thinking about.",
  ["A good floorplan is felt rather than noticed.",
   "Cross ventilation costs nothing and cools a room all night.",
   "Insulation pays for itself in about six winters.",
   "It is often cheaper to renovate than to demolish.",
   "An ergonomic chair is one you stop thinking about."],
  ["A good floorplan is felt rather than noticed.",
   "Insulation pays for itself in about six winters.",
   "An ergonomic chair is one you stop thinking about."],
  "What is an ergonomic chair?","It is one you stop thinking about."),

D(385,384,'Moving Through the City','🚇','Day386_WhoGetstoLiveHere_B2.html','🔑','wordsearch',
  'Urban comparison: outperforms / at the expense of / to the benefit of.',
  [('junction','ทางแยก','/ˈdʒʌŋkʃn/','➕'),('roundabout','วงเวียน','/ˈraʊndəbaʊt/','🔄'),
   ('underpass','ทางลอด','/ˈʌndəpɑːs/','⬇️'),('flyover','ทางยกระดับ','/ˈflaɪəʊvə(r)/','⬆️'),
   ('boulevard','ถนนใหญ่มีต้นไม้','/ˈbuːləvɑːd/','🛣️'),('promenade','ทางเดินเลียบ','/ˌprɒməˈnɑːd/','🚶'),
   ('walkable','เดินได้สะดวก','/ˈwɔːkəbl/','👟'),('gridlock','การจราจรติดตาย','/ˈɡrɪdlɒk/','🚗'),
   ('sprawl','การขยายเมืองไร้ทิศทาง','/sprɔːl/','🗺️')],
  "A busy junction is where most city accidents happen. A roundabout is slower to enter and much safer than a crossroads. An underpass keeps people apart from traffic and often feels unsafe at night. A flyover solves gridlock for about eight years. A wide boulevard with trees is cooler than the same street without them. A river promenade turns a barrier into the best address in town. A walkable district needs shops, homes and work within a few streets. Building more lanes reliably produces more gridlock, not less. Sprawl is cheap to build and extremely expensive to serve.",
  ["A roundabout is slower to enter and much safer than a crossroads.",
   "A flyover solves gridlock for about eight years.",
   "A wide boulevard with trees is cooler than the same street without them.",
   "A walkable district needs shops, homes and work within a few streets.",
   "Sprawl is cheap to build and extremely expensive to serve."],
  ["A flyover solves gridlock for about eight years.",
   "A walkable district needs shops, homes and work within a few streets.",
   "Sprawl is cheap to build and extremely expensive to serve."],
  "What does building more lanes produce?","It reliably produces more gridlock, not less."),

D(386,385,'Who Gets to Live Here','🔑','Day387_TheCityUnderground_B2.html','🚰','vowels',
  'Policy trade-offs: at the cost of / in exchange for / with the result that.',
  [('zoning','การกำหนดเขตการใช้ที่ดิน','/ˈzəʊnɪŋ/','🗂️'),('gentrification','การเปลี่ยนย่านเก่าให้แพงขึ้น','/ˌdʒentrɪfɪˈkeɪʃn/','☕'),
   ('affordable','ราคาพอจ่ายไหว','/əˈfɔːdəbl/','🏷️'),('mixeduse','ใช้งานผสมผสาน','/ˌmɪkstˈjuːs/','🧩'),
   ('greenbelt','พื้นที่สีเขียวล้อมเมือง','/ˈɡriːnbelt/','🌲'),('vista','ทัศนียภาพ','/ˈvɪstə/','🏞️'),
   ('listedbuilding','อาคารที่ขึ้นทะเบียนอนุรักษ์','/ˈlɪstɪdbɪldɪŋ/','🏺'),('displacement','การถูกผลักออกจากพื้นที่','/dɪsˈpleɪsmənt/','📤'),
   ('participation','การมีส่วนร่วมของชุมชน','/pɑːˌtɪsɪˈpeɪʃn/','🙋')],
  "Zoning decides what may be built where, and therefore who can live there. Gentrification improves a street and slowly removes the people who improved it. Truly affordable housing has to be built, not merely hoped for. A mixeduse block puts a bakery under the flats and life on the pavement. A greenbelt limits sprawl and can also limit new homes. A protected vista is a view the law will not let anyone block. A listedbuilding costs more to keep and is worth keeping. Displacement is the part of regeneration that rarely appears in the brochure. Real participation means the plan can still change after the meeting.",
  ["Zoning decides what may be built where.",
   "Truly affordable housing has to be built, not merely hoped for.",
   "A greenbelt limits sprawl and can also limit new homes.",
   "A listedbuilding costs more to keep and is worth keeping.",
   "Real participation means the plan can still change after the meeting."],
  ["Truly affordable housing has to be built, not merely hoped for.",
   "A listedbuilding costs more to keep and is worth keeping.",
   "Real participation means the plan can still change after the meeting."],
  "What does real participation mean?","The plan can still change after the meeting."),

D(387,386,'The City Underground','🚰','Day388_Week56Review_B2.html','⭐','tiles',
  'Invisible systems: without which / on which everything depends.',
  [('sewer','ท่อระบายน้ำเสีย','/ˈsuːə(r)/','🕳️'),('drainage','ระบบระบายน้ำ','/ˈdreɪnɪdʒ/','💧'),
   ('grid','โครงข่ายสาธารณูปโภค','/ɡrɪd/','⚡'),('streetlight','ไฟถนน','/ˈstriːtlaɪt/','🔦'),
   ('prefabricated','สำเร็จรูปจากโรงงาน','/ˌpriːˈfæbrɪkeɪtɪd/','📦'),('modular','เป็นหน่วยประกอบ','/ˈmɒdjələ(r)/','🧊'),
   ('maintenance','การบำรุงรักษา','/ˈmeɪntənəns/','🔧'),('resilient','ทนทานฟื้นตัวได้','/rɪˈzɪliənt/','🌾'),
   ('subsidence','การทรุดตัวของดิน','/ˈsʌbsɪdəns/','📉')],
  "A city is judged by its sewer system more honestly than by its skyline. Poor drainage turns an ordinary storm into a disaster. When the grid fails, everything modern fails with it. A working streetlight changes how safe a street feels after dark. Prefabricated parts are made in a dry factory and assembled in a wet street. A modular design lets one building be repaired without closing the rest. Maintenance is the least glamorous and most valuable budget line there is. A resilient city fails gently rather than suddenly. Subsidence cracks walls slowly and is expensive to stop.",
  ["A city is judged by its sewer system more honestly than by its skyline.",
   "Poor drainage turns an ordinary storm into a disaster.",
   "When the grid fails, everything modern fails with it.",
   "Maintenance is the least glamorous and most valuable budget line there is.",
   "A resilient city fails gently rather than suddenly."],
  ["Poor drainage turns an ordinary storm into a disaster.",
   "Maintenance is the least glamorous and most valuable budget line.",
   "A resilient city fails gently rather than suddenly."],
  "How does a resilient city fail?","It fails gently rather than suddenly."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
