# -*- coding: utf-8 -*-
# Level 7 · B1 · Week 30 Work & Future (188–194) · Week 31 Environment (195–201)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level7/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta, theme='Work'):
    return dict(n=n, prev=prev, level=7, cefr='B1', title=title, emoji=emoji, theme=theme,
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(188,187,'My Future Job','💼','Day189_AtAnInterview_B1.html','🤵','tiles',
  'Future plans: I am going to / I hope to / I would like to.',
  [('career','อาชีพระยะยาว','/kəˈrɪə(r)/','🧭'),('profession','วิชาชีพ','/prəˈfeʃn/','🎓'),
   ('salary','เงินเดือน','/ˈsæləri/','💰'),('skill','ทักษะ','/skɪl/','🛠️'),
   ('qualification','คุณสมบัติ','/ˌkwɒlɪfɪˈkeɪʃn/','📜'),('apply','สมัคร','/əˈplaɪ/','✍️'),
   ('employer','นายจ้าง','/ɪmˈplɔɪə(r)/','🏢'),('ambition','ความมุ่งมั่น','/æmˈbɪʃn/','🔥')],
  "What career would you like in the future? Mimi hopes to enter the medical profession one day. A high salary is nice, but interesting work matters more. Every job needs a special skill and the right qualification. When you apply, an employer will read your letter carefully. Ben has the ambition to build his own company. Start learning today and your future will thank you.",
  ["What career would you like in the future?",
   "Mimi hopes to enter the medical profession.",
   "Every job needs a special skill.",
   "An employer will read your letter carefully.",
   "Ben has the ambition to build his own company."],
  ["Mimi hopes to enter the medical profession.",
   "An employer will read your letter carefully.",
   "Ben has the ambition to build his own company."],
  "What does Mimi hope to do?","She hopes to enter the medical profession."),

D(189,188,'At an Interview','🤵','Day190_WorkingTogether_B1.html','🧑‍💼','scramble',
  'Reported speech: He said that he was ready. She asked if I could start.',
  [('appointment','การนัดหมาย','/əˈpɔɪntmənt/','📅'),('punctual','ตรงต่อเวลา','/ˈpʌŋktʃuəl/','⏰'),
   ('impression','ความประทับใจ','/ɪmˈpreʃn/','✨'),('experience','ประสบการณ์','/ɪkˈspɪəriəns/','📚'),
   ('strength','จุดแข็ง','/streŋθ/','💪'),('weakness','จุดอ่อน','/ˈwiːknəs/','🪫'),
   ('frankly','อย่างตรงไปตรงมา','/ˈfræŋkli/','🗝️'),('assurance','ความเชื่อมั่น','/əˈʃʊərəns/','🌟')],
  "Ben arrived early for his appointment at the small office. Being punctual makes a very good impression. The manager asked about his experience with computers. What is your greatest strength? she said. Ben also spoke frankly about one weakness. His assurance grew as the meeting went on. He said that he was ready to learn anything.",
  ["Ben arrived early for his appointment.",
   "Being punctual makes a very good impression.",
   "The manager asked about his experience.",
   "What is your greatest strength, she said.",
   "He said that he was ready to learn anything."],
  ["Being punctual makes a very good impression.",
   "The manager asked about his experience.",
   "He said that he was ready to learn anything."],
  "Why is being punctual important?","Because it makes a good impression."),

D(190,189,'Working Together','🧑‍💼','Day191_OurPlanetToday_B1.html','🌍','memory',
  'Should have / could have: We should have started earlier.',
  [('colleague','เพื่อนร่วมงาน','/ˈkɒliːɡ/','👥'),('manager','ผู้จัดการ','/ˈmænɪdʒə(r)/','📋'),
   ('deadline','กำหนดส่ง','/ˈdedlaɪn/','⏳'),('meeting','การประชุม','/ˈmiːtɪŋ/','🗓️'),
   ('update','อัปเดตความคืบหน้า','/ˈʌpdeɪt/','📈'),('delegate','มอบหมายงาน','/ˈdelɪɡeɪt/','➡️'),
   ('efficient','มีประสิทธิภาพ','/ɪˈfɪʃnt/','⚡'),('dependable','ไว้วางใจได้','/dɪˈpendəbl/','🧱')],
  "A good colleague makes hard work feel lighter. Their manager set a clear deadline for Friday. Every Monday the team has a short meeting. Each person gives a quick update. A smart leader will delegate tasks fairly. An efficient team wastes less time and less energy. Everyone wants to work beside a dependable person.",
  ["A good colleague makes hard work feel lighter.",
   "Their manager set a clear deadline for Friday.",
   "Every Monday the team has a short meeting.",
   "A smart leader will delegate tasks fairly.",
   "An efficient team wastes less time."],
  ["Their manager set a clear deadline for Friday.",
   "A smart leader will delegate tasks fairly.",
   "An efficient team wastes less time."],
  "What does a smart leader do?","A smart leader will delegate tasks fairly."),

D(191,190,'Our Planet Today','🌍','Day192_ClimateChange_B1.html','🌡️','wordsearch',
  'Present perfect continuous: Temperatures have been rising for decades.',
  [('pollute','ทำให้เป็นมลพิษ','/pəˈluːt/','🏭'),('emission','การปล่อยมลพิษ','/ɪˈmɪʃn/','💨'),
   ('resource','ทรัพยากร','/rɪˈsɔːs/','⛏️'),('consume','บริโภค','/kənˈsjuːm/','🍽️'),
   ('shortage','การขาดแคลน','/ˈʃɔːtɪdʒ/','📉'),('sustainable','ยั่งยืน','/səˈsteɪnəbl/','🌿'),
   ('impact','ผลกระทบ','/ˈɪmpækt/','💥'),('urgent','เร่งด่วน','/ˈɜːdʒənt/','🚨')],
  "Factories pollute the air in many big cities. Car emission has been rising for decades. We consume more resource than the Earth can replace. A water shortage already affects several countries. A sustainable choice today protects tomorrow. Every small action has an impact. Scientists say the problem is urgent but not hopeless.",
  ["Factories pollute the air in many big cities.",
   "We consume more resource than the Earth can replace.",
   "A water shortage already affects several countries.",
   "A sustainable choice today protects tomorrow.",
   "Every small action has an impact."],
  ["Factories pollute the air in many big cities.",
   "A sustainable choice today protects tomorrow.",
   "Every small action has an impact."],
  "What do scientists say about the problem?","They say it is urgent but not hopeless."),

D(192,191,'Climate Change','🌡️','Day193_TakeAction_B1.html','📣','vowels',
  'Cause and effect: leads to / results in / is caused by.',
  [('carbon','คาร์บอน','/ˈkɑːbən/','⚫'),('drought','ภัยแล้ง','/draʊt/','🏜️'),
   ('erosion','การกัดเซาะ','/ɪˈrəʊʒn/','⛰️'),('deforestation','การตัดไม้ทำลายป่า','/ˌdiːˌfɒrɪˈsteɪʃn/','🪓'),
   ('threaten','คุกคาม','/ˈθretn/','🌊'),('extreme','รุนแรงสุดขั้ว','/ɪkˈstriːm/','🌪️'),
   ('adapt','ปรับตัว','/əˈdæpt/','🔄'),('predict','ทำนาย','/prɪˈdɪkt/','🔮')],
  "Too much carbon in the air leads to a warmer world. A long drought can destroy a whole harvest. Heavy rain results in soil erosion on bare hills. Deforestation removes the trees that hold the ground. Rising water threaten small islands everywhere. Extreme weather is becoming more common. Scientists predict that we must adapt quickly.",
  ["Too much carbon leads to a warmer world.",
   "A long drought can destroy a whole harvest.",
   "Deforestation removes the trees that hold the ground.",
   "Extreme weather is becoming more common.",
   "Scientists predict that we must adapt quickly."],
  ["A long drought can destroy a whole harvest.",
   "Extreme weather is becoming more common.",
   "Scientists predict that we must adapt quickly."],
  "What does deforestation remove?","It removes the trees that hold the ground."),

D(193,192,'Take Action','📣','Day194_Week30Review_B1.html','⭐','tiles',
  'Suggestions: Why not...? / How about...? / We ought to...',
  [('campaign','การรณรงค์','/kæmˈpeɪn/','📣'),('awareness','การตระหนักรู้','/əˈweənəs/','🔔'),
   ('reduce','ลดลง','/rɪˈdjuːs/','🔽'),('petition','คำร้อง','/pəˈtɪʃn/','✒️'),
   ('activist','นักกิจกรรม','/ˈæktɪvɪst/','✊'),('influence','อิทธิพล','/ˈɪnfluəns/','🌐'),
   ('commit','ให้คำมั่น','/kəˈmɪt/','🤞'),('lasting','ที่คงอยู่','/ˈlɑːstɪŋ/','♾️')],
  "The students started a campaign to save water. Their goal was to raise awareness in every classroom. Why not reduce plastic bottles first? asked Mimi. They wrote a petition and collected signatures. A young activist spoke at the school assembly. One clear voice can influence hundreds of people. If we commit today, the change will be lasting.",
  ["The students started a campaign to save water.",
   "Their goal was to raise awareness in every classroom.",
   "Why not reduce plastic bottles first?",
   "One clear voice can influence hundreds of people.",
   "If we commit today, the change will be lasting."],
  ["Their goal was to raise awareness in every classroom.",
   "One clear voice can influence hundreds of people.",
   "If we commit today, the change will be lasting."],
  "What was the goal of the campaign?","To raise awareness in every classroom."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']),'คำ')
