# -*- coding: utf-8 -*-
# Level 14 · B2 · Week 60 Global Challenges & Cooperation (Day 412–417) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level14/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=14, cefr='B2', title=title, emoji=emoji, theme='Global Cooperation',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(412,411,'One World, Many Problems','🌐','Day413_TalkingBetweenNations_B2.html','🕊️','tiles',
  'Global scale: worldwide / across borders / on every continent.',
  [('globalisation','โลกาภิวัตน์','/ˌɡləʊbəlaɪˈzeɪʃn/','🌐'),('interdependence','การพึ่งพากันและกัน','/ˌɪntədɪˈpendəns/','🔗'),
   ('supplychain','ห่วงโซ่อุปทาน','/səˈplaɪtʃeɪn/','🚢'),('protectionism','นโยบายกีดกันการค้า','/prəˈtekʃənɪzəm/','🧱'),
   ('freetrade','การค้าเสรี','/ˌfriːˈtreɪd/','🤝'),('sanction','มาตรการคว่ำบาตร','/ˈsæŋkʃn/','⛔'),
   ('reshoring','การย้ายการผลิตกลับประเทศ','/ˌriːˈʃɔːrɪŋ/','🏭'),('foodsecurity','ความมั่นคงทางอาหาร','/ˈfuːdsɪkjʊərəti/','🌾'),
   ('watersecurity','ความมั่นคงทางน้ำ','/ˈwɔːtəsɪkjʊərəti/','💧')],
  "Globalisation made goods cheaper and made every country easier to disrupt. Interdependence is safer than isolation and far less comfortable. One blocked canal showed the world how fragile a supplychain can be. Protectionism saves visible jobs and costs invisible ones. Freetrade raises total wealth and does not share it evenly by itself. A sanction is meant to change behaviour without firing a shot, and often fails. Reshoring costs more per unit and buys certainty. Foodsecurity is not about growing everything; it is about never depending on one source. Watersecurity will decide more borders this century than oil did last century.",
  ["Interdependence is safer than isolation and far less comfortable.",
   "One blocked canal showed the world how fragile a supplychain can be.",
   "Protectionism saves visible jobs and costs invisible ones.",
   "Reshoring costs more per unit and buys certainty.",
   "Foodsecurity is about never depending on one source."],
  ["Protectionism saves visible jobs and costs invisible ones.",
   "Reshoring costs more per unit and buys certainty.",
   "Foodsecurity is about never depending on one source."],
  "What does protectionism cost?","It costs invisible jobs."),

D(413,412,'Talking Between Nations','🕊️','Day414_WhenCrisisComes_B2.html','🚨','scramble',
  'Diplomatic register: the parties agreed to / expressed regret that.',
  [('multilateral','หลายฝ่ายร่วมกัน','/ˌmʌltiˈlætərəl/','👥'),('envoy','ผู้แทนพิเศษ','/ˈenvɔɪ/','✉️'),
   ('consulate','สถานกงสุล','/ˈkɒnsjələt/','🏢'),('conference','การประชุมนานาชาติ','/ˈkɒnfərəns/','⛰️'),
   ('communique','แถลงการณ์ร่วม','/kəˈmjuːnɪkeɪ/','📄'),('accord','ข้อตกลงร่วม','/əˈkɔːd/','🤍'),
   ('pact','สนธิสัญญาข้อตกลง','/pækt/','📜'),('ratification','การให้สัตยาบัน','/ˌrætɪfɪˈkeɪʃn/','✍️'),
   ('compliance','การปฏิบัติตามข้อตกลง','/kəmˈplaɪəns/','✅')],
  "A multilateral agreement is slower to reach and much harder to abandon. An envoy carries a message and sometimes carries the blame. A consulate helps its own citizens; an embassy speaks to the government. A conference is mostly the ceremony at the end of a year of quiet work. A joint communique is written by people who disagree and must both sign. An accord announces intention; a treaty creates obligation. A pact between two states is only as strong as the weaker promise in it. Ratification at home is where many international agreements quietly die. Without monitoring, compliance is simply a hope printed on good paper.",
  ["A multilateral agreement is slower to reach and much harder to abandon.",
   "A consulate helps its own citizens; an embassy speaks to the government.",
   "A conference is mostly the ceremony at the end of a year of quiet work.",
   "An accord announces intention; a treaty creates obligation.",
   "Ratification at home is where many international agreements quietly die."],
  ["A conference is mostly the ceremony at the end of a year of quiet work.",
   "An accord announces intention; a treaty creates obligation.",
   "A multilateral agreement is harder to abandon."],
  "What is a conference mostly?","The ceremony at the end of a year of quiet work."),

D(414,413,'When Crisis Comes','🚨','Day415_HealthWithoutBorders_B2.html','💉','memory',
  'Emergency response: is deployed to / is coordinated by / is scaled up.',
  [('lifesaving','ที่ช่วยชีวิตคน','/ˈlaɪfseɪvɪŋ/','🤲'),('peacekeeping','การรักษาสันติภาพ','/ˈpiːskiːpɪŋ/','🪖'),
   ('ceasefire','การหยุดยิง','/ˈsiːsfaɪə(r)/','🕊️'),('resettlement','การตั้งถิ่นฐานใหม่','/ˌriːˈsetlmənt/','🏘️'),
   ('haulage','การขนส่งลำเลียง','/ˈhɔːlɪdʒ/','🚚'),('coordination','การประสานงาน','/kəʊˌɔːdɪˈneɪʃn/','🔀'),
   ('remit','ขอบเขตอำนาจหน้าที่','/ˈriːmɪt/','📋'),('neutral','เป็นกลางไม่เข้าข้าง','/ˈnjuːtrəl/','⚪'),
   ('auditing','การตรวจสอบบัญชี','/ˈɔːdɪtɪŋ/','🔍')],
  "Lifesaving work is judged by whether it reaches the last village, not the first. Peacekeeping soldiers are not there to win; they are there to be seen. A ceasefire is fragile in the first seventy two hours and then usually holds. Resettlement asks a community to make room, and it works best when asked properly. In a disaster, haulage matters more than sympathy. Poor coordination means three agencies deliver blankets and nobody delivers water. A clear remit defines what a mission may do and, more importantly, may not. A neutral organisation can enter places a national army cannot. Careful auditing of aid money protects the donors and, far more, the recipients.",
  ["Lifesaving work is judged by whether it reaches the last village.",
   "Peacekeeping soldiers are there to be seen.",
   "In a disaster, haulage matters more than sympathy.",
   "A clear remit defines what a mission may do and may not.",
   "A neutral organisation can enter places a national army cannot."],
  ["In a disaster, haulage matters more than sympathy.",
   "A clear remit defines what a mission may do and may not.",
   "A neutral organisation can enter places a national army cannot."],
  "What matters more than sympathy in a disaster?","Haulage matters more than sympathy."),

D(415,414,'Health Without Borders','💉','Day416_KeepingthePeace_B2.html','🛡️','wordsearch',
  'Public-health language: is monitored for / is contained by / is eliminated.',
  [('preparedness','ความพร้อมรับมือ','/prɪˈpeədnəs/','🎒'),('containment','การควบคุมการระบาด','/kənˈteɪnmənt/','🔒'),
   ('eradicate','กำจัดให้หมดสิ้น','/ɪˈrædɪkeɪt/','🚫'),('immunisation','การสร้างภูมิคุ้มกันหมู่','/ˌɪmjunaɪˈzeɪʃn/','💉'),
   ('mortality','อัตราการเสียชีวิต','/mɔːˈtæləti/','📉'),('lifeexpectancy','อายุขัยเฉลี่ย','/ˈlaɪfɪkspektənsi/','📈'),
   ('indicator','ตัวชี้วัด','/ˈɪndɪkeɪtə(r)/','📊'),('capacitybuilding','การเสริมสร้างขีดความสามารถ','/kəˈpæsətiˌbɪldɪŋ/','🏗️'),
   ('electrification','การเข้าถึงไฟฟ้า','/ɪˌlektrɪfɪˈkeɪʃn/','💡')],
  "Preparedness is expensive before an outbreak and priceless during one. Early containment costs a fraction of late treatment. Only two diseases have ever been fully eradicated from the world. Mass immunisation protects the children who cannot be vaccinated at all. Falling child mortality is the clearest good news of the last century. Lifeexpectancy has risen almost everywhere and unevenly. A single indicator can hide as much as it reveals. Capacitybuilding means training local staff instead of flying experts in forever. Rural electrification changes education, health and income at the same time.",
  ["Preparedness is expensive before an outbreak and priceless during one.",
   "Early containment costs a fraction of late treatment.",
   "Mass immunisation protects the children who cannot be vaccinated at all.",
   "A single indicator can hide as much as it reveals.",
   "Rural electrification changes education, health and income at the same time."],
  ["Early containment costs a fraction of late treatment.",
   "A single indicator can hide as much as it reveals.",
   "Preparedness is priceless during an outbreak."],
  "What does early containment cost?","A fraction of late treatment."),

D(416,415,'Keeping the Peace','🛡️','Day417_MeasuringProgress_B2.html','📊','vowels',
  'Security language: is intended to deter / poses a risk of.',
  [('proliferation','การแพร่ขยายอาวุธ','/prəˌlɪfəˈreɪʃn/','☢️'),('disarmament','การลดอาวุธ','/dɪsˈɑːməmənt/','🔓'),
   ('deterrent','สิ่งที่ใช้ป้องปราม','/dɪˈterənt/','🛡️'),('inspection','การเข้าตรวจสอบ','/ɪnˈspekʃn/','🔬'),
   ('inspector','ผู้ตรวจการ','/ɪnˈspektə(r)/','🕵️'),('cybersecurity','ความมั่นคงไซเบอร์','/ˌsaɪbəsɪˈkjʊərəti/','🔐'),
   ('escalation','การยกระดับความขัดแย้ง','/ˌeskəˈleɪʃn/','📶'),('selfrestraint','การยับยั้งตนเอง','/ˌselfrɪˈstreɪnt/','✋'),
   ('stability','เสถียรภาพ','/stəˈbɪləti/','⚖️')],
  "Proliferation is easier to prevent than to reverse. Disarmament agreements survive only when both sides can check. A deterrent works by never being used, which makes it hard to measure. Inspection requires access that nobody wants to grant. An independent inspector is the least glamorous guarantee of peace there is. Cybersecurity has become a national security question in twenty years. Escalation is rarely a decision; it is usually a series of small responses. Selfrestraint after a provocation is the most underrated act in diplomacy. Stability is not the same as justice, and a wise policy wants both.",
  ["Proliferation is easier to prevent than to reverse.",
   "A deterrent works by never being used.",
   "An independent inspector is the least glamorous guarantee of peace there is.",
   "Escalation is rarely a decision; it is usually a series of small responses.",
   "Stability is not the same as justice."],
  ["Proliferation is easier to prevent than to reverse.",
   "A deterrent works by never being used.",
   "Stability is not the same as justice."],
  "How does a deterrent work?","It works by never being used."),

D(417,416,'Measuring Progress','📊','Day418_Week60Review_B2.html','⭐','tiles',
  'Evaluating claims: the trend has been / the figure conceals / broadly speaking.',
  [('benchmark','เกณฑ์เปรียบเทียบ','/ˈbentʃmɑːk/','📏'),('baseline','ค่าตั้งต้นก่อนวัดผล','/ˈbeɪslaɪn/','🏁'),
   ('aggregate','ค่ารวมทั้งหมด','/ˈæɡrɪɡət/','➕'),('disaggregate','แยกย่อยข้อมูล','/ˌdɪsˈæɡrɪɡeɪt/','➗'),
   ('proxy','ตัวแทนวัดทางอ้อม','/ˈprɒksi/','🎯'),('longitudinal','ตามติดระยะยาว','/ˌlɒŋɡɪˈtjuːdɪnl/','📆'),
   ('linkage','การเชื่อมโยงเหตุกับผล','/ˈlɪŋkɪdʒ/','🧬'),('unintended','ผลที่ไม่ได้ตั้งใจ','/ˌʌnɪnˈtendɪd/','🎲'),
   ('sustainability','ความยั่งยืนของผลลัพธ์','/səˌsteɪnəˈbɪləti/','♻️')],
  "A benchmark tells you whether the number is good, which the number alone cannot. Without a baseline, no improvement can be honestly claimed. An aggregate figure can rise while most people get poorer. Disaggregate the data by region and the story usually changes. A proxy measures what you can count instead of what you care about. A longitudinal study follows the same people for years and is worth the wait. Linkage is the hardest problem: the programme ran, and so did everything else. Every large intervention has an unintended consequence somewhere. Sustainability asks what remains three years after the funding stops.",
  ["A benchmark tells you whether the number is good.",
   "Without a baseline, no improvement can be honestly claimed.",
   "An aggregate figure can rise while most people get poorer.",
   "A proxy measures what you can count instead of what you care about.",
   "Sustainability asks what remains three years after the funding stops."],
  ["Without a baseline, no improvement can be honestly claimed.",
   "An aggregate figure can rise while most people get poorer.",
   "Sustainability asks what remains after the funding stops."],
  "What does sustainability ask?","What remains three years after the funding stops."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
