# -*- coding: utf-8 -*-
# Level 9 · B1 · Week 37 Global Issues (241–247) · Week 38 Study Skills (248–254)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level9/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta, theme='Global'):
    return dict(n=n, prev=prev, level=9, cefr='B1', title=title, emoji=emoji, theme=theme,
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(241,240,'One Shared World','🌏','Day242_HelpingAcrossBorders_B1.html','🤝','tiles',
  'Impersonal passive: It is believed that / It has been reported that.',
  [('humanitarian','ด้านมนุษยธรรม','/hjuːˌmænɪˈteəriən/','🕊️'),('aid','ความช่วยเหลือ','/eɪd/','📦'),
   ('treaty','สนธิสัญญา','/ˈtriːti/','📜'),('diplomacy','การทูต','/dɪˈpləʊməsi/','🤵'),
   ('negotiate','เจรจา','/nɪˈɡəʊʃieɪt/','💬'),('alliance','พันธมิตร','/əˈlaɪəns/','🔗'),
   ('summit','การประชุมสุดยอด','/ˈsʌmɪt/','🏔️'),('cooperation','ความร่วมมือ','/kəʊˌɒpəˈreɪʃn/','🫱')],
  "It is believed that no country can solve a crisis alone. Humanitarian aid crosses every border in an emergency. Leaders sign a treaty after months of quiet diplomacy. Skilled teams negotiate for weeks before an agreement. An alliance of small nations can be very powerful. Each summit brings new promises. Real cooperation is measured in action, not speeches.",
  ["It is believed that no country can solve a crisis alone.",
   "Humanitarian aid crosses every border in an emergency.",
   "Leaders sign a treaty after months of quiet diplomacy.",
   "An alliance of small nations can be very powerful.",
   "Real cooperation is measured in action, not speeches."],
  ["Humanitarian aid crosses every border in an emergency.",
   "An alliance of small nations can be very powerful.",
   "Real cooperation is measured in action, not speeches."],
  "How is real cooperation measured?","It is measured in action, not speeches."),

D(242,241,'Helping Across Borders','🤝','Day243_HealthForEveryone_B1.html','💉','scramble',
  'Quantity with uncountables: a great deal of suffering, a lack of clean water.',
  [('displaced','ต้องพลัดถิ่น','/dɪsˈpleɪst/','🏚️'),('famine','ทุพภิกขภัย','/ˈfæmɪn/','🥣'),
   ('scarcity','การขาดแคลน','/ˈskeəsəti/','🌵'),('donor','ผู้บริจาค','/ˈdəʊnə(r)/','💝'),
   ('supply','เสบียง','/səˈplaɪ/','🚚'),('encampment','ค่ายที่พัก','/ɪnˈkæmpmənt/','⛺'),
   ('necessity','สิ่งจำเป็น','/nəˈsesəti/','🚨'),('relief','การบรรเทาทุกข์','/rɪˈliːf/','🌤️')],
  "Millions of people are displaced by war and weather every year. A long famine follows serious water scarcity. A single donor cannot fix the problem alone. Trucks bring medical supply along dangerous roads. Families wait in a temporary encampment for months. Clean water is the first necessity of all. Relief work continues long after the news cameras leave.",
  ["Millions of people are displaced every year.",
   "A long famine follows serious water scarcity.",
   "Trucks bring medical supply along dangerous roads.",
   "Clean water is the first necessity of all.",
   "Relief work continues after the cameras leave."],
  ["A long famine follows serious water scarcity.",
   "Clean water is the first necessity of all.",
   "Relief work continues after the cameras leave."],
  "What is the first necessity?","Clean water is the most urgent need."),

D(243,242,'Health for Everyone','💉','Day244_StudySmart_B1.html','📚','memory',
  'Sequencing scientific process: once, as soon as, until, by the time.',
  [('vaccine','วัคซีน','/ˈvæksiːn/','💉'),('pandemic','การระบาดใหญ่','/pænˈdemɪk/','🌐'),
   ('outbreak','การระบาด','/ˈaʊtbreɪk/','📈'),('quarantine','การกักตัว','/ˈkwɒrəntiːn/','🚪'),
   ('symptom','อาการ','/ˈsɪmptəm/','🤒'),('prevention','การป้องกัน','/prɪˈvenʃn/','🛡️'),
   ('isolated','ห่างไกลผู้คน','/ˈaɪsəleɪtɪd/','🏥'),('equity','ความเป็นธรรม','/ˈekwəti/','💊')],
  "A vaccine takes years of careful testing. During a pandemic every country is affected. An outbreak can begin in one small village. Once a case is found, quarantine slows the spread. Learn to recognise a common symptom early. Prevention always costs less than treatment. One small clinic in an isolated area may serve twenty villages. Health equity is still a global challenge.",
  ["A vaccine takes years of careful testing.",
   "An outbreak can begin in one small village.",
   "Once a case is found, quarantine slows the spread.",
   "Prevention always costs less than treatment.",
   "Health equity is still a global challenge."],
  ["An outbreak can begin in one small village.",
   "Prevention always costs less than treatment.",
   "Health equity is still a global challenge."],
  "What costs less than treatment?","Prevention always costs less."),

D(244,243,'Study Smart','📚','Day245_BeatingDistraction_B1.html','🎯','wordsearch',
  'Gerund after prepositions: instead of reading, by writing, without stopping.',
  [('revision','การทบทวน','/rɪˈvɪʒn/','🔁'),('technique','เทคนิค','/tekˈniːk/','🛠️'),
   ('memorise','ท่องจำ','/ˈmeməraɪz/','🧠'),('flashcard','บัตรคำ','/ˈflæʃkɑːd/','🃏'),
   ('highlight','ไฮไลต์','/ˈhaɪlaɪt/','🖍️'),('annotate','จดโน้ตข้างเนื้อหา','/ˈænəteɪt/','✏️'),
   ('repetition','การทำซ้ำ','/ˌrepəˈtɪʃn/','♻️'),('effective','ได้ผล','/ɪˈfektɪv/','✅')],
  "Good revision is a skill you can learn. The best technique is not simply reading again. Instead of trying to memorise everything, understand the idea first. A flashcard forces your brain to recall the answer. Do not highlight the whole page in yellow. It is better to annotate in your own words. Spaced repetition is the most effective method we know.",
  ["Good revision is a skill you can learn.",
   "The best technique is not simply reading again.",
   "A flashcard forces your brain to recall the answer.",
   "It is better to annotate in your own words.",
   "Spaced repetition is the most effective method."],
  ["The best technique is not simply reading again.",
   "It is better to annotate in your own words.",
   "Spaced repetition is the most effective method."],
  "What does a flashcard force your brain to do?","It forces your brain to recall the answer."),

D(245,244,'Beating Distraction','🎯','Day246_ExamStrategy_B1.html','📝','vowels',
  'Reduced relative clauses: students working alone / a phone left on the desk.',
  [('concentrate','จดจ่อ','/ˈkɒnsntreɪt/','🔍'),('distraction','สิ่งรบกวน','/dɪˈstrækʃn/','📱'),
   ('procrastinate','ผัดวันประกันพรุ่ง','/prəʊˈkræstɪneɪt/','🐌'),('prioritise','จัดลำดับความสำคัญ','/praɪˈɒrətaɪz/','🥇'),
   ('interval','ช่วงพัก','/ˈɪntəvl/','⏲️'),('workspace','พื้นที่ทำงาน','/ˈwɜːkspeɪs/','🪑'),
   ('willpower','กำลังใจกำลังความตั้งใจ','/ˈwɪlpaʊə(r)/','💪'),('habitual','ที่ทำจนเป็นนิสัย','/həˈbɪtʃuəl/','🔂')],
  "It is hard to concentrate with a phone left on the desk. Every notification is a small distraction. Most students procrastinate because a task feels too big. Break it apart and prioritise the first step. Work for twenty five minutes, then take a short interval. A tidy workspace helps more than extra willpower. Studying at the same hour makes it habitual.",
  ["It is hard to concentrate with a phone on the desk.",
   "Every notification is a small distraction.",
   "Most students procrastinate because a task feels too big.",
   "Work for twenty five minutes, then take a short interval.",
   "Studying at the same hour makes it habitual."],
  ["Every notification is a small distraction.",
   "Work for twenty five minutes, then take a short interval.",
   "Studying at the same hour makes it habitual."],
  "Why do most students procrastinate?","Because a task feels too big."),

D(246,245,'Exam Strategy','📝','Day247_Week37Review_B1.html','⭐','tiles',
  'Advice with imperatives: skim first, underline key words, check your timing.',
  [('skim','อ่านผ่านเร็วๆ','/skɪm/','👁️'),('underline','ขีดเส้นใต้','/ˌʌndəˈlaɪn/','➖'),
   ('allocate','จัดสรร','/ˈæləkeɪt/','🧮'),('estimate','ประมาณการ','/ˈestɪmeɪt/','📐'),
   ('guess','เดา','/ɡes/','🎲'),('proofread','ตรวจทาน','/ˈpruːfriːd/','🔎'),
   ('panic','ตื่นตระหนก','/ˈpænɪk/','😱'),('composure','ความสงบนิ่ง','/kəmˈpəʊʒə(r)/','🧘')],
  "Skim the whole paper before you write anything. Underline the key word in every question. Allocate your minutes to each section fairly. Estimate how long the long answer will take. A sensible guess is better than an empty space. Always proofread if time remains. If you panic, breathe slowly and regain your composure.",
  ["Skim the whole paper before you write anything.",
   "Underline the key word in every question.",
   "Allocate your minutes to each section fairly.",
   "A sensible guess is better than an empty space.",
   "If you panic, breathe slowly and regain your composure."],
  ["Underline the key word in every question.",
   "A sensible guess is better than an empty space.",
   "If you panic, breathe slowly and regain your composure."],
  "What is better than an empty space?","A sensible guess is better."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']),'คำ')
