# -*- coding: utf-8 -*-
# Level 11 · B2 · Week 45 Economy & Society (Day 301–306) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level11/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=11, cefr='B2', title=title, emoji=emoji, theme='Economy & Society',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(301,300,'How Markets Work','📈','Day302_MoneyandGovernment_B2.html','🏛️','tiles',
  'Cause chains: which in turn / thereby / consequently.',
  [('commodity','สินค้าโภคภัณฑ์','/kəˈmɒdəti/','🌾'),('demand','อุปสงค์','/dɪˈmɑːnd/','📈'),
   ('monopoly','การผูกขาด','/məˈnɒpəli/','♟️'),('vendor','ผู้ขาย','/ˈvendə(r)/','🧺'),
   ('margin','ส่วนต่างกำไร','/ˈmɑːdʒɪn/','📐'),('overhead','ต้นทุนคงที่','/ˈəʊvəhed/','🏢'),
   ('revenue','รายรับ','/ˈrevənjuː/','💵'),('turnover','ยอดขายรวม','/ˈtɜːnəʊvə(r)/','🔁'),
   ('barter','แลกของกับของ','/ˈbɑːtə(r)/','🤝')],
  "Rice is a commodity, which means one sack is much like another. When demand rises faster than supply, the price follows. A monopoly has no reason to improve anything. Each vendor in the market watches the others closely. A thin margin can still make a good living. Overhead is what you pay before you sell a single item. Revenue is money coming in, not money kept. High turnover with no profit is a trap. Long before coins, people would barter what they had.",
  ["Rice is a commodity, which means one sack is much like another.",
   "When demand rises faster than supply, the price follows.",
   "A monopoly has no reason to improve anything.",
   "Overhead is what you pay before you sell a single item.",
   "Revenue is money coming in, not money kept."],
  ["A monopoly has no reason to improve anything.",
   "Overhead is what you pay before you sell a single item.",
   "Revenue is money coming in, not money kept."],
  "What is revenue?","Revenue is money coming in, not money kept."),

D(302,301,'Money and Government','🏛️','Day303_WhenEconomiesStruggle_B2.html','📉','scramble',
  'Hedged claims: tends to / is likely to / may well.',
  [('taxation','การเก็บภาษี','/tækˈseɪʃn/','🧾'),('subsidy','เงินอุดหนุน','/ˈsʌbsədi/','🎟️'),
   ('tariff','ภาษีศุลกากร','/ˈtærɪf/','🚢'),('fiscal','เกี่ยวกับการคลัง','/ˈfɪskl/','🏦'),
   ('monetary','เกี่ยวกับเงินตรา','/ˈmʌnɪtri/','🪙'),('deficit','การขาดดุล','/ˈdefɪsɪt/','➖'),
   ('stimulus','มาตรการกระตุ้น','/ˈstɪmjələs/','⚡'),('austerity','การรัดเข็มขัด','/ɔːˈsterəti/','🔒'),
   ('governance','ธรรมาภิบาล','/ˈɡʌvənəns/','⚖️')],
  "Taxation is how a country pays for the things nobody owns alone. A subsidy makes something cheaper than it truly costs. A tariff protects local jobs and raises local prices at the same time. Fiscal policy is about spending and taxing. Monetary policy is about interest and the money supply. A deficit is not always dangerous, but it is never free. A stimulus works best when it is fast and temporary. Austerity tends to hurt the people with the least. Good governance is judged over decades, not headlines.",
  ["Taxation is how a country pays for the things nobody owns alone.",
   "A subsidy makes something cheaper than it truly costs.",
   "Fiscal policy is about spending and taxing.",
   "A deficit is not always dangerous, but it is never free.",
   "Good governance is judged over decades, not headlines."],
  ["A subsidy makes something cheaper than it truly costs.",
   "A deficit is not always dangerous, but it is never free.",
   "Good governance is judged over decades, not headlines."],
  "How is good governance judged?","It is judged over decades, not headlines."),

D(303,302,'When Economies Struggle','📉','Day304_BuildingaBusiness_B2.html','🚀','memory',
  'Contrast at length: whereas / while / by contrast.',
  [('recession','ภาวะเศรษฐกิจถดถอย','/rɪˈseʃn/','📉'),('stagnation','ภาวะชะงักงัน','/stæɡˈneɪʃn/','🧊'),
   ('prosperity','ความมั่งคั่งรุ่งเรือง','/prɒˈsperəti/','🌟'),('volatility','ความผันผวน','/ˌvɒləˈtɪləti/','🎢'),
   ('speculation','การเก็งกำไร','/ˌspekjuˈleɪʃn/','🎲'),('devalue','ลดค่าเงิน','/ˌdiːˈvæljuː/','⬇️'),
   ('ration','ปันส่วน','/ˈræʃn/','🎫'),('livelihood','การทำมาหากิน','/ˈlaɪvlihʊd/','🧑‍🌾'),
   ('remittance','เงินที่ส่งกลับบ้าน','/rɪˈmɪtns/','✉️')],
  "A recession is two quarters of shrinking, and years of worry. Stagnation is worse than a fall, because nothing moves at all. Prosperity spreads unevenly, whereas hardship spreads fast. Volatility frightens savers more than a slow decline. Speculation turns a market into a casino. When a country has to devalue, imports become painful overnight. In wartime governments ration what they cannot supply. One flood can end a family's livelihood in an afternoon. For many villages, a monthly remittance is the whole economy.",
  ["A recession is two quarters of shrinking, and years of worry.",
   "Stagnation is worse than a fall, because nothing moves at all.",
   "Volatility frightens savers more than a slow decline.",
   "Speculation turns a market into a casino.",
   "One flood can end a family's livelihood in an afternoon."],
  ["Stagnation is worse than a fall, because nothing moves at all.",
   "Speculation turns a market into a casino.",
   "One flood can end a family's livelihood in an afternoon."],
  "Why is stagnation worse than a fall?","Because nothing moves at all."),

D(304,303,'Building a Business','🚀','Day305_TheGapBetweenUs_B2.html','⚖️','wordsearch',
  'Conditional advice: were you to / should you decide to.',
  [('enterprise','กิจการ','/ˈentəpraɪz/','🏭'),('entrepreneur','ผู้ประกอบการ','/ˌɒntrəprəˈnɜː(r)/','💡'),
   ('asset','สินทรัพย์','/ˈæset/','🏠'),('liability','หนี้สิน','/ˌlaɪəˈbɪləti/','⛓️'),
   ('shareholder','ผู้ถือหุ้น','/ˈʃeəhəʊldə(r)/','📜'),('dividend','เงินปันผล','/ˈdɪvɪdend/','🎁'),
   ('invoice','ใบแจ้งหนี้','/ˈɪnvɔɪs/','🧮'),('ledger','บัญชีแยกประเภท','/ˈledʒə(r)/','📒'),
   ('cooperative','สหกรณ์','/kəʊˈɒpərətɪv/','🫱')],
  "A small enterprise fails more often from bad records than bad ideas. An entrepreneur is someone who is comfortable being uncertain. An asset earns while you sleep. A liability costs while you sleep. Every shareholder owns a slice of the risk as well as the reward. A dividend is a share of profit, paid only when there is profit. Send the invoice the same week, not the same month. A clear ledger has saved more businesses than any clever plan. In a cooperative the workers and the owners are the same people.",
  ["An entrepreneur is someone who is comfortable being uncertain.",
   "An asset earns while you sleep.",
   "Every shareholder owns a slice of the risk as well as the reward.",
   "Send the invoice the same week, not the same month.",
   "A clear ledger has saved more businesses than any clever plan."],
  ["An asset earns while you sleep.",
   "Send the invoice the same week, not the same month.",
   "A clear ledger has saved more businesses than any clever plan."],
  "When should you send the invoice?","The same week, not the same month."),

D(305,304,'The Gap Between Us','⚖️','Day306_CountingaCountry_B2.html','📊','vowels',
  'Emphatic structures: what really matters is / it is X that.',
  [('inequality','ความเหลื่อมล้ำ','/ˌɪnɪˈkwɒləti/','📊'),('affluence','ความมั่งมี','/ˈæfluəns/','💎'),
   ('philanthropy','การกุศลขนาดใหญ่','/fɪˈlænθrəpi/','🤲'),('redistribution','การกระจายใหม่','/ˌriːdɪstrɪˈbjuːʃn/','🔄'),
   ('mobility','การเลื่อนชั้นทางสังคม','/məʊˈbɪləti/','🪜'),('bureaucracy','ระบบราชการ','/bjʊəˈrɒkrəsi/','🗂️'),
   ('corruption','การทุจริต','/kəˈrʌpʃn/','🕳️'),('capitalism','ระบบทุนนิยม','/ˈkæpɪtəlɪzəm/','🏙️'),
   ('socialism','ระบบสังคมนิยม','/ˈsəʊʃəlɪzəm/','🧑‍🤝‍🧑')],
  "Inequality is not the same as poverty, and both matter. Affluence in one district can hide hardship in the next street. Philanthropy is generous, but it is not a system. Redistribution is argued about in every parliament on earth. What really matters is mobility: can a child do better than her parents? A slow bureaucracy costs the poor more time than it costs the rich. Corruption is a tax that nobody voted for. Capitalism rewards risk. Socialism shares it. Most countries choose a little of each.",
  ["Inequality is not the same as poverty, and both matter.",
   "Philanthropy is generous, but it is not a system.",
   "Can a child do better than her parents?",
   "A slow bureaucracy costs the poor more time than it costs the rich.",
   "Corruption is a tax that nobody voted for."],
  ["Philanthropy is generous, but it is not a system.",
   "Corruption is a tax that nobody voted for.",
   "Capitalism rewards risk."],
  "What is corruption compared to?","It is a tax that nobody voted for."),

D(306,305,'Counting a Country','📊','Day307_Week45Review_B2.html','⭐','tiles',
  'Interpreting data: suggests that / accounts for / is attributable to.',
  [('census','สำมะโนประชากร','/ˈsensəs/','📋'),('demographic','เกี่ยวกับโครงสร้างประชากร','/ˌdeməˈɡræfɪk/','👨‍👩‍👧‍👦'),
   ('urbanisation','การขยายตัวของเมือง','/ˌɜːbənaɪˈzeɪʃn/','🌆'),('logistics','การขนส่งและกระจายสินค้า','/ləˈdʒɪstɪks/','🚛'),
   ('distribution','การกระจายสินค้า','/ˌdɪstrɪˈbjuːʃn/','🗺️'),('procurement','การจัดซื้อจัดจ้าง','/prəˈkjʊəmənt/','📥'),
   ('franchise','แฟรนไชส์','/ˈfræntʃaɪz/','🏪'),('microloan','สินเชื่อรายย่อย','/ˈmaɪkrəʊləʊn/','🌱'),
   ('transparency','ความโปร่งใส','/trænsˈpærənsi/','🪟')],
  "A census is taken once a decade and argued about for ten years. A demographic shift is slow, certain and easy to ignore. Urbanisation moved half the world into cities within one lifetime. Logistics decides whether medicine arrives before it expires. Distribution matters as much as production. Honest procurement saves more public money than any budget cut. A franchise sells a system, not just a product. One small microloan can start a shop that feeds a family. Transparency is cheaper than trust rebuilt after it is lost.",
  ["A census is taken once a decade and argued about for ten years.",
   "Urbanisation moved half the world into cities within one lifetime.",
   "Logistics decides whether medicine arrives before it expires.",
   "Distribution matters as much as production.",
   "A franchise sells a system, not just a product."],
  ["Distribution matters as much as production.",
   "A franchise sells a system, not just a product.",
   "Logistics decides whether medicine arrives before it expires."],
  "What does a franchise sell?","It sells a system, not just a product."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']),'คำ')
