# -*- coding: utf-8 -*-
# Level 15 · B2 · Week 64 The Last Stretch (Day 442–447) — 9,9,9,9,9,12 คำ
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level15/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=15, cefr='B2', title=title, emoji=emoji, theme='The Last Stretch',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(442,441,'Words That Trip People Up','🪤','Day443_SayingWhatYouMean_B2.html','💬','tiles',
  'Careful distinction: not to be confused with / strictly speaking.',
  [('imply','บอกเป็นนัย','/ɪmˈplaɪ/','🫥'),('complement','ส่วนที่เติมเต็มกัน','/ˈkɒmplɪmənt/','🧩'),
   ('discreet','รอบคอบไม่แพร่งพราย','/dɪˈskriːt/','🤫'),('discrete','แยกเป็นส่วนชัดเจน','/dɪˈskriːt/','🔢'),
   ('elicit','ดึงคำตอบออกมาได้','/iˈlɪsɪt/','🎣'),('illicit','ผิดกฎหมาย','/ɪˈlɪsɪt/','🚫'),
   ('ensure','ทำให้แน่ใจว่าเกิดขึ้น','/ɪnˈʃʊə(r)/','✅'),('comprise','ประกอบด้วย','/kəmˈpraɪz/','📦'),
   ('continual','เกิดซ้ำเป็นระยะ','/kənˈtɪnjuəl/','🔁')],
  "A speaker will imply something; a listener will infer it. Two things complement each other when each supplies what the other lacks. A discreet friend keeps your news to themselves. Discrete quantities can be counted; continuous ones can only be measured. A good question will elicit an honest answer. An illicit trade is one the law forbids and the market rewards. To ensure something is to make certain it happens. The committee comprises nine members; it is not comprised of them. Continual interruptions come again and again; continuous noise never stops at all.",
  ["A speaker will imply something; a listener will infer it.",
   "A discreet friend keeps your news to themselves.",
   "A good question will elicit an honest answer.",
   "To ensure something is to make certain it happens.",
   "Continual interruptions come again and again."],
  ["A speaker will imply something; a listener will infer it.",
   "A good question will elicit an honest answer.",
   "To ensure something is to make certain it happens."],
  "Who implies and who infers?","A speaker implies; a listener infers."),

D(443,442,'Saying What You Mean','💬','Day444_TheWayYouSayIt_B2.html','🎚️','scramble',
  'Softening and strengthening: I would suggest / I am convinced that.',
  [('candid','พูดตรงอย่างจริงใจ','/ˈkændɪd/','🪟'),('blunt','พูดตรงจนกระด้าง','/blʌnt/','🔨'),
   ('courteous','สุภาพมีมารยาท','/ˈkɜːtiəs/','🎩'),('gracious','อ่อนโยนมีน้ำใจ','/ˈɡreɪʃəs/','🌸'),
   ('concede','ยอมรับว่าอีกฝ่ายถูก','/kənˈsiːd/','🤲'),('acknowledge','รับรู้และยอมรับ','/əkˈnɒlɪdʒ/','👍'),
   ('endorse','สนับสนุนอย่างเปิดเผย','/ɪnˈdɔːs/','✍️'),('uphold','ยืนหยัดรักษาไว้','/ʌpˈhəʊld/','🛡️'),
   ('reckon','คิดว่าประเมินว่า','/ˈrekən/','🤔')],
  "A candid answer is honest and still chooses its words. A blunt answer is honest and has not bothered to. Being courteous costs nothing and is remembered for years. A gracious winner is far rarer than a good one. To concede a point in an argument makes your other points stronger. Acknowledge a mistake early and it stays small. To endorse something publicly is to lend it your own reputation. Uphold a rule you dislike and people will trust you with the ones you like. In everyday English, reckon simply means think.",
  ["A candid answer is honest and still chooses its words.",
   "Being courteous costs nothing and is remembered for years.",
   "To concede a point in an argument makes your other points stronger.",
   "Acknowledge a mistake early and it stays small.",
   "In everyday English, reckon simply means think."],
  ["A candid answer is honest and still chooses its words.",
   "Acknowledge a mistake early and it stays small.",
   "To concede a point makes your other points stronger."],
  "What happens if you acknowledge a mistake early?","It stays small."),

D(444,443,'The Way You Say It','🎚️','Day445_TheKindofPersonYouAre_B2.html','🧭','memory',
  'Idiomatic register: to be frank / to put it another way / if anything.',
  [('ballpark','ตัวเลขคร่าวๆ','/ˈbɔːlpɑːk/','⚾'),('upshot','ผลสรุปที่ได้','/ˈʌpʃɒt/','🎯'),
   ('grapple','ต่อสู้กับปัญหายาก','/ˈɡræpl/','🤼'),('linger','ค้างอยู่ไม่จางหาย','/ˈlɪŋɡə(r)/','🌫️'),
   ('unfold','ค่อยๆ คลี่คลาย','/ʌnˈfəʊld/','📜'),('ponder','ครุ่นคิดพิจารณา','/ˈpɒndə(r)/','💭'),
   ('savour','ลิ้มรสอย่างช้าๆ','/ˈseɪvə(r)/','🍵'),('cherish','ทะนุถนอมในใจ','/ˈtʃerɪʃ/','💗'),
   ('strive','มุ่งมั่นพยายาม','/straɪv/','🏔️')],
  "A ballpark figure is a rough estimate everyone understands is rough. The upshot of a long meeting can usually be written in one line. To grapple with an idea is more useful than to agree with it quickly. A good ending will linger for days. Let a difficult conversation unfold instead of forcing it. It is worth taking a minute to ponder before replying to anything important. Savour a language rather than only using it. Cherish the words you found difficult; they are the ones you truly learned. Strive for better and accept good on the way there.",
  ["A ballpark figure is a rough estimate everyone understands is rough.",
   "The upshot of a long meeting can usually be written in one line.",
   "To grapple with an idea is more useful than to agree with it quickly.",
   "Let a difficult conversation unfold instead of forcing it.",
   "Cherish the words you found difficult."],
  ["The upshot of a long meeting can usually be written in one line.",
   "Let a difficult conversation unfold instead of forcing it.",
   "Cherish the words you found difficult."],
  "What is a ballpark figure?","A rough estimate everyone understands is rough."),

D(445,444,'The Kind of Person You Are','🧭','Day446_KeepingEnglishAlive_B2.html','🌱','wordsearch',
  'Character description: is known for being / comes across as.',
  [('tenacious','ไม่ยอมปล่อยมือ','/təˈneɪʃəs/','🐕'),('meticulous','ละเอียดถี่ถ้วน','/məˈtɪkjələs/','🔬'),
   ('scrupulous','ซื่อตรงเคร่งครัด','/ˈskruːpjələs/','⚖️'),('resourceful','พลิกแพลงหาทางได้','/rɪˈsɔːsfl/','🧰'),
   ('conscientious','ทำงานด้วยความรับผิดชอบ','/ˌkɒnʃiˈenʃəs/','📋'),('astute','เฉียบแหลมมองขาด','/əˈstjuːt/','🦉'),
   ('pragmatic','เน้นปฏิบัติได้จริง','/præɡˈmætɪk/','🔧'),('poised','สุขุมมั่นคง','/pɔɪzd/','🕊️'),
   ('earnest','จริงจังจริงใจ','/ˈɜːnɪst/','🌾')],
  "A tenacious person is not stubborn; they simply have not finished. Meticulous work looks slow until you count the corrections it avoided. A scrupulous colleague is worth three clever ones. Resourceful people solve problems with what is already in the room. A conscientious worker does the part nobody will inspect. An astute observer notices what everyone else walked past. A pragmatic approach chooses the option that will actually be used. Someone poised does not need to be the loudest person present. An earnest effort deserves respect even when it does not succeed.",
  ["A tenacious person is not stubborn; they simply have not finished.",
   "Meticulous work looks slow until you count the corrections it avoided.",
   "Resourceful people solve problems with what is already in the room.",
   "A conscientious worker does the part nobody will inspect.",
   "An astute observer notices what everyone else walked past."],
  ["A tenacious person is not stubborn; they simply have not finished.",
   "A conscientious worker does the part nobody will inspect.",
   "An astute observer notices what everyone else walked past."],
  "What does a conscientious worker do?","The part nobody will inspect."),

D(446,445,'Keeping English Alive','🌱','Day447_FourHundredFortyEight_B2.html','🎓','vowels',
  'Habit for the future: from now on / whenever you get the chance.',
  [('nurture','บ่มเพาะดูแลให้เติบโต','/ˈnɜːtʃə(r)/','🌿'),('replenish','เติมให้เต็มอยู่เสมอ','/rɪˈplenɪʃ/','🔋'),
   ('steep','แช่ตัวอยู่กับภาษา','/stiːp/','🌊'),('revisit','กลับมาทบทวนอีกครั้ง','/ˌriːˈvɪzɪt/','🔂'),
   ('broaden','ขยายให้กว้างขึ้น','/ˈbrɔːdn/','🌍'),('hone','ลับฝีมือให้คม','/həʊn/','💎'),
   ('steadfastness','ความสม่ำเสมอมั่นคง','/ˈstedfɑːstnəs/','📆'),('inquisitive','ช่างสงสัยใคร่รู้','/ɪnˈkwɪzətɪv/','🔭'),
   ('continuing','ที่ดำเนินต่อไปเรื่อยๆ','/kənˈtɪnjuːɪŋ/','♾️')],
  "Nurture the habit and the vocabulary looks after itself. To replenish a language you need contact, not lessons. Steep yourself in it a little every week rather than a great deal once a year. Revisit an old chapter and notice how much easier it has become. Broaden your reading before you deepen it. Hone one skill at a time: this month listening, next month writing. Modest steadfastness survives a busy season; an ambitious plan does not. An inquisitive mind is the only requirement discipline cannot replace. Continuing study is not a slogan here; it is simply what happens next.",
  ["Nurture the habit and the vocabulary looks after itself.",
   "To replenish a language you need contact, not lessons.",
   "Revisit an old chapter and notice how much easier it has become.",
   "Modest steadfastness survives a busy season; an ambitious plan does not.",
   "An inquisitive mind is the only requirement discipline cannot replace."],
  ["To replenish a language you need contact, not lessons.",
   "Modest steadfastness survives a busy season.",
   "An inquisitive mind cannot be replaced by discipline."],
  "What do you need to replenish a language?","Contact, not lessons."),

D(447,446,'Four Hundred Forty Eight','🎓','Day448_TheFinalReview_B2.html','⭐','tiles',
  'Closing reflection: looking back / from here on / what remains is.',
  [('signpost','หมุดหมายบอกทาง','/ˈsaɪnpəʊst/','🪧'),('culmination','จุดสูงสุดของความพยายาม','/ˌkʌlmɪˈneɪʃn/','🎇'),
   ('testament','เครื่องพิสูจน์','/ˈtestəmənt/','🪶'),('gratifying','น่าพอใจชื่นใจ','/ˈɡrætɪfaɪɪŋ/','😊'),
   ('hardwon','ได้มาด้วยความยากลำบาก','/ˌhɑːdˈwʌn/','⛏️'),('unwavering','ไม่หวั่นไหว','/ʌnˈweɪvərɪŋ/','🗿'),
   ('doorway','ประตูสู่สิ่งใหม่','/ˈdɔːweɪ/','🚪'),('beckon','เรียกให้ก้าวไปหา','/ˈbekən/','➡️'),
   ('flourish','เจริญงอกงาม','/ˈflʌrɪʃ/','🌻'),('delve','เจาะลึกลงไป','/delv/','🧭'),
   ('resolute','แน่วแน่','/ˈrezəluːt/','🪨'),('boundless','ไร้ขีดจำกัด','/ˈbaʊndləs/','🌌')],
  "Day four hundred and forty eight is a signpost, not a finish. This is the culmination of four hundred and forty eight ordinary decisions. Three thousand words is a testament to showing up, not to talent. It is gratifying to read a page now and forget it is not your first language. Hardwon skill is the only kind that stays. Unwavering habits beat brilliant beginnings every single time. You are standing in a doorway that is already open. From here the road will beckon and it is yours to follow. Given use, a language will flourish; given silence, it will fade. Delve into books, films and conversations that are slightly too hard. Stay resolute on the days when nothing feels like progress. The world you can now read in English is boundless.",
  ["Day four hundred and forty eight is a signpost, not a finish.",
   "Three thousand words is a testament to showing up, not to talent.",
   "Hardwon skill is the only kind that stays.",
   "Unwavering habits beat brilliant beginnings every single time.",
   "Given use, a language will flourish; given silence, it will fade."],
  ["Three thousand words is a testament to showing up, not to talent.",
   "Hardwon skill is the only kind that stays.",
   "Given use, a language will flourish; given silence, it will fade."],
  "Is day four hundred and forty eight a finish?","No, it is a signpost, not a finish."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
