# -*- coding: utf-8 -*-
# Level 9 · B1 · Week 38 Innovation (248–254) · Week 39 Communication (255–261)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level9/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta, theme='Future'):
    return dict(n=n, prev=prev, level=9, cefr='B1', title=title, emoji=emoji, theme=theme,
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(248,247,'From Idea to Product','💡','Day249_TomorrowsTechnology_B1.html','🤖','tiles',
  'Stages with by the time: By the time it launches, five versions have been tested.',
  [('prototype','ต้นแบบ','/ˈprəʊtətaɪp/','🧪'),('patent','สิทธิบัตร','/ˈpætnt/','📃'),
   ('pitch','นำเสนอโครงการ','/pɪtʃ/','🎤'),('venture','กิจการใหม่','/ˈventʃə(r)/','🚀'),
   ('investor','นักลงทุน','/ɪnˈvestə(r)/','💼'),('feasible','เป็นไปได้จริง','/ˈfiːzəbl/','✔️'),
   ('refine','ขัดเกลาให้ดีขึ้น','/rɪˈfaɪn/','🪄'),('launch','เปิดตัว','/lɔːntʃ/','🎬')],
  "Every product begins as a rough prototype. The team applied for a patent last spring. Next month they will pitch the idea to an investor. A new venture needs money and patience. First the plan must be feasible, not only exciting. They refine the design after every test. By the time they launch, six versions have been tried.",
  ["Every product begins as a rough prototype.",
   "The team applied for a patent last spring.",
   "Next month they will pitch the idea to an investor.",
   "First the plan must be feasible, not only exciting.",
   "They refine the design after every test."],
  ["The team applied for a patent last spring.",
   "First the plan must be feasible, not only exciting.",
   "They refine the design after every test."],
  "What must the plan be first?","It must be feasible, not only exciting."),

D(249,248,'Tomorrow\'s Technology','🤖','Day250_ScienceAndEthics_B1.html','⚖️','scramble',
  'Speculating: it could well / it is likely to / there is a chance that.',
  [('autonomous','ทำงานได้เอง','/ɔːˈtɒnəməs/','🚗'),('sensor','เซนเซอร์','/ˈsensə(r)/','📡'),
   ('drone','โดรน','/drəʊn/','🛸'),('quantum','ควอนตัม','/ˈkwɒntəm/','⚛️'),
   ('genome','จีโนม','/ˈdʒiːnəʊm/','🧬'),('biotech','ไบโอเทค','/ˈbaɪəʊtek/','🦠'),
   ('adaptable','ปรับตัวได้','/əˈdæptəbl/','🔀'),('speculate','คาดการณ์','/ˈspekjuleɪt/','🔮')],
  "An autonomous car reads the road through a sensor. A small drone can deliver medicine to an island. Quantum computers may solve problems in seconds. Scientists can now read a human genome in one day. Biotech is changing how we grow food. The most adaptable workers will do best. It is easy to speculate, but hard to predict.",
  ["An autonomous car reads the road through a sensor.",
   "A small drone can deliver medicine to an island.",
   "Scientists can now read a human genome in one day.",
   "The most adaptable workers will do best.",
   "It is easy to speculate, but hard to predict."],
  ["A small drone can deliver medicine to an island.",
   "The most adaptable workers will do best.",
   "It is easy to speculate, but hard to predict."],
  "How does an autonomous car read the road?","It reads the road through a sensor."),

D(250,249,'Science and Ethics','⚖️','Day251_SpeakingWell_B1.html','🎤','memory',
  'Concession: although / even though / despite the fact that.',
  [('ethics','จริยธรรม','/ˈeθɪks/','⚖️'),('regulate','กำกับดูแล','/ˈreɡjuleɪt/','📋'),
   ('consent','การยินยอม','/kənˈsent/','✍️'),('transparent','โปร่งใส','/ˈtrænspərənt/','🪟'),
   ('misuse','ใช้ในทางที่ผิด','/ˌmɪsˈjuːs/','🚫'),('oversight','การกำกับตรวจสอบ','/ˈəʊvəsaɪt/','🚧'),
   ('discourse','การอภิปราย','/ˈdɪskɔːs/','💬'),('stewardship','การดูแลอย่างรับผิดชอบ','/ˈstjuːədʃɪp/','🤲')],
  "Just because we can do something does not mean we should. Ethics asks the harder question. Governments try to regulate new technology quickly enough. A patient must give clear consent before any test. Companies should be transparent about their data. Any powerful tool can be open to misuse. Careful oversight and open discourse decide the limits. Good stewardship protects everyone.",
  ["Just because we can do something does not mean we should.",
   "Governments try to regulate new technology.",
   "A patient must give clear consent before any test.",
   "Companies should be transparent about their data.",
   "Any powerful tool can be open to misuse."],
  ["Governments try to regulate new technology.",
   "Companies should be transparent about their data.",
   "Any powerful tool can be open to misuse."],
  "What must a patient give before any test?","A patient must give clear consent."),

D(251,250,'Speaking Well','🎤','Day252_TheArtOfListening_B1.html','👂','wordsearch',
  'Emphasis: It is the ending that people remember most.',
  [('articulate','พูดชัดถ้อยชัดคำ','/ɑːˈtɪkjuleɪt/','🗣️'),('clarity','ความชัดเจน','/ˈklærəti/','🔆'),
   ('pause','การหยุดเว้นจังหวะ','/pɔːz/','⏸️'),('emphasis','การเน้นย้ำ','/ˈemfəsɪs/','❗'),
   ('persuasion','การโน้มน้าว','/pəˈsweɪʒn/','🎯'),('rehearsal','การซ้อมพูด','/rɪˈhɜːsl/','🔁'),
   ('conciseness','ความกระชับ','/kənˈsaɪsnəs/','📏'),('eloquent','พูดจับใจ','/ˈeləkwənt/','💥')],
  "A confident speaker does not talk quickly. Try to articulate every ending sound. Clarity beats clever vocabulary every time. A short pause gives your idea room to land. Use emphasis on the word that truly matters. Persuasion comes from evidence and warmth together. Careful rehearsal turns a nervous speaker into an eloquent one. Conciseness is a gift to your audience.",
  ["A confident speaker does not talk quickly.",
   "Clarity beats clever vocabulary every time.",
   "A short pause gives your idea room to land.",
   "Persuasion comes from evidence and warmth together.",
   "Conciseness is a gift to your audience."],
  ["Clarity beats clever vocabulary every time.",
   "A short pause gives your idea room to land.",
   "Conciseness is a gift to your audience."],
  "What beats clever vocabulary?","Clarity beats clever vocabulary."),

D(252,251,'The Art of Listening','👂','Day253_WritingThatWorks_B1.html','✍️','vowels',
  'Indirect questions: Could you tell me what you meant by that?',
  [('attentive','ตั้งใจฟัง','/əˈtentɪv/','👂'),('paraphrase','พูดทวนด้วยคำตัวเอง','/ˈpærəfreɪz/','🔄'),
   ('interrupt','ขัดจังหวะ','/ˌɪntəˈrʌpt/','✋'),('presumption','การคิดไปเอง','/prɪˈzʌmpʃn/','❔'),
   ('curiosity','ความอยากรู้','/ˌkjʊəriˈɒsəti/','🧐'),('validate','ยอมรับความรู้สึก','/ˈvælɪdeɪt/','💗'),
   ('silence','ความเงียบ','/ˈsaɪləns/','🤫'),('understanding','ความเข้าใจ','/ˌʌndəˈstændɪŋ/','🤝')],
  "An attentive listener hears more than words. Try to paraphrase what the other person said. Do not interrupt to prepare your own reply. Check your own presumption before you judge. Ask from real curiosity, not politeness. Sometimes you only need to validate a feeling. Comfortable silence is part of a good conversation. Understanding is the real goal, not winning.",
  ["An attentive listener hears more than words.",
   "Try to paraphrase what the other person said.",
   "Do not interrupt to prepare your own reply.",
   "Sometimes you only need to validate a feeling.",
   "Understanding is the real goal, not winning."],
  ["Try to paraphrase what the other person said.",
   "Sometimes you only need to validate a feeling.",
   "Understanding is the real goal, not winning."],
  "What is the real goal of listening?","Understanding is the real goal, not winning."),

D(253,252,'Writing That Works','✍️','Day254_Week38Review_B1.html','⭐','tiles',
  'Linking words for essays: firstly, moreover, however, in conclusion.',
  [('draft','ฉบับร่าง','/drɑːft/','📝'),('composition','การเรียบเรียง','/ˌkɒmpəˈzɪʃn/','🏗️'),
   ('reasoning','การให้เหตุผล','/ˈriːzənɪŋ/','⚔️'),('coherent','ต่อเนื่องเป็นเหตุเป็นผล','/kəʊˈhɪərənt/','🔗'),
   ('edit','แก้ไขต้นฉบับ','/ˈedɪt/','✂️'),('formal','เป็นทางการ','/ˈfɔːml/','🎩'),
   ('informal','ไม่เป็นทางการ','/ɪnˈfɔːml/','👕'),('readership','กลุ่มผู้อ่าน','/ˈriːdəʃɪp/','👓')],
  "Nobody writes a perfect first draft. Plan the composition before the first sentence. Clear reasoning needs three solid points. Each paragraph must be coherent with the one before. Cut ten percent when you edit. A formal email sounds very different from an informal message. Always write for your real readership.",
  ["Nobody writes a perfect first draft.",
   "Plan the composition before the first sentence.",
   "Clear reasoning needs three solid points.",
   "Cut ten percent when you edit.",
   "A formal email sounds different from an informal message."],
  ["Plan the composition before the first sentence.",
   "Cut ten percent when you edit.",
   "A formal email sounds different from an informal message."],
  "How much should you cut when you edit?","Cut ten percent."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']),'คำ')
