# -*- coding: utf-8 -*-
# Level 13 · B2 · Week 53 Thinking & Ethics (Day 361–366) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level13/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=13, cefr='B2', title=title, emoji=emoji, theme='Thinking & Ethics',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(361,360,'The Shape of an Argument','🧩','Day362_WhenLogicBreaks_B2.html','🕳️','tiles',
  'Logical connectors: it follows that / from which we may conclude.',
  [('philosophy','ปรัชญา','/fəˈlɒsəfi/','🏛️'),('premise','ข้อตั้งต้นของเหตุผล','/ˈpremɪs/','🧱'),
   ('deduction','การอนุมานจากกฎสู่กรณี','/dɪˈdʌkʃn/','⬇️'),('induction','การสรุปจากกรณีสู่กฎ','/ɪnˈdʌkʃn/','⬆️'),
   ('syllogism','ตรรกบทสามขั้น','/ˈsɪlədʒɪzəm/','3️⃣'),('axiom','สัจพจน์','/ˈæksiəm/','🗿'),
   ('thesis','ข้อเสนอหลัก','/ˈθiːsɪs/','📌'),('antithesis','ข้อเสนอตรงข้าม','/ænˈtɪθəsɪs/','↔️'),
   ('objectivity','ความเป็นภววิสัย','/ˌɒbdʒekˈtɪvəti/','🔬')],
  "Philosophy is the habit of asking what a word actually means. Every argument stands on a premise, stated or hidden. Deduction moves from a general rule to a particular case. Induction moves the other way and is never quite certain. A syllogism has two premises and one conclusion, and can be perfectly valid while being false. An axiom is accepted without proof so that everything else can be proved. State your thesis in one sentence or you do not yet have one. The strongest writers state the antithesis fairly before answering it. Complete objectivity may be impossible, which is not a reason to stop trying.",
  ["Philosophy is the habit of asking what a word actually means.",
   "Every argument stands on a premise, stated or hidden.",
   "Deduction moves from a general rule to a particular case.",
   "State your thesis in one sentence or you do not yet have one.",
   "The strongest writers state the antithesis fairly before answering it."],
  ["Every argument stands on a premise, stated or hidden.",
   "State your thesis in one sentence or you do not yet have one.",
   "Deduction moves from a general rule to a particular case."],
  "What does every argument stand on?","It stands on a premise, stated or hidden."),

D(362,361,'When Logic Breaks','🕳️','Day363_TheGoodLife_B2.html','🌿','scramble',
  'Refuting: this does not follow / the conclusion overstates the evidence.',
  [('paradox','ปฏิทรรศน์','/ˈpærədɒks/','🔄'),('contradiction','ความขัดแย้งในตัวเอง','/ˌkɒntrəˈdɪkʃn/','⚔️'),
   ('fallacious','มีข้อบกพร่องทางตรรกะ','/fəˈleɪʃəs/','🕳️'),('refute','หักล้างด้วยหลักฐาน','/rɪˈfjuːt/','🛡️'),
   ('postulate','ตั้งสมมติฐานไว้ก่อน','/ˈpɒstjuleɪt/','💡'),('dialectic','วิภาษวิธี','/ˌdaɪəˈlektɪk/','♻️'),
   ('relativism','สัมพัทธนิยม','/ˈrelətɪvɪzəm/','🌗'),('absolutism','สัมบูรณนิยม','/ˈæbsəluːtɪzəm/','⬛'),
   ('subjectivity','ความเป็นอัตวิสัย','/ˌsʌbdʒekˈtɪvəti/','👁️')],
  "A paradox is a sentence that seems to defeat itself and often teaches something. A contradiction cannot be repaired by saying it louder. An argument may be fallacious and still reach a true conclusion by luck. To refute a claim you must show it false, not merely dislike it. We postulate something in order to see what would follow from it. Dialectic is the slow method of improving an idea by attacking it honestly. Strict relativism says every view is equally valid, which is hard to live by. Strict absolutism admits no exception, which is equally hard. Subjectivity is not a flaw to remove but a position to declare.",
  ["A paradox is a sentence that seems to defeat itself.",
   "A contradiction cannot be repaired by saying it louder.",
   "To refute a claim you must show it false, not merely dislike it.",
   "Dialectic improves an idea by attacking it honestly.",
   "Subjectivity is not a flaw to remove but a position to declare."],
  ["A contradiction cannot be repaired by saying it louder.",
   "To refute a claim you must show it false, not merely dislike it.",
   "Subjectivity is a position to declare."],
  "How do you refute a claim?","You must show it false, not merely dislike it."),

D(363,362,'The Good Life','🌿','Day364_WhatWeOweEachOther_B2.html','🤝','memory',
  'Value statements: what matters most is / it is better to.',
  [('virtue','คุณธรรม','/ˈvɜːtʃuː/','🌟'),('temperance','ความรู้จักพอ','/ˈtempərəns/','⚖️'),
   ('altruism','การเห็นแก่ผู้อื่น','/ˈæltruɪzəm/','🤲'),('selfishness','ความเห็นแก่ตัว','/ˈselfɪʃnəs/','🪞'),
   ('greed','ความโลภ','/ɡriːd/','💰'),('envy','ความอิจฉา','/ˈenvi/','🟢'),
   ('sincerity','ความจริงใจ','/sɪnˈserəti/','💗'),('hypocrisy','ความหน้าไหว้หลังหลอก','/hɪˈpɒkrəsi/','🎭'),
   ('utilitarian','แบบประโยชน์นิยม','/ˌjuːtɪlɪˈteəriən/','📊')],
  "A virtue is a habit, not a mood you happen to be in. Temperance is knowing when enough has arrived. Altruism appears in every human society ever studied. Selfishness is easy to see in others and invisible in oneself. Greed is not wanting much; it is never reaching the point of enough. Envy is the only one of these that gives no pleasure at all. Sincerity means the inside and the outside match. Hypocrisy is not failing to meet a standard; it is demanding it only of others. A utilitarian asks which action produces the most good overall.",
  ["A virtue is a habit, not a mood you happen to be in.",
   "Temperance is knowing when enough has arrived.",
   "Greed is never reaching the point of enough.",
   "Sincerity means the inside and the outside match.",
   "A utilitarian asks which action produces the most good overall."],
  ["A virtue is a habit, not a mood you happen to be in.",
   "Greed is never reaching the point of enough.",
   "Sincerity means the inside and the outside match."],
  "What is temperance?","It is knowing when enough has arrived."),

D(364,363,'What We Owe Each Other','🤝','Day365_HarmandRepair_B2.html','🩹','wordsearch',
  'Obligation and exception: as a rule / except where / unless it would.',
  [('reciprocity','การตอบแทนซึ่งกันและกัน','/ˌresɪˈprɒsəti/','🔁'),('trustworthiness','ความน่าไว้วางใจ','/ˈtrʌstwɜːðinəs/','🤞'),
   ('impartiality','ความไม่ลำเอียง','/ˌɪmpɑːʃiˈæləti/','👓'),('exploitation','การเอารัดเอาเปรียบ','/ˌeksplɔɪˈteɪʃn/','⛏️'),
   ('coercion','การบังคับข่มขู่','/kəʊˈɜːʃn/','🗜️'),('deception','การหลอกลวง','/dɪˈsepʃn/','🃏'),
   ('complicity','การมีส่วนร่วมในความผิด','/kəmˈplɪsəti/','🙈'),('proportional','ได้สัดส่วนเหมาะสม','/prəˈpɔːʃənl/','📐'),
   ('mercy','ความเมตตาผ่อนโทษ','/ˈmɜːsi/','🕊️')],
  "Reciprocity is the quiet rule that holds most communities together. Trustworthiness is built by keeping promises nobody was watching you make. Impartiality means the same rule for the person you like and the person you do not. Exploitation is a deal that is legal, voluntary and still unfair. Under coercion a choice is not really a choice. Deception can be achieved without saying anything untrue. Silence can become complicity when you had the power to speak. A punishment should be proportional to the harm, not to the anger. Mercy is choosing less than you are entitled to take.",
  ["Reciprocity is the quiet rule that holds most communities together.",
   "Impartiality means the same rule for the person you like and the person you do not.",
   "Under coercion a choice is not really a choice.",
   "Silence can become complicity when you had the power to speak.",
   "Mercy is choosing less than you are entitled to take."],
  ["Under coercion a choice is not really a choice.",
   "Silence can become complicity when you had the power to speak.",
   "Mercy is choosing less than you are entitled to take."],
  "What is mercy?","It is choosing less than you are entitled to take."),

D(365,364,'Harm and Repair','🩹','Day366_FreedomandFate_B2.html','🎲','vowels',
  'Hypothetical justice: suppose that / imagine a case in which.',
  [('remorse','ความสำนึกผิด','/rɪˈmɔːs/','💧'),('retribution','การลงโทษตอบแทน','/ˌretrɪˈbjuːʃn/','⚡'),
   ('deterrence','การป้องปราม','/dɪˈterəns/','🚧'),('restitution','การชดใช้คืน','/ˌrestɪˈtjuːʃn/','🧾'),
   ('reconciliation','การคืนดี','/ˌrekənsɪliˈeɪʃn/','🫱'),('culpable','มีความผิดที่ต้องรับ','/ˈkʌlpəbl/','🎯'),
   ('leniency','ความผ่อนปรน','/ˈliːniənsi/','🪶'),('vindictive','อาฆาตแค้น','/vɪnˈdɪktɪv/','🔥'),
   ('dilemma','สภาวะกลืนไม่เข้าคายไม่ออก','/dɪˈlemə/','🔀')],
  "Remorse is different from regret: regret is about the cost to you. Retribution answers a wrong with a matching harm and stops there. Deterrence tries to prevent the next offence rather than settle the last. Restitution asks the wrongdoer to repair what was actually broken. Reconciliation is slower than justice and sometimes worth more. A person found culpable is not the same as a person destroyed. Leniency shown once may be mercy; shown always it becomes neglect. A vindictive response feels satisfying and rarely improves anything. A true dilemma has no clean option, only a defensible one.",
  ["Remorse is different from regret: regret is about the cost to you.",
   "Deterrence tries to prevent the next offence.",
   "Restitution asks the wrongdoer to repair what was actually broken.",
   "Reconciliation is slower than justice and sometimes worth more.",
   "A true dilemma has no clean option, only a defensible one."],
  ["Restitution asks the wrongdoer to repair what was actually broken.",
   "Reconciliation is slower than justice and sometimes worth more.",
   "A true dilemma has no clean option, only a defensible one."],
  "What does a true dilemma have?","No clean option, only a defensible one."),

D(366,365,'Freedom and Fate','🎲','Day367_Week53Review_B2.html','⭐','tiles',
  'Abstract debate: proponents argue / critics counter that.',
  [('determinism','นิยัตินิยม','/dɪˈtɜːmɪnɪzəm/','⛓️'),('freewill','เจตจำนงเสรี','/ˌfriːˈwɪl/','🦋'),
   ('agency','ความสามารถกำหนดการกระทำเอง','/ˈeɪdʒənsi/','🎮'),('circumstance','สภาพแวดล้อมที่กำหนด','/ˈsɜːkəmstəns/','🌐'),
   ('headstart','การได้เปรียบตั้งแต่ต้น','/ˈhedstɑːt/','🎒'),('luck','โชค','/lʌk/','🍀'),
   ('merit','ความดีความชอบที่ทำได้เอง','/ˈmerɪt/','🏅'),('advantage','ข้อได้เปรียบ','/ədˈvɑːntɪdʒ/','🎁'),
   ('unassuming','ไม่โอ้อวดตัว','/ˌʌnəˈsjuːmɪŋ/','🙇')],
  "Determinism says every choice was already fixed by what came before. Freewill says something in you could have chosen otherwise. Agency is the ordinary experience of deciding, whatever the philosophers conclude. Circumstance shapes a life far more than most successful people admit. A headstart in life is real even when nobody talks about it. Luck decides where you were born and who taught you to read. Merit is real, and it is never the whole story. To notice your own advantage is not guilt; it is accuracy. An unassuming person simply sees the size of what they did not do alone.",
  ["Determinism says every choice was already fixed by what came before.",
   "Agency is the ordinary experience of deciding.",
   "Circumstance shapes a life far more than most successful people admit.",
   "Merit is real, and it is never the whole story.",
   "To notice your own advantage is not guilt; it is accuracy."],
  ["Agency is the ordinary experience of deciding.",
   "Merit is real, and it is never the whole story.",
   "To notice your own advantage is not guilt; it is accuracy."],
  "Is noticing your own advantage guilt?","No, it is accuracy."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
