# -*- coding: utf-8 -*-
# Level 11 · B2 · Week 48 The Mind & How We Learn (Day 322–327) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level11/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=11, cefr='B2', title=title, emoji=emoji, theme='Mind & Learning',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(322,321,'How the Mind Works','🧠','Day323_HowWeRemember_B2.html','📚','tiles',
  'Explaining mechanisms: this allows / this enables / as a result of which.',
  [('cognition','กระบวนการคิดรู้','/kɒɡˈnɪʃn/','🧠'),('perception','การรับรู้','/pəˈsepʃn/','👁️'),
   ('neuron','เซลล์ประสาท','/ˈnjʊərɒn/','⚡'),('synapse','จุดเชื่อมประสาท','/ˈsaɪnæps/','🔗'),
   ('cortex','เปลือกสมอง','/ˈkɔːteks/','🥥'),('plasticity','ความยืดหยุ่นของสมอง','/plæˈstɪsəti/','🪀'),
   ('subconscious','จิตใต้สำนึก','/ˌsʌbˈkɒnʃəs/','🌊'),('intuition','สัญชาตญาณ','/ˌɪntjuˈɪʃn/','💫'),
   ('concentration','สมาธิจดจ่อ','/ˌkɒnsnˈtreɪʃn/','🎯')],
  "Cognition is everything the brain does between seeing and deciding. Perception is not a recording; the brain fills in the gaps. A single neuron is simple, and eighty billion of them are not. Learning changes the synapse, not the number of brain cells. The cortex is the thin folded layer where most thinking happens. Plasticity means the brain keeps rewiring itself for your whole life. Your subconscious sorts the day while you sleep. Intuition is fast pattern matching, and it can be confidently wrong. Concentration is a skill you build, not a mood you wait for.",
  ["Cognition is everything the brain does between seeing and deciding.",
   "Perception is not a recording; the brain fills in the gaps.",
   "Plasticity means the brain keeps rewiring itself for your whole life.",
   "Intuition is fast pattern matching, and it can be confidently wrong.",
   "Concentration is a skill you build, not a mood you wait for."],
  ["Perception is not a recording; the brain fills in the gaps.",
   "Plasticity means the brain keeps rewiring itself for your whole life.",
   "Concentration is a skill you build, not a mood you wait for."],
  "Is concentration a mood?","No, it is a skill you build."),

D(323,322,'How We Remember','📚','Day324_HabitsandDrive_B2.html','🔁','scramble',
  'Describing processes: is stored as / is later retrieved by.',
  [('encode','แปลงข้อมูลเข้าความจำ','/ɪnˈkəʊd/','📥'),('retrieve','ดึงข้อมูลกลับมา','/rɪˈtriːv/','📤'),
   ('chunking','การจับกลุ่มข้อมูล','/ˈtʃʌŋkɪŋ/','🧩'),('forgetting','การลืม','/fəˈɡetɪŋ/','🕳️'),
   ('association','การเชื่อมโยง','/əˌsəʊsiˈeɪʃn/','🕸️'),('interference','การรบกวนความจำ','/ˌɪntəˈfɪərəns/','📡'),
   ('spacing','การทิ้งช่วงทบทวน','/ˈspeɪsɪŋ/','📅'),('visualise','นึกเป็นภาพ','/ˈvɪʒuəlaɪz/','🖼️'),
   ('overlearn','ฝึกซ้ำจนอัตโนมัติ','/ˌəʊvəˈlɜːn/','🔁')],
  "You cannot retrieve what you never took the trouble to encode. To retrieve a fact is itself a way of strengthening it. Chunking turns eleven digits into three easy pieces. Forgetting is not a fault; it is how the brain protects what matters. A strong association ties a new word to something you already own. Interference is why two similar words learned together get mixed up. Spacing your review across days beats one long evening. If you visualise a word in a scene, it stays. To overlearn something is to keep practising after you already know it.",
  ["You cannot retrieve what you never took the trouble to encode.",
   "Chunking turns eleven digits into three easy pieces.",
   "Forgetting is not a fault; it is how the brain protects what matters.",
   "Spacing your review across days beats one long evening.",
   "If you visualise a word in a scene, it stays."],
  ["Chunking turns eleven digits into three easy pieces.",
   "Spacing your review across days beats one long evening.",
   "If you visualise a word in a scene, it stays."],
  "What beats one long evening of study?","Spacing your review across days."),

D(324,323,'Habits and Drive','🔁','Day325_FeelingsHaveReasons_B2.html','💗','memory',
  'Talking about tendencies: we are inclined to / there is a tendency for.',
  [('motivation','แรงจูงใจ','/ˌməʊtɪˈveɪʃn/','🔥'),('reinforcement','การเสริมแรง','/ˌriːɪnˈfɔːsmənt/','➕'),
   ('conditioning','การวางเงื่อนไข','/kənˈdɪʃənɪŋ/','🔔'),('cue','สัญญาณกระตุ้น','/kjuː/','🚩'),
   ('routine','กิจวัตร','/ruːˈtiːn/','🗓️'),('impulse','แรงกระตุ้นฉับพลัน','/ˈɪmpʌls/','🎇'),
   ('craving','ความอยากอย่างแรง','/ˈkreɪvɪŋ/','🍩'),('dopamine','โดพามีน','/ˈdəʊpəmiːn/','💊'),
   ('mindset','กรอบความคิด','/ˈmaɪndset/','🪟')],
  "Motivation arrives after you start, not before. Reinforcement works better than punishment in almost every study. Conditioning explains why a bell can make a dog hungry. Every habit begins with a cue you have stopped noticing. Change the routine and leave the cue alone. An impulse lasts about ninety seconds if you let it pass. A craving is loudest just before it fades. Dopamine is about wanting more than about enjoying. A growth mindset treats difficulty as information, not as a verdict.",
  ["Motivation arrives after you start, not before.",
   "Reinforcement works better than punishment in almost every study.",
   "Every habit begins with a cue you have stopped noticing.",
   "An impulse lasts about ninety seconds if you let it pass.",
   "A growth mindset treats difficulty as information."],
  ["Motivation arrives after you start, not before.",
   "Every habit begins with a cue you have stopped noticing.",
   "A growth mindset treats difficulty as information."],
  "When does motivation arrive?","After you start, not before."),

D(325,324,'Feelings Have Reasons','💗','Day326_ThinkingClearly_B2.html','🔍','wordsearch',
  'Softening advice: it might help to / you may find that.',
  [('temperament','พื้นอารมณ์ประจำตัว','/ˈtemprəmənt/','🎭'),('serotonin','เซโรโทนิน','/ˌserəˈtəʊnɪn/','☀️'),
   ('assertive','กล้าแสดงออกอย่างสุภาพ','/əˈsɜːtɪv/','🗣️'),('reframe','มองมุมใหม่','/ˌriːˈfreɪm/','🔄'),
   ('coping','การรับมือ','/ˈkəʊpɪŋ/','🛟'),('acceptance','การยอมรับ','/əkˈseptəns/','🤲'),
   ('selftalk','การพูดกับตัวเอง','/ˈselftɔːk/','💭'),('optimism','การมองโลกในแง่ดี','/ˈɒptɪmɪzəm/','🌤️'),
   ('pessimism','การมองโลกในแง่ร้าย','/ˈpesɪmɪzəm/','🌧️')],
  "Temperament is what you were born with; character is what you build. Sunlight and sleep both affect serotonin, which affects mood. Being assertive is not the same as being loud. To reframe a setback is to ask what else it could mean. Healthy coping faces the problem instead of the feeling about the problem. Acceptance is not agreement; it is refusing to argue with what already happened. Kind selftalk is not silly, and cruel selftalk is not honest. Optimism helps you start. A little pessimism helps you prepare.",
  ["Temperament is what you were born with; character is what you build.",
   "Being assertive is not the same as being loud.",
   "To reframe a setback is to ask what else it could mean.",
   "Acceptance is not agreement.",
   "Optimism helps you start."],
  ["Being assertive is not the same as being loud.",
   "Acceptance is not agreement.",
   "Optimism helps you start."],
  "Is being assertive the same as being loud?","No, it is not the same."),

D(326,325,'Thinking Clearly','🔍','Day327_LookingAftertheMind_B2.html','🌿','vowels',
  'Questioning a claim: on what grounds / how do we know that.',
  [('heuristic','วิธีคิดลัด','/hjuˈrɪstɪk/','✂️'),('fallacy','ข้อผิดพลาดเชิงเหตุผล','/ˈfæləsi/','🃏'),
   ('rationalise','หาเหตุผลเข้าข้างตัวเอง','/ˈræʃnəlaɪz/','🎈'),('assumption','ข้อสันนิษฐาน','/əˈsʌmpʃn/','❓'),
   ('scepticism','การตั้งข้อสงสัย','/ˈskeptɪsɪzəm/','🧐'),('distortion','การบิดเบือน','/dɪˈstɔːʃn/','🪞'),
   ('avoidance','การหลีกเลี่ยง','/əˈvɔɪdəns/','🚪'),('interpretation','การตีความ','/ɪnˌtɜːprəˈteɪʃn/','🔎'),
   ('verification','การตรวจสอบข้อเท็จจริง','/ˌverɪfɪˈkeɪʃn/','✅')],
  "A heuristic is a shortcut that is usually right and occasionally disastrous. Naming a fallacy is easier than avoiding one. We rationalise a decision after making it and call it thinking. Every argument rests on an assumption somebody forgot to mention. Healthy scepticism asks for evidence; cynicism refuses it. A distortion is a true fact placed in a false frame. Avoidance feels like relief and behaves like debt. Two honest people can reach a different interpretation of the same figure. Verification takes five minutes and saves five years of being wrong.",
  ["A heuristic is a shortcut that is usually right.",
   "Naming a fallacy is easier than avoiding one.",
   "Healthy scepticism asks for evidence; cynicism refuses it.",
   "Avoidance feels like relief and behaves like debt.",
   "Verification takes five minutes and saves five years of being wrong."],
  ["Naming a fallacy is easier than avoiding one.",
   "Avoidance feels like relief and behaves like debt.",
   "Healthy scepticism asks for evidence."],
  "What does healthy scepticism ask for?","It asks for evidence."),

D(327,326,'Looking After the Mind','🌿','Day328_Week48Review_B2.html','⭐','tiles',
  'Recommending gently: it is worth / there is much to be said for.',
  [('counselling','การให้คำปรึกษา','/ˈkaʊnsəlɪŋ/','🗨️'),('diagnosis','การวินิจฉัย','/ˌdaɪəɡˈnəʊsɪs/','🩺'),
   ('meditation','การทำสมาธิ','/ˌmedɪˈteɪʃn/','🧘'),('daydream','ฝันกลางวัน','/ˈdeɪdriːm/','☁️'),
   ('drowsy','ง่วงซึม','/ˈdraʊzi/','😴'),('multisensory','ใช้หลายประสาทสัมผัส','/ˌmʌltiˈsensəri/','🎨'),
   ('verbalise','พูดออกมาเป็นคำ','/ˈvɜːbəlaɪz/','📢'),('restlessness','ความอยู่ไม่นิ่ง','/ˈrestləsnəs/','💤'),
   ('forbearance','ความใจเย็นอดกลั้น','/fɔːˈbeərəns/','⏳')],
  "Counselling is a conversation with someone trained to listen properly. A diagnosis is a starting point, never a description of a person. Ten minutes of meditation is worth more than an hour you never do. A wandering daydream is where a good deal of creative work happens. A drowsy brain learns almost nothing, so sleep is part of studying. Multisensory learning uses sound, sight and movement together. When you verbalise a worry it usually becomes smaller. Restlessness in class is a signal, not a crime. Forbearance with yourself is not the same as giving up on yourself.",
  ["Counselling is a conversation with someone trained to listen properly.",
   "A diagnosis is a starting point, never a description of a person.",
   "A drowsy brain learns almost nothing, so sleep is part of studying.",
   "When you verbalise a worry it usually becomes smaller.",
   "Forbearance with yourself is not the same as giving up on yourself."],
  ["A diagnosis is a starting point, never a description of a person.",
   "A drowsy brain learns almost nothing, so sleep is part of studying.",
   "When you verbalise a worry it usually becomes smaller."],
  "Why is sleep part of studying?","Because a drowsy brain learns almost nothing."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
