# -*- coding: utf-8 -*-
# Level 13 · B2 · Week 54 Space & Time (Day 368–373) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level13/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=13, cefr='B2', title=title, emoji=emoji, theme='Space & Time',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(368,367,'The Scale of the Universe','🌌','Day369_HowtheUniverseBegan_B2.html','💥','tiles',
  'Expressing magnitude: on the order of / by a factor of / vanishingly small.',
  [('nebula','เนบิวลา','/ˈnebjələ/','☁️'),('constellation','กลุ่มดาว','/ˌkɒnstəˈleɪʃn/','✨'),
   ('asteroid','ดาวเคราะห์น้อย','/ˈæstərɔɪd/','🪨'),('comet','ดาวหาง','/ˈkɒmɪt/','☄️'),
   ('eclipse','อุปราคา','/ɪˈklɪps/','🌑'),('lightyear','ปีแสง','/ˈlaɪtjɪə(r)/','📏'),
   ('observatory','หอดูดาว','/əbˈzɜːvətri/','🔭'),('exoplanet','ดาวเคราะห์นอกระบบ','/ˈeksəʊplænɪt/','🪐'),
   ('habitable','อาศัยอยู่ได้','/ˈhæbɪtəbl/','🌍')],
  "A nebula is a cloud of gas where new stars are still being made. A constellation is a pattern we drew, not a group that belongs together. An asteroid is rock; a comet is mostly ice and dust. A comet grows a tail only when it comes near the sun. An eclipse happens because the moon and the sun look almost the same size from here. One lightyear is the distance light travels in a year, and light is not slow. A mountain observatory is built high to see through less air. The first exoplanet was confirmed only in the nineteen nineties. A habitable world needs liquid water, and that is only the beginning of the list.",
  ["A nebula is a cloud of gas where new stars are still being made.",
   "A constellation is a pattern we drew.",
   "An asteroid is rock; a comet is mostly ice and dust.",
   "One lightyear is the distance light travels in a year.",
   "A habitable world needs liquid water."],
  ["A constellation is a pattern we drew.",
   "An asteroid is rock; a comet is mostly ice and dust.",
   "One lightyear is the distance light travels in a year."],
  "What does a habitable world need?","It needs liquid water."),

D(369,368,'How the Universe Began','💥','Day370_ExtremeObjects_B2.html','🕳️','scramble',
  'Reporting theory: is thought to have / is believed to be.',
  [('cosmology','จักรวาลวิทยา','/kɒzˈmɒlədʒi/','🌌'),('bigbang','บิกแบง','/ˌbɪɡˈbæŋ/','💥'),
   ('redshift','การเลื่อนไปทางแดง','/ˈredʃɪft/','🔴'),('expansion','การขยายตัวของเอกภพ','/ɪkˈspænʃn/','🎈'),
   ('cosmic','เกี่ยวกับเอกภพ','/ˈkɒzmɪk/','🌟'),('primordial','ดั้งเดิมแต่แรกเริ่ม','/praɪˈmɔːdiəl/','🥚'),
   ('abundance','ปริมาณธาตุที่พบ','/əˈbʌndəns/','⚖️'),('discern','สังเกตแยกแยะออก','/dɪˈsɜːn/','🧐'),
   ('speculative','ที่ยังเป็นเพียงข้อคาดการณ์','/ˈspekjələtɪv/','❓')],
  "Cosmology asks how everything began and how it is likely to end. The bigbang was not an explosion in space; it was the appearance of space. Redshift shows that distant galaxies are moving away from us. That expansion is happening everywhere, not from one centre. Faint cosmic background radiation is the oldest light there is. The primordial mixture was almost entirely hydrogen and helium. The measured abundance of those elements matches the theory closely. From the light alone we can discern temperature, speed and age. Anything beyond the observable universe remains speculative, and honest scientists say so.",
  ["The bigbang was not an explosion in space; it was the appearance of space.",
   "Redshift shows that distant galaxies are moving away from us.",
   "That expansion is happening everywhere, not from one centre.",
   "The primordial mixture was almost entirely hydrogen and helium.",
   "From the light alone we can discern temperature, speed and age."],
  ["Redshift shows that distant galaxies are moving away from us.",
   "That expansion is happening everywhere, not from one centre.",
   "From the light alone we can discern temperature, speed and age."],
  "Was the bigbang an explosion in space?","No, it was the appearance of space."),

D(370,369,'Extreme Objects','🕳️','Day371_LeavingtheGround_B2.html','🚀','memory',
  'Describing extremes: so dense that / such that nothing can.',
  [('blackhole','หลุมดำ','/ˈblækhəʊl/','🕳️'),('supernova','ซูเปอร์โนวา','/ˌsuːpəˈnəʊvə/','💫'),
   ('neutronstar','ดาวนิวตรอน','/ˈnjuːtrɒnstɑː/','⭐'),('meteor','ดาวตก','/ˈmiːtiə(r)/','🌠'),
   ('magnetosphere','สนามแม่เหล็กโลก','/mæɡˈniːtəsfɪə(r)/','🧲'),('solarwind','ลมสุริยะ','/ˈsəʊləwɪnd/','🌬️'),
   ('ionosphere','ชั้นไอโอโนสเฟียร์','/aɪˈɒnəsfɪə(r)/','🌫️'),('luminous','เปล่งแสงสว่าง','/ˈluːmɪnəs/','🔆'),
   ('collapse','ยุบตัวลง','/kəˈlæps/','⬇️')],
  "A blackhole is not a hole; it is matter packed too tightly to escape from. One supernova can outshine an entire galaxy for a few weeks. A neutronstar packs the mass of the sun into a city. A meteor is the streak of light, not the rock itself. The magnetosphere is an invisible shield around this planet. Without it the solarwind would strip the ionosphere away. Earth keeps its air because of gravity and that magnetic shield together. The most luminous objects we can see are also among the most distant. When a large star runs out of fuel, it will collapse in seconds.",
  ["A blackhole is matter packed too tightly to escape from.",
   "One supernova can outshine an entire galaxy for a few weeks.",
   "A meteor is the streak of light, not the rock itself.",
   "The magnetosphere is an invisible shield around this planet.",
   "When a large star runs out of fuel, it will collapse in seconds."],
  ["A meteor is the streak of light, not the rock itself.",
   "The magnetosphere is an invisible shield around this planet.",
   "One supernova can outshine an entire galaxy."],
  "What is a meteor?","It is the streak of light, not the rock itself."),

D(371,370,'Leaving the Ground','🚀','Day372_MeasuringTime_B2.html','⏱️','wordsearch',
  'Technical sequence: prior to launch / upon separation / once in orbit.',
  [('trajectory','วิถีโคจร','/trəˈdʒektəri/','📈'),('payload','สัมภาระที่ส่งขึ้นไป','/ˈpeɪləʊd/','📦'),
   ('launchpad','ฐานปล่อยจรวด','/ˈlɔːntʃpæd/','🗼'),('weightless','ไร้น้ำหนัก','/ˈweɪtləs/','🪂'),
   ('microgravity','แรงโน้มถ่วงต่ำมาก','/ˌmaɪkrəʊˈɡrævəti/','🪶'),('spacesuit','ชุดอวกาศ','/ˈspeɪssuːt/','🧑‍🚀'),
   ('rover','ยานสำรวจภาคพื้น','/ˈrəʊvə(r)/','🛻'),('docking','การเชื่อมต่อยาน','/ˈdɒkɪŋ/','🔗'),
   ('reentry','การกลับเข้าชั้นบรรยากาศ','/ˌriːˈentri/','🔥')],
  "A rocket does not fly upward; it follows a curved trajectory sideways. Every extra kilogram of payload costs a great deal of fuel. A launchpad is designed to survive being briefly on fire. Astronauts are not weightless because gravity is absent; they are falling around the Earth. Microgravity weakens bone within weeks. A spacesuit is a small spacecraft shaped like a person. A rover on Mars waits minutes for every instruction to arrive. Docking two craft at eight kilometres a second requires astonishing patience. Reentry is the most dangerous ten minutes of any mission.",
  ["A rocket does not fly upward; it follows a curved trajectory sideways.",
   "Every extra kilogram of payload costs a great deal of fuel.",
   "Astronauts are not weightless because gravity is absent.",
   "A spacesuit is a small spacecraft shaped like a person.",
   "Reentry is the most dangerous ten minutes of any mission."],
  ["Every extra kilogram of payload costs a great deal of fuel.",
   "A spacesuit is a small spacecraft shaped like a person.",
   "Reentry is the most dangerous ten minutes of any mission."],
  "What is a spacesuit?","It is a small spacecraft shaped like a person."),

D(372,371,'Measuring Time','⏱️','Day373_TimeandChange_B2.html','🔄','vowels',
  'Precision language: to within / accurate to / no more than.',
  [('chronology','ลำดับเวลา','/krəˈnɒlədʒi/','📜'),('millennium','สหัสวรรษ','/mɪˈleniəm/','🗿'),
   ('epoch','ยุคสมัยทางธรณี','/ˈiːpɒk/','🦴'),('simultaneous','ที่เกิดขึ้นพร้อมกัน','/ˌsɪmlˈteɪniəs/','⏸️'),
   ('duration','ช่วงเวลาที่กินไป','/djuˈreɪʃn/','📶'),('synchronise','ทำให้ตรงกัน','/ˈsɪŋkrənaɪz/','🔃'),
   ('calibrate','ปรับเทียบให้แม่นยำ','/ˈkælɪbreɪt/','🎚️'),('sundial','นาฬิกาแดด','/ˈsʌndaɪəl/','🌞'),
   ('hourglass','นาฬิกาทราย','/ˈaʊəɡlɑːs/','⏳')],
  "A clear chronology is the first thing a historian builds and the last thing a reader notices. A millennium is a thousand years, which sounds long until you meet geology. An epoch in geology can last several million years. Two events that look simultaneous here may not be simultaneous elsewhere. The duration of a day has not always been twenty four hours. Satellites must synchronise their clocks to within billionths of a second. Any instrument must calibrate against something more reliable than itself. A sundial keeps solar time and cannot help you at night. An hourglass measures a fixed duration and nothing else, which is its charm.",
  ["A clear chronology is the first thing a historian builds.",
   "An epoch in geology can last several million years.",
   "The duration of a day has not always been twenty four hours.",
   "Satellites must synchronise their clocks to within billionths of a second.",
   "A sundial keeps solar time and cannot help you at night."],
  ["An epoch in geology can last several million years.",
   "The duration of a day has not always been twenty four hours.",
   "A sundial keeps solar time and cannot help you at night."],
  "How long can a geological epoch last?","It can last several million years."),

D(373,372,'Time and Change','🔄','Day374_Week54Review_B2.html','⭐','tiles',
  'Talking about permanence: for the time being / in perpetuity / fleetingly.',
  [('prehistoric','ก่อนประวัติศาสตร์','/ˌpriːhɪˈstɒrɪk/','🦕'),('medieval','ยุคกลาง','/ˌmediˈiːvl/','🏰'),
   ('contemporary','ร่วมสมัย','/kənˈtemprəri/','🕶️'),('cyclical','เป็นวัฏจักร','/ˈsɪklɪkl/','♻️'),
   ('perpetual','ต่อเนื่องไม่สิ้นสุด','/pəˈpetʃuəl/','♾️'),('transient','ชั่วครู่ชั่วยาม','/ˈtrænziənt/','🍂'),
   ('ephemeral','อยู่ได้ไม่นาน','/ɪˈfemərəl/','🫧'),('extrapolate','คาดการณ์ต่อจากแนวโน้ม','/ɪkˈstræpəleɪt/','📉'),
   ('futurology','อนาคตศาสตร์','/ˌfjuːtʃəˈrɒlədʒi/','🔮')],
  "Prehistoric simply means before anybody wrote anything down. The medieval world was far less dark than the name suggests. Contemporary art is often disliked and later becomes the classic. Many cultures see time as cyclical rather than as a straight line. Nothing physical is truly perpetual, though some things outlast every witness. A transient fashion can still change a language permanently. An ephemeral post may be screenshotted and last for decades. It is tempting to extrapolate a straight line from three points. Futurology is mostly the study of how badly the past predicted us.",
  ["Prehistoric simply means before anybody wrote anything down.",
   "Many cultures see time as cyclical rather than as a straight line.",
   "A transient fashion can still change a language permanently.",
   "It is tempting to extrapolate a straight line from three points.",
   "Contemporary art is often disliked and later becomes the classic."],
  ["Prehistoric means before anybody wrote anything down.",
   "A transient fashion can still change a language permanently.",
   "It is tempting to extrapolate a straight line from three points."],
  "What does prehistoric mean?","It means before anybody wrote anything down."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
