# -*- coding: utf-8 -*-
# Level 7 · B1 · Week 31 Stories & Literature (195–201) · Week 32 Growing Up (202–208) + 209–210
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level7/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta, theme='Stories'):
    return dict(n=n, prev=prev, level=7, cefr='B1', title=title, emoji=emoji, theme=theme,
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(195,194,'Inside a Novel','📖','Day196_WordsThatPaint_B1.html','🎨','tiles',
  'Narrative tenses: past simple for events, past continuous for background.',
  [('novel','นวนิยาย','/ˈnɒvl/','📕'),('author','ผู้แต่ง','/ˈɔːθə(r)/','✍️'),
   ('chapter','บท','/ˈtʃæptə(r)/','🔖'),('plot','โครงเรื่อง','/plɒt/','🧵'),
   ('fiction','เรื่องแต่ง','/ˈfɪkʃn/','🐉'),('narrator','ผู้เล่าเรื่อง','/nəˈreɪtə(r)/','🎙️'),
   ('genre','ประเภทวรรณกรรม','/ˈʒɒnrə/','🗂️'),('summary','บทสรุป','/ˈsʌməri/','📄')],
  "Mimi finished a long novel over the weekend. The author wrote it more than fifty years ago. Each chapter ended with a small surprise. While she was reading, the plot suddenly changed. This kind of fiction is her favourite genre. The narrator was a clever old cat! She wrote a short summary for the class.",
  ["Mimi finished a long novel over the weekend.",
   "The author wrote it more than fifty years ago.",
   "Each chapter ended with a small surprise.",
   "While she was reading, the plot suddenly changed.",
   "She wrote a short summary for the class."],
  ["The author wrote it more than fifty years ago.",
   "While she was reading, the plot suddenly changed.",
   "She wrote a short summary for the class."],
  "Who was the narrator of the novel?","The narrator was a clever old cat."),

D(196,195,'Words That Paint','🎨','Day197_OldTales_B1.html','🏺','scramble',
  'Similes: as brave as a lion / like a river of light.',
  [('poetry','บทกวี','/ˈpəʊətri/','🕊️'),('rhyme','สัมผัสคำ','/raɪm/','🎵'),
   ('metaphor','อุปมาอุปไมย','/ˈmetəfə(r)/','🪄'),('imagination','จินตนาการ','/ɪˌmædʒɪˈneɪʃn/','💭'),
   ('vivid','ชัดเจนมีชีวิตชีวา','/ˈvɪvɪd/','🌈'),('describe','บรรยาย','/dɪˈskraɪb/','🖌️'),
   ('emotion','อารมณ์ความรู้สึก','/ɪˈməʊʃn/','💗'),('original','มีเอกลักษณ์','/əˈrɪdʒənl/','📤')],
  "Good poetry can paint a picture with only ten words. Ben learned that rhyme makes a line easier to remember. A metaphor says one thing is another: the city is a jungle. Imagination turns an ordinary street into a kingdom. Use vivid words to describe what you see. Poems carry emotion better than long explanations. Everyone can be original in their own way.",
  ["Good poetry can paint a picture with ten words.",
   "Rhyme makes a line easier to remember.",
   "Imagination turns an ordinary street into a kingdom.",
   "Use vivid words to describe what you see.",
   "Poems carry emotion better than long explanations."],
  ["Rhyme makes a line easier to remember.",
   "Use vivid words to describe what you see.",
   "Poems carry emotion better than long explanations."],
  "What does a metaphor do?","It says one thing is another."),

D(197,196,'Old Tales','🏺','Day198_WhoAmI_B1.html','🪞','memory',
  'Past perfect: The village had suffered for years before the hero arrived.',
  [('legend','ตำนาน','/ˈledʒənd/','🐲'),('myth','เทพนิยาย','/mɪθ/','⚡'),
   ('ancestor','บรรพบุรุษ','/ˈænsestə(r)/','🌳'),('moral','ข้อคิดสอนใจ','/ˈmɒrəl/','📿'),
   ('wisdom','ปัญญา','/ˈwɪzdəm/','🦉'),('symbol','สัญลักษณ์','/ˈsɪmbl/','🔱'),
   ('folklore','คติชนพื้นบ้าน','/ˈfəʊklɔː(r)/','↕️'),('preserve','อนุรักษ์','/prɪˈzɜːv/','🏛️')],
  "Grandma told an old legend about a golden fish. In this myth the river spirit granted three wishes. Our ancestor passed the story from mouth to mouth. Every tale carries a quiet moral at the end. Old folklore still teaches us wisdom today. The fish is a symbol of patience and luck. We must preserve these stories for the next generation.",
  ["Grandma told an old legend about a golden fish.",
   "Our ancestor passed the story from mouth to mouth.",
   "Every tale carries a quiet moral at the end.",
   "The fish is a symbol of patience and luck.",
   "We must preserve these stories."],
  ["Our ancestor passed the story from mouth to mouth.",
   "The fish is a symbol of patience and luck.",
   "We must preserve these stories."],
  "What is the fish a symbol of?","It is a symbol of patience and luck."),

D(198,197,'Who Am I?','🪞','Day199_FeelingsInside_B1.html','💗','wordsearch',
  'Reflexive pronouns: myself, yourself, herself, ourselves.',
  [('identity','ตัวตน','/aɪˈdentəti/','🪪'),('personality','บุคลิกภาพ','/ˌpɜːsəˈnæləti/','🎭'),
   ('introvert','คนชอบอยู่เงียบ','/ˈɪntrəvɜːt/','🤫'),('extrovert','คนชอบเข้าสังคม','/ˈekstrəvɜːt/','🎉'),
   ('unique','ไม่เหมือนใคร','/juˈniːk/','❄️'),('assured','เชื่อมั่นในตัวเอง','/əˈʃʊəd/','🤗'),
   ('doubt','สงสัยในตัวเอง','/daʊt/','⚖️'),('discovery','การค้นพบ','/dɪˈskʌvəri/','🌱')],
  "Your identity is more than your name. Personality is the way you meet the world. An introvert enjoys quiet time to recharge. An extrovert finds energy in a crowd. Neither one is better than the other. Every person is unique in some way. Do not doubt yourself all the time. Feel assured first, and knowing who you are becomes a happy discovery.",
  ["Your identity is more than your name.",
   "Personality is the way you meet the world.",
   "An introvert enjoys quiet time to recharge.",
   "Every person is unique in some way.",
   "Feel assured first and it becomes a happy discovery."],
  ["Personality is the way you meet the world.",
   "Every person is unique in some way.",
   "Feel assured first and it becomes a happy discovery."],
  "Where does an extrovert find energy?","An extrovert finds energy in a crowd."),

D(199,198,'Feelings Inside','💗','Day200_GrowingUp_B1.html','🌱','vowels',
  'Verb + gerund: I enjoy talking. She avoids arguing.',
  [('empathy','ความเห็นอกเห็นใจ','/ˈempəθi/','🫂'),('anxiety','ความวิตกกังวล','/æŋˈzaɪəti/','😰'),
   ('temper','อารมณ์ร้อน','/ˈtempə(r)/','🌡️'),('reflect','ใคร่ครวญ','/rɪˈflekt/','🧘'),
   ('confide','ระบายความในใจ','/kənˈfaɪd/','🗨️'),('reassure','ทำให้อุ่นใจ','/ˌriːəˈʃʊə(r)/','🤝'),
   ('overwhelm','ท่วมท้นจนรับไม่ไหว','/ˌəʊvəˈwelm/','🌊'),('resilience','ความยืดหยุ่นทางใจ','/rɪˈzɪliəns/','⚖️')],
  "Empathy means feeling what another person feels. Before a test anxiety can overwhelm anyone. Ben learned to control his temper by counting to ten. Take five minutes each evening to reflect. It helps to confide in someone instead of hiding it. A good friend will reassure you without judging. Resilience is built one habit at a time.",
  ["Empathy means feeling what another person feels.",
   "Before a test anxiety can overwhelm anyone.",
   "Ben learned to control his temper.",
   "Take five minutes each evening to reflect.",
   "Resilience is built one habit at a time."],
  ["Before a test anxiety can overwhelm anyone.",
   "Take five minutes each evening to reflect.",
   "Resilience is built one habit at a time."],
  "How did Ben control his temper?","He controlled it by counting to ten."),

D(200,199,'Growing Up','🌱','Day201_Week31Review_B1.html','⭐','tiles',
  'Used to vs would: I used to be shy. We would play in the yard for hours.',
  [('maturity','วุฒิภาวะ','/məˈtʃʊərəti/','🧗'),('independence','ความเป็นตัวของตัวเอง','/ˌɪndɪˈpendəns/','🦅'),
   ('teenager','วัยรุ่น','/ˈtiːneɪdʒə(r)/','🧑'),('guardian','ผู้ปกครอง','/ˈɡɑːdiən/','👨‍🏫'),
   ('setback','อุปสรรค','/ˈsetbæk/','🔁'),('privilege','สิทธิพิเศษ','/ˈprɪvəlɪdʒ/','🎟️'),
   ('boundary','ขอบเขต','/ˈbaʊndri/','🚧'),('gradually','ทีละน้อย','/ˈɡrædʒuəli/','📶')],
  "Maturity is not about age but about choices. A teenager wants more independence every year. With freedom comes a clear boundary too. Talk to a guardian you trust when something feels wrong. Every setback teaches more than a perfect score. Extra time online is a privilege, not a right. We all grow gradually, one honest step at a time.",
  ["Maturity is not about age but about choices.",
   "A teenager wants more independence every year.",
   "With freedom comes a clear boundary too.",
   "Extra time online is a privilege, not a right.",
   "We all grow gradually, one honest step at a time."],
  ["A teenager wants more independence every year.",
   "Extra time online is a privilege, not a right.",
   "We all grow gradually, one honest step at a time."],
  "What comes with freedom?","A clear boundary comes with freedom."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B1.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace('?',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']),'คำ')
