# -*- coding: utf-8 -*-
# Level 14 · B2 · Week 59 Leading, Working & Negotiating (Day 405–410) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level14/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=14, cefr='B2', title=title, emoji=emoji, theme='Leading & Working',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(405,404,'Leading People','🧭','Day406_HowTeamsWork_B2.html','👥','tiles',
  'Management advice: rather than / instead of -ing / the temptation is to.',
  [('morale','ขวัญกำลังใจ','/məˈrɑːl/','🎈'),('cohesion','ความเป็นน้ำหนึ่งใจเดียว','/kəʊˈhiːʒn/','🧲'),
   ('micromanage','จู้จี้ควบคุมทุกขั้นตอน','/ˈmaɪkrəʊmænɪdʒ/','🔬'),('incentivise','สร้างแรงจูงใจด้วยรางวัล','/ɪnˈsentɪvaɪz/','🥕'),
   ('onboarding','การรับคนใหม่เข้างาน','/ˈɒnbɔːdɪŋ/','🚪'),('attrition','อัตราการลาออก','/əˈtrɪʃn/','📉'),
   ('succession','การวางตัวผู้สืบทอด','/səkˈseʃn/','🪜'),('facilitate','ช่วยให้การประชุมเดินหน้า','/fəˈsɪlɪteɪt/','🎤'),
   ('tactful','มีชั้นเชิงถนอมน้ำใจ','/ˈtæktfl/','🕊️')],
  "Morale is destroyed by small unfairness far more often than by hard work. Cohesion grows when a team survives something difficult together. Managers who micromanage produce staff who stop deciding anything. To incentivise the wrong number is to guarantee the wrong behaviour. Good onboarding in week one saves six months of confusion. High attrition is a symptom, and the cause is usually one level above. Succession planning is the least urgent and most important task a leader has. To facilitate a meeting is to make room for the quiet person. A tactful correction is remembered; a public one is only resented.",
  ["Morale is destroyed by small unfairness far more often than by hard work.",
   "Cohesion grows when a team survives something difficult together.",
   "Good onboarding in week one saves six months of confusion.",
   "To facilitate a meeting is to make room for the quiet person.",
   "A tactful correction is remembered; a public one is only resented."],
  ["Cohesion grows when a team survives something difficult together.",
   "Good onboarding in week one saves six months of confusion.",
   "To facilitate a meeting is to make room for the quiet person."],
  "What destroys morale most often?","Small unfairness, far more often than hard work."),

D(406,405,'How Teams Work','👥','Day407_RunningaProject_B2.html','📋','scramble',
  'Organisational description: reports to / sits within / cuts across.',
  [('hierarchy','ลำดับชั้นบังคับบัญชา','/ˈhaɪərɑːki/','🔺'),('silo','การทำงานแยกส่วนไม่คุยกัน','/ˈsaɪləʊ/','🗄️'),
   ('crossfunctional','ข้ามสายงาน','/ˌkrɒsˈfʌŋkʃənl/','🔀'),('alignment','ความเข้าใจตรงกัน','/əˈlaɪnmənt/','📐'),
   ('stakeholder','ผู้มีส่วนได้ส่วนเสีย','/ˈsteɪkhəʊldə(r)/','🤝'),('escalate','ส่งเรื่องขึ้นระดับสูงกว่า','/ˈeskəleɪt/','⬆️'),
   ('retrospective','การทบทวนหลังงานเสร็จ','/ˌretrəˈspektɪv/','🔙'),('norms','บรรทัดฐานที่ทีมยึดถือ','/nɔːmz/','🌱'),
   ('rapport','ความสัมพันธ์อันดี','/ræˈpɔː(r)/','☕')],
  "A flat hierarchy still has power in it; it is simply harder to see. A silo forms whenever two teams stop needing each other's approval. A crossfunctional group solves in one room what four emails cannot. Alignment means everyone can state the goal in the same words. Every stakeholder should be identified before the plan, not after the complaint. Escalate early and calmly; escalating late looks like blame. A blameless retrospective finds five times as many real causes. Team norms are what happen when the manager is on holiday. Rapport is built in the five minutes before a meeting starts.",
  ["A flat hierarchy still has power in it; it is simply harder to see.",
   "A crossfunctional group solves in one room what four emails cannot.",
   "Alignment means everyone can state the goal in the same words.",
   "Team norms are what happen when the manager is on holiday.",
   "Rapport is built in the five minutes before a meeting starts."],
  ["Alignment means everyone can state the goal in the same words.",
   "Team norms are what happen when the manager is on holiday.",
   "Rapport is built in the five minutes before a meeting starts."],
  "What are team norms?","It is what happens when the manager is on holiday."),

D(407,406,'Running a Project','📋','Day408_AttheTable_B2.html','🤝','memory',
  'Planning language: is due by / is contingent on / is out of scope.',
  [('deliverable','สิ่งที่ต้องส่งมอบ','/dɪˈlɪvərəbl/','📦'),('scopecreep','งานบานปลายเกินขอบเขต','/ˈskəʊpkriːp/','🌊'),
   ('fallback','แผนสำรองเมื่อพลาด','/ˈfɔːlbæk/','🪂'),('dependency','งานที่ต้องรอกันก่อน','/dɪˈpendənsi/','⛓️'),
   ('bottleneck','จุดคอขวด','/ˈbɒtlnek/','🍾'),('roadmap','แผนที่นำทางโครงการ','/ˈrəʊdmæp/','🗺️'),
   ('forecasting','การคาดการณ์เวลางาน','/ˈfɔːkɑːstɪŋ/','🔢'),('buffer','เวลาเผื่อ','/ˈbʌfə(r)/','🧷'),
   ('postmortem','การถอดบทเรียนหลังปัญหา','/ˌpəʊstˈmɔːtəm/','🔍')],
  "A deliverable is something someone else can check, not something you feel is done. Scopecreep never arrives as one large request; it arrives as nine small ones. A fallback is a plan you hope to waste. One unnoticed dependency can hold up eleven finished tasks. Find the bottleneck before optimising anything else. A roadmap shows direction; it is not a promise about dates. Honest forecasting carries the confidence attached to it. A schedule with no buffer is a schedule that has already failed. A postmortem should ask what the system allowed, not who was careless.",
  ["A deliverable is something someone else can check.",
   "Scopecreep arrives as nine small requests, not one large one.",
   "A fallback is a plan you hope to waste.",
   "Find the bottleneck before optimising anything else.",
   "A schedule with no buffer is a schedule that has already failed."],
  ["A fallback is a plan you hope to waste.",
   "Find the bottleneck before optimising anything else.",
   "A schedule with no buffer has already failed."],
  "What is a fallback?","It is a plan you hope to waste."),

D(408,407,'At the Table','🤝','Day409_WhenTalksStall_B2.html','🧊','wordsearch',
  'Negotiation language: we would be prepared to / on the condition that.',
  [('bargaining','การต่อรอง','/ˈbɑːɡɪnɪŋ/','⚖️'),('concession','การยอมลดให้','/kənˈseʃn/','🎁'),
   ('counteroffer','ข้อเสนอโต้กลับ','/ˈkaʊntərɒfə(r)/','↩️'),('anchor','ตัวเลขตั้งต้นที่ยึดใจ','/ˈæŋkə(r)/','⚓'),
   ('walkaway','จุดที่พร้อมเดินจากโต๊ะ','/ˈwɔːkəweɪ/','🚶'),('reciprocate','ตอบแทนกลับ','/rɪˈsɪprəkeɪt/','🔁'),
   ('goodwill','ไมตรีจิต','/ˌɡʊdˈwɪl/','💚'),('winwin','ได้ประโยชน์ทั้งสองฝ่าย','/ˌwɪnˈwɪn/','🤗'),
   ('zerosum','ฝ่ายหนึ่งได้อีกฝ่ายเสีย','/ˈzɪərəʊsʌm/','➖')],
  "Bargaining begins long before anyone mentions a number. Never make a concession without asking for something in return. A counteroffer keeps the conversation alive better than a refusal does. The first number spoken becomes the anchor, fairly or not. Know your walkaway point before you enter the room. If they move and you never reciprocate, they will stop moving. Goodwill built over years is spent in a single greedy afternoon. A winwin is not a compromise; it is finding what each side values differently. Very few situations are truly zerosum, though many are argued as if they were.",
  ["Bargaining begins long before anyone mentions a number.",
   "Never make a concession without asking for something in return.",
   "The first number spoken becomes the anchor, fairly or not.",
   "Know your walkaway point before you enter the room.",
   "Goodwill built over years is spent in a single greedy afternoon."],
  ["Never make a concession without asking for something in return.",
   "Know your walkaway point before you enter the room.",
   "Goodwill built over years is spent in a single greedy afternoon."],
  "What should you know before entering the room?","Know your walkaway point."),

D(409,408,'When Talks Stall','🧊','Day410_TheLongGame_B2.html','⏳','vowels',
  'Deadlock language: we appear to have reached / it may help if.',
  [('stalemate','ภาวะคุมเชิงไปไม่ได้','/ˈsteɪlmeɪt/','♟️'),('impasse','ทางตัน','/ˈæmpɑːs/','🚧'),
   ('ultimatum','คำขาด','/ˌʌltɪˈmeɪtəm/','⏰'),('mediator','ผู้ไกล่เกลี่ย','/ˈmiːdieɪtə(r)/','🫱'),
   ('arbitrator','อนุญาโตตุลาการ','/ˈɑːbɪtreɪtə(r)/','👨‍⚖️'),('assertiveness','ความกล้าแสดงจุดยืน','/əˈsɜːtɪvnəs/','🗣️'),
   ('cutoff','จุดตัดเวลาเจรจา','/ˈkʌtɒf/','📅'),('facesaving','การรักษาหน้าให้อีกฝ่าย','/ˈfeɪsseɪvɪŋ/','🎭'),
   ('deescalate','ลดระดับความตึงเครียด','/ˌdiːˈeskəleɪt/','🧯')],
  "A stalemate is not failure; it is information about what matters most. At an impasse, change the shape of the problem rather than the volume. An ultimatum removes every option except obedience and refusal. A neutral mediator suggests; nobody has to accept. An arbitrator decides, and both sides agreed in advance to accept it. Assertiveness states a need without attacking a person. A real cutoff moves people; a fake one destroys trust once discovered. A facesaving exit lets someone change their mind without looking defeated. To deescalate is to lower the temperature before solving anything.",
  ["A stalemate is not failure; it is information about what matters most.",
   "An ultimatum removes every option except obedience and refusal.",
   "An arbitrator decides, and both sides agreed in advance to accept it.",
   "Assertiveness states a need without attacking a person.",
   "To deescalate is to lower the temperature before solving anything."],
  ["A stalemate is not failure; it is information about what matters most.",
   "Assertiveness states a need without attacking a person.",
   "To deescalate is to lower the temperature before solving anything."],
  "What does assertiveness do?","It states a need without attacking a person."),

D(410,409,'The Long Game','⏳','Day411_Week59Review_B2.html','⭐','tiles',
  'Time horizons: in the long run / in the short term / over the course of.',
  [('longterm','ระยะยาว','/ˌlɒŋˈtɜːm/','🌳'),('shortterm','ระยะสั้น','/ˌʃɔːtˈtɜːm/','⏱️'),
   ('reputation','ชื่อเสียงสั่งสม','/ˌrepjuˈteɪʃn/','🏛️'),('uprightness','ความตรงไปตรงมา','/ˈʌpraɪtnəs/','💎'),
   ('steadiness','ความสม่ำเสมอมั่นคง','/ˈstedinəs/','📏'),('followthrough','การทำจนจบตามที่รับปาก','/ˈfɒləʊθruː/','✅'),
   ('forbearing','ใจเย็นรอได้','/fɔːˈbeərɪŋ/','⏳'),('adaptability','ความสามารถปรับตัว','/əˌdæptəˈbɪləti/','🤸'),
   ('endowment','สิ่งดีที่ส่งต่อให้คนรุ่นถัดไป','/ɪnˈdaʊmənt/','🕯️')],
  "A longterm reputation is built by shortterm decisions nobody was watching. Shortterm pressure is real and is a poor reason to break a promise. Reputation travels faster than any advertisement, in both directions. Uprightness is expensive exactly once, and cheap for the rest of your life. Steadiness beats brilliance in almost every job that lasts. Followthrough is rarer than talent and worth more. A forbearing leader is not passive; they choose the right moment on purpose. Adaptability is what keeps a long career from ending early. The best endowment is a colleague who learned to do it without you.",
  ["A longterm reputation is built by shortterm decisions nobody was watching.",
   "Uprightness is expensive exactly once, and cheap for the rest of your life.",
   "Steadiness beats brilliance in almost every job that lasts.",
   "Followthrough is rarer than talent and worth more.",
   "The best endowment is a colleague who learned to do it without you."],
  ["Uprightness is expensive exactly once.",
   "Steadiness beats brilliance in almost every job that lasts.",
   "The best endowment is a colleague who learned to do it without you."],
  "What beats brilliance in a lasting job?","Steadiness beats brilliance."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
