# -*- coding: utf-8 -*-
# Week 20 — School & Learning (Day 112–118) + Special Times (119–120) · Level 4 · A2
# ทุกคำตรวจแล้วไม่ซ้ำกับ 537 คำเดิม (check_new_words.py)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build

OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level4/'


def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta, theme='School'):
    return dict(n=n, prev=prev, level=4, cefr='A2', title=title, emoji=emoji, theme=theme,
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)


W = [
D(112, 111, 'School Subjects', '📚', 'Day113_InTheClassroom_A2.html', '🙋', 'tiles',
  'Comparing: interesting / more interesting. Use "than" to compare two things.',
  [('subject', 'วิชา', '/ˈsʌbdʒɪkt/', '📗'), ('math', 'คณิตศาสตร์', '/mæθ/', '➗'),
   ('science', 'วิทยาศาสตร์', '/ˈsaɪəns/', '🔬'), ('history', 'ประวัติศาสตร์', '/ˈhɪstri/', '🏛️'),
   ('timetable', 'ตารางเรียน', '/ˈtaɪmteɪbl/', '🗓️'), ('interesting', 'น่าสนใจ', '/ˈɪntrəstɪŋ/', '✨'),
   ('boring', 'น่าเบื่อ', '/ˈbɔːrɪŋ/', '🥱')],
  "The new timetable is on the wall. Which subject do you like best? asked Ben. Leo loves math because he enjoys numbers. Mimi thinks science is more interesting than history. Nothing is boring if you are curious, said the teacher. Every subject opens a new door.",
  ["The new timetable is on the wall.",
   "Which subject do you like best?",
   "Leo loves math because he enjoys numbers.",
   "Mimi thinks science is interesting.",
   "Every subject opens a new door."],
  ["Which subject do you like best?",
   "Leo loves math because he enjoys numbers.",
   "Mimi thinks science is interesting."],
  "Why does Leo love math?", "Because he enjoys numbers."),

D(113, 112, 'In the Classroom', '🙋', 'Day114_HomeworkTime_A2.html', '📝', 'scramble',
  'Past tense: teach becomes taught, understand becomes understood (irregular).',
  [('question', 'คำถาม', '/ˈkwestʃən/', '❓'), ('attention', 'ความตั้งใจ', '/əˈtenʃn/', '👀'),
   ('correct', 'ถูกต้อง', '/kəˈrekt/', '✔️'), ('explain', 'อธิบาย', '/ɪkˈspleɪn/', '🗣️'),
   ('focus', 'มีสมาธิ', '/ˈfəʊkəs/', '🎯'), ('realize', 'ตระหนักได้', '/ˈriːəlaɪz/', '🧠'),
   ('clever', 'ฉลาด', '/ˈklevə(r)/', '🎓')],
  "Ben raised his hand and asked a good question. The teacher gave him her full attention. She began to explain the answer slowly. Everyone tried to focus on the board. That is correct, Ben! Now I realize how it works, he said with a smile. You are all clever when you listen well.",
  ["Ben asked a good question.",
   "The teacher gave him her attention.",
   "She began to explain the answer.",
   "Everyone tried to focus on the board.",
   "Now I realize how it works."],
  ["Ben asked a good question.",
   "She began to explain the answer.",
   "Now I realize how it works."],
  "What did Ben do first?", "He asked a good question."),

D(114, 113, 'Homework Time', '📝', 'Day115_UsingComputers_A2.html', '💻', 'memory',
  'Past tense: spend becomes spent, do becomes did (irregular verbs).',
  [('project', 'ชิ้นงาน', '/ˈprɒdʒekt/', '📋'), ('notebook', 'สมุด', '/ˈnəʊtbʊk/', '📓'),
   ('effort', 'ความพยายาม', '/ˈefət/', '💪'), ('difficult', 'ยาก', '/ˈdɪfɪkəlt/', '🧗'),
   ('complete', 'ทำให้เสร็จ', '/kəmˈpliːt/', '🏁'), ('improve', 'พัฒนาขึ้น', '/ɪmˈpruːv/', '📈'),
   ('prepare', 'เตรียมตัว', '/prɪˈpeə(r)/', '🎒')],
  "Mimi opened her notebook and started the science project. It looked difficult at first. She did not give up. Hard effort makes you improve, said Mum. Leo helped her prepare the drawings. They spent one hour and did their best. Together they complete the work before dinner!",
  ["Mimi opened her notebook.",
   "The project looked difficult at first.",
   "Hard effort makes you improve.",
   "Leo helped her prepare the drawings.",
   "They complete the work before dinner."],
  ["Mimi opened her notebook.",
   "Hard effort makes you improve.",
   "They complete the work before dinner."],
  "Who helped Mimi with the drawings?", "Leo helped her."),

D(115, 114, 'Using Computers', '💻', 'Day116_TestDay_A2.html', '📄', 'wordsearch',
  'Past tense: type becomes typed, click becomes clicked (add -ed).',
  [('screen', 'จอ', '/skriːn/', '🖥️'), ('keyboard', 'แป้นพิมพ์', '/ˈkiːbɔːd/', '⌨️'),
   ('mouse', 'เมาส์', '/maʊs/', '🖱️'), ('internet', 'อินเทอร์เน็ต', '/ˈɪntənet/', '🌐'),
   ('type', 'พิมพ์', '/taɪp/', '✍️'), ('click', 'คลิก', '/klɪk/', '👆'),
   ('search', 'ค้นหา', '/sɜːtʃ/', '🔍')],
  "In the computer room every screen was ready. Ben typed his name on the keyboard. Mimi moved the mouse and clicked the blue button. They used the internet to search for pictures of insects. Type the word carefully, said the teacher. Look at all these beautiful photos!",
  ["Every screen was ready.",
   "Ben typed his name on the keyboard.",
   "Mimi moved the mouse and clicked.",
   "They used the internet to search.",
   "Type the word carefully."],
  ["Ben typed his name on the keyboard.",
   "They used the internet to search.",
   "Type the word carefully."],
  "What did they search for on the internet?", "They searched for pictures of insects."),

D(116, 115, 'Test Day', '📄', 'Day117_ILoveLearning_A2.html', '💡', 'vowels',
  'Past tense: feel becomes felt, think becomes thought (irregular verbs).',
  [('exam', 'การสอบ', '/ɪɡˈzæm/', '📄'), ('pass', 'สอบผ่าน', '/pɑːs/', '🎉'),
   ('fail', 'สอบตก', '/feɪl/', '😔'), ('retry', 'ลองใหม่', '/ˌriːˈtraɪ/', '🔁'),
   ('steady', 'มั่นคง นิ่ง', '/ˈstedi/', '😌'), ('accurate', 'แม่นยำ', '/ˈækjərət/', '✅'),
   ('applaud', 'ปรบมือให้', '/əˈplɔːd/', '👏')],
  "Today was the big exam. Ben felt worried but Leo kept a steady mind. Read every question twice, said the teacher. Mimi checked that her answers were accurate. Ben did not pass this time. Do not worry! If you fail, you can retry next month. His friends applaud him for trying so hard!",
  ["Today was the big exam.",
   "Ben felt worried but Leo kept a steady mind.",
   "Mimi checked that her answers were accurate.",
   "If you fail, you can retry next month.",
   "His friends applaud him for trying."],
  ["Today was the big exam.",
   "Mimi checked that her answers were accurate.",
   "His friends applaud him for trying."],
  "What can Ben do if he fails?", "He can retry next month."),

D(117, 116, 'I Love Learning', '💡', 'Day118_Week20Review_A2.html', '⭐', 'tiles',
  'Future: will + verb. "I will learn something new."',
  [('knowledge', 'ความรู้', '/ˈnɒlɪdʒ/', '📚'), ('idea', 'ความคิด', '/aɪˈdɪə/', '💡'),
   ('curious', 'อยากรู้อยากเห็น', '/ˈkjʊəriəs/', '🤔'), ('wise', 'ฉลาดรอบรู้', '/waɪz/', '🦉'),
   ('achieve', 'บรรลุ', '/əˈtʃiːv/', '🏆'), ('success', 'ความสำเร็จ', '/səkˈses/', '🌟'),
   ('continue', 'ทำต่อไป', '/kənˈtɪnjuː/', '➡️')],
  "Ben is always curious about the world. He asks many questions every day. Knowledge grows when you share it, said the wise old teacher. Mimi had a bright idea for a new club. If we continue to practise, we will achieve our dreams. Small steps lead to big success!",
  ["Ben is always curious about the world.",
   "He asks many questions every day.",
   "Knowledge grows when you share it.",
   "Mimi had a bright idea.",
   "Small steps lead to big success."],
  ["He asks many questions every day.",
   "Knowledge grows when you share it.",
   "Small steps lead to big success."],
  "What did Mimi have?", "She had a bright idea for a new club."),

D(119, 118, 'A Celebration', '🎉', 'Day120_LookingForward_A2.html', '🚀', 'scramble',
  'Past tense: sing becomes sang, bring becomes brought (irregular verbs).',
  [('celebrate', 'ฉลอง', '/ˈselɪbreɪt/', '🥳'), ('festival', 'เทศกาล', '/ˈfestɪvl/', '🎪'),
   ('guest', 'แขก', '/ɡest/', '🧑‍🤝‍🧑'), ('gather', 'มารวมตัวกัน', '/ˈɡæðə(r)/', '💌'),
   ('surprise', 'เซอร์ไพรส์', '/səˈpraɪz/', '🎁'), ('enjoy', 'สนุกกับ', '/ɪnˈdʒɔɪ/', '😄'),
   ('cheer', 'ส่งเสียงเชียร์', '/tʃɪə(r)/', '📣')],
  "The school held a festival to celebrate the end of term. Leo helped gather every guest at the gate. Mimi brought a big surprise cake. Everyone began to cheer when the music started. They sang together and enjoyed the whole afternoon. What a wonderful day!",
  ["The school held a festival.",
   "Leo helped gather every guest at the gate.",
   "Mimi brought a big surprise cake.",
   "Everyone began to cheer.",
   "They enjoyed the whole afternoon."],
  ["Leo helped gather every guest at the gate.",
   "Mimi brought a big surprise cake.",
   "They enjoyed the whole afternoon."],
  "What did Mimi bring to the festival?", "She brought a big surprise cake.", 'Special'),

D(120, 119, 'Looking Forward', '🚀', '../dashboard.html', '🏠', 'memory',
  'Future: will + verb. Look ahead: "We will begin Level 5!"',
  [('award', 'รางวัล', '/əˈwɔːd/', '🏅'), ('medal', 'เหรียญ', '/ˈmedl/', '🥇'),
   ('reward', 'ผลตอบแทน', '/rɪˈwɔːd/', '🎖️'), ('ahead', 'ข้างหน้า', '/əˈhed/', '🛤️'),
   ('ceremony', 'พิธี', '/ˈserəməni/', '🎗️'), ('honour', 'เกียรติ', '/ˈɒnə(r)/', '🏵️'),
   ('forward', 'ไปข้างหน้า', '/ˈfɔːwəd/', '🛫')],
  "At the ceremony the head teacher gave each child an award. Ben received a bright medal for his effort. Hard work always brings a reward, she said. It is an honour to stand with my friends, said Leo. A long road lies ahead of us. We will keep moving forward together. Level 5, here we come!",
  ["The head teacher gave each child an award.",
   "Ben received a bright medal.",
   "Hard work always brings a reward.",
   "It is an honour to stand with my friends, said Leo.",
   "A long road lies ahead of us."],
  ["Ben received a bright medal.",
   "Hard work always brings a reward.",
   "A long road lies ahead of us."],
  "What did Ben receive at the ceremony?", "He received a bright medal.", 'Special'),
]

for d in W:
    out = build(d)
    fn = 'Day%d_%s_A2.html' % (d['n'], d['title'].replace(' ', '').replace("'", ''))
    open(OUT + fn, 'w', encoding='utf-8').write(out)
    leak = out.count('Day 61') + out.count('wla_d61') + out.count('Happy Feelings')
    print('%s %s leak=%d' % ('OK' if leak == 0 else 'WARN', fn, leak))
