# -*- coding: utf-8 -*-
# Level 14 · B2 · Week 57 Language & Words (Day 391–396) — 9 คำ/วัน
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from golden_generator import build
OUT = '/sessions/wonderful-magical-bohr/mnt/English/Level14/'

def D(n, prev, title, emoji, nf, ne, game, grammar, words, story, ss, ds, tq, ta):
    return dict(n=n, prev=prev, level=14, cefr='B2', title=title, emoji=emoji, theme='Language',
                next_file=nf, next_emoji=ne, game=game, grammar=grammar, words=words, story=story,
                ss=ss, ds=ds, think_q=tq, think_a=ta)

W = [
D(391,390,'The Study of Language','🔤','Day392_HowWordsAreBuilt_B2.html','🧱','tiles',
  'Defining a field: is concerned with / deals with / seeks to explain.',
  [('linguistics','ภาษาศาสตร์','/lɪŋˈɡwɪstɪks/','🔤'),('phonetics','สัทศาสตร์','/fəˈnetɪks/','👄'),
   ('phoneme','หน่วยเสียง','/ˈfəʊniːm/','🔉'),('semantics','อรรถศาสตร์','/sɪˈmæntɪks/','💭'),
   ('pragmatics','วัจนปฏิบัติศาสตร์','/præɡˈmætɪks/','🤝'),('lexicon','คลังคำของภาษา','/ˈleksɪkən/','📚'),
   ('etymology','นิรุกติศาสตร์','/ˌetɪˈmɒlədʒi/','🌳'),('cognate','คำร่วมรากภาษา','/ˈkɒɡnət/','👯'),
   ('loanword','คำยืมจากภาษาอื่น','/ˈləʊnwɜːd/','🧳')],
  "Linguistics studies language the way biology studies life. Phonetics describes the sounds a mouth can actually make. A phoneme is a sound that changes meaning: pat and bat differ by one. Semantics asks what a sentence means; pragmatics asks what the speaker meant by it. The lexicon of English is unusually large because it borrowed so freely. Etymology often shows that a familiar word once meant something surprising. A cognate is a word two languages inherited from the same ancestor. A loanword arrives with the thing it names and stays forever.",
  ["Linguistics studies language the way biology studies life.",
   "A phoneme is a sound that changes meaning.",
   "Semantics asks what a sentence means.",
   "The lexicon of English is unusually large because it borrowed so freely.",
   "A loanword arrives with the thing it names and stays forever."],
  ["A phoneme is a sound that changes meaning.",
   "Semantics asks what a sentence means.",
   "A loanword arrives with the thing it names and stays forever."],
  "What does a phoneme do?","It is a sound that changes meaning."),

D(392,391,'How Words Are Built','🧱','Day393_TheShapeofaSentence_B2.html','📐','scramble',
  'Word formation: by adding / is derived from / takes the form of.',
  [('morpheme','หน่วยคำ','/ˈmɔːfiːm/','🧩'),('morphology','วิทยาหน่วยคำ','/mɔːˈfɒlədʒi/','🔬'),
   ('affix','หน่วยคำเติม','/ˈæfɪks/','📎'),('prefix','อุปสรรค','/ˈpriːfɪks/','⬅️'),
   ('suffix','ปัจจัยท้ายคำ','/ˈsʌfɪks/','➡️'),('inflection','การผันคำ','/ɪnˈflekʃn/','🔄'),
   ('neologism','คำเกิดใหม่','/niˈɒlədʒɪzəm/','✨'),('coinage','การประดิษฐ์คำใหม่','/ˈkɔɪnɪdʒ/','🪙'),
   ('archaic','โบราณเลิกใช้แล้ว','/ɑːˈkeɪɪk/','🏺')],
  "A morpheme is the smallest piece of a word that still carries meaning. Morphology explains why unhappiness has three parts and not one. An affix is anything you attach to a root. A prefix goes before, and a suffix goes after. English has lost most of its inflection, which is why word order matters so much. A neologism is a word younger than the person using it. Every coinage sounds ridiculous for about ten years. An archaic word survives in poems and in legal documents.",
  ["A morpheme is the smallest piece of a word that still carries meaning.",
   "A prefix goes before, and a suffix goes after.",
   "English has lost most of its inflection.",
   "A neologism is a word younger than the person using it.",
   "Every coinage sounds ridiculous for about ten years."],
  ["A prefix goes before, and a suffix goes after.",
   "A neologism is a word younger than the person using it.",
   "Every coinage sounds ridiculous for about ten years."],
  "What is a neologism?","A word younger than the person using it."),

D(393,392,'The Shape of a Sentence','📐','Day394_ManyEnglishes_B2.html','🌏','memory',
  'Grammar description: functions as / agrees with / is governed by.',
  [('syntax','วากยสัมพันธ์','/ˈsɪntæks/','📐'),('subordinate','อนุประโยครอง','/səˈbɔːdɪnət/','🔗'),
   ('modifier','ส่วนขยาย','/ˈmɒdɪfaɪə(r)/','🖌️'),('determiner','คำนำหน้านาม','/dɪˈtɜːmɪnə(r)/','1️⃣'),
   ('preposition','บุพบท','/ˌprepəˈzɪʃn/','📍'),('conjunction','คำเชื่อม','/kənˈdʒʌŋkʃn/','➕'),
   ('ambiguity','ความกำกวม','/ˌæmbɪˈɡjuːəti/','🌫️'),('polysemy','ความหมายหลากหลายของคำเดียว','/pəˈlɪsəmi/','🎭'),
   ('homophone','คำพ้องเสียง','/ˈhɒməfəʊn/','👂')],
  "Syntax is the set of rules that decides which orders are possible. A subordinate clause cannot stand alone, however long it is. A modifier belongs as close as possible to what it modifies. A determiner tells you which one and how many. A preposition is the hardest part of any language to learn and the easiest to hear wrong. A conjunction joins two ideas and quietly says how they relate. Ambiguity is usually accidental and occasionally the whole point of a joke. Polysemy means one word carrying several related meanings at once. A homophone sounds identical and is spelled differently.",
  ["Syntax is the set of rules that decides which orders are possible.",
   "A subordinate clause cannot stand alone.",
   "A modifier belongs as close as possible to what it modifies.",
   "A conjunction joins two ideas and quietly says how they relate.",
   "A homophone sounds identical and is spelled differently."],
  ["A subordinate clause cannot stand alone.",
   "A modifier belongs as close as possible to what it modifies.",
   "A homophone sounds identical and is spelled differently."],
  "What is a homophone?","A word that sounds identical and is spelled differently."),

D(394,393,'Many Englishes','🌏','Day395_HowLanguagesChange_B2.html','⏳','wordsearch',
  'Variation: varies according to / is characteristic of / is typical among.',
  [('vernacular','ภาษาพูดพื้นถิ่น','/vəˈnækjələ(r)/','🏘️'),('jargon','ศัพท์เฉพาะวงการ','/ˈdʒɑːɡən/','🧑‍⚕️'),
   ('slang','คำสแลง','/slæŋ/','😎'),('creole','ภาษาครีโอล','/ˈkriːəʊl/','🌴'),
   ('pidgin','ภาษาผสมเพื่อสื่อสาร','/ˈpɪdʒɪn/','⚓'),('multilingual','ใช้ได้หลายภาษา','/ˌmʌltiˈlɪŋɡwəl/','🗺️'),
   ('standardise','ทำให้เป็นมาตรฐาน','/ˈstændədaɪz/','📏'),('orthography','ระบบการสะกด','/ɔːˈθɒɡrəfi/','✒️'),
   ('transliterate','ถอดเสียงเป็นอีกอักษร','/trænsˈlɪtəreɪt/','🔁')],
  "The vernacular of a neighbourhood is a real grammar, not a broken one. Jargon is useful inside a profession and rude outside it. Slang dates a speaker faster than any photograph. A creole begins as a pidgin and becomes a full language within a generation. A pidgin is invented by adults who need to trade tomorrow. Most of the world is multilingual; monolingual countries are the unusual ones. To standardise a spelling is a political act as much as a practical one. English orthography records how words sounded five centuries ago. To transliterate a name is to keep the sound and change the letters.",
  ["The vernacular of a neighbourhood is a real grammar, not a broken one.",
   "Jargon is useful inside a profession and rude outside it.",
   "A creole begins as a pidgin and becomes a full language within a generation.",
   "Most of the world is multilingual.",
   "To transliterate a name is to keep the sound and change the letters."],
  ["Jargon is useful inside a profession and rude outside it.",
   "Most of the world is multilingual.",
   "To transliterate a name is to keep the sound and change the letters."],
  "Is the vernacular a broken grammar?","No, it is a real grammar."),

D(395,394,'How Languages Change','⏳','Day396_SpeakingClearly_B2.html','🗣️','vowels',
  'Gradual change: over successive generations / little by little.',
  [('bilingualism','ภาวะสองภาษา','/baɪˈlɪŋɡwəlɪzəm/','🔀'),('logogram','อักษรภาพแทนคำ','/ˈlɒɡəɡræm/','🈳'),
   ('syllabary','ระบบอักษรพยางค์','/ˈsɪləbəri/','🔡'),('alphabet','ตัวอักษร','/ˈælfəbet/','🔠'),
   ('punctuation','เครื่องหมายวรรคตอน','/ˌpʌŋktʃuˈeɪʃn/','❕'),('apostrophe','เครื่องหมายอะพอสทรอฟี','/əˈpɒstrəfi/','✏️'),
   ('semicolon','อัฒภาค','/ˌsemiˈkəʊlən/','⏸️'),('parenthesis','วงเล็บ','/pəˈrenθəsɪs/','🫧'),
   ('hyphen','ยัติภังค์','/ˈhaɪfn/','➖')],
  "Bilingualism in childhood costs nothing and pays for sixty years. A logogram stands for a whole word rather than a sound. A syllabary gives one symbol to each syllable. An alphabet needs only a few dozen symbols to write anything at all. Punctuation was invented to help people read aloud. The apostrophe is the most argued about mark in English. A semicolon joins two sentences that did not want to separate. A parenthesis is an aside the writer could not resist. A hyphen changes a small firm into something quite different from a small business.",
  ["Bilingualism in childhood costs nothing and pays for sixty years.",
   "A logogram stands for a whole word rather than a sound.",
   "An alphabet needs only a few dozen symbols to write anything at all.",
   "Punctuation was invented to help people read aloud.",
   "A semicolon joins two sentences that did not want to separate."],
  ["A logogram stands for a whole word rather than a sound.",
   "Punctuation was invented to help people read aloud.",
   "A semicolon joins two sentences that did not want to separate."],
  "Why was punctuation invented?","To help people read aloud."),

D(396,395,'Speaking Clearly','🗣️','Day397_Week57Review_B2.html','⭐','tiles',
  'Advice on delivery: try to / avoid -ing / it helps if you.',
  [('enunciate','ออกเสียงให้ชัด','/ɪˈnʌnsieɪt/','📢'),('mumble','พูดพึมพำ','/ˈmʌmbl/','🤐'),
   ('accentuate','เน้นให้เด่นชัด','/əkˈsentʃueɪt/','🔆'),('diction','การเลือกใช้ถ้อยคำ','/ˈdɪkʃn/','🎼'),
   ('cadence','จังหวะทำนองการพูด','/ˈkeɪdns/','🌊'),('elision','การกลืนเสียง','/ɪˈlɪʒn/','✂️'),
   ('liaison','การเชื่อมเสียงระหว่างคำ','/liˈeɪzɒn/','🪢'),('minimalpair','คู่คำต่างเสียงเดียว','/ˈmɪnɪmlpeə(r)/','⚖️'),
   ('shadow','พูดตามทันทีที่ได้ยิน','/ˈʃædəʊ/','🎧')],
  "To enunciate is to finish the ends of your words. People mumble when they are unsure, not when they are quiet. Accentuate the word that carries the new information. Diction is the choice of words; delivery is what you do with them. A natural cadence is what makes a fluent speaker restful to listen to. Elision is why did you sounds like one word in real speech. Liaison joins the end of one word to the start of the next. A minimalpair like ship and sheep trains one sound at a time. To shadow a recording is the fastest exercise for rhythm.",
  ["To enunciate is to finish the ends of your words.",
   "Accentuate the word that carries the new information.",
   "A natural cadence is what makes a fluent speaker restful to listen to.",
   "Liaison joins the end of one word to the start of the next.",
   "To shadow a recording is the fastest exercise for rhythm."],
  ["To enunciate is to finish the ends of your words.",
   "Accentuate the word that carries the new information.",
   "To shadow a recording is the fastest exercise for rhythm."],
  "What does it mean to enunciate?","To finish the ends of your words."),
]
for d in W:
    out = build(d)
    fn = 'Day%d_%s_B2.html' % (d['n'], d['title'].replace(' ','').replace("'",'').replace(',',''))
    open(OUT+fn,'w',encoding='utf-8').write(out)
    print('OK', fn, len(d['words']))
